module.exports = {
"004":"정답 ③ joined — made. make a good soldier(훌륭한 군인이 되다) + join the army.",
"014":"정답 ③ lies in. 주어 The secret(단수) → lies; the secret lies in ~(~에 있다).",
"015":"정답 ① raised → risen. 물가는 자동사 rise(rise-rose-risen). raise는 타동사라 목적어 필요.",
"020":"정답 ③ say. say (that) ~ is service(that절 목적어). talk/speak는 자동사.",
"021":"정답 ④ made me a cake. 4형식 make + 간접목적어 + 직접목적어.",
"022":"정답 ② 오류. ask such questions to your parents → ask your parents ~ / ask ~ of your parents.",
"023":"정답 ③ cost. cost는 4형식(cost + 사람 + 사물). cost a lot of fame to her의 to는 불가.",
"024":"정답 ③ describe it to me. describe는 4형식 불가 → describe + 목적어 + to + 사람.",
"025":"정답 ③ to us. explain to + 사람.",
"028":"정답 ① says. 시계가 시각을 가리킬 때 say. told(과거)는 부적절.",
"029":"정답 ② told. tell + 사람 + that절. say는 to 필요, converse/talk는 that절 목적어 불가.",
"030":"정답 ④ Ellen told Helen that ~. tell + 사람 + that절. 나머지는 tell to 사람 오류.",
"031":"정답 ① remind. remind + 사람 + of. remember/recall은 of와 안 씀.",
"036":"정답 ② ambush their prey. predators(복수) → their; help + 목적어 + (to)동사원형.",
"037":"정답 ② wrung → wringing. keep + 목적어 + ~ing(능동: 손을 비비고 있다).",
"040":"정답 ④ 오류. forbade me smoke → forbade me to smoke. forbid + 목적어 + to부정사.",
"041":"정답 ① was → were. 주어 Latin and French(복수).",
"042":"정답 ③ has → have. 주어가 두 개척자(복수).",
"044":"정답 ③ was. not only A but also B는 B(manager 단수)에 동사 일치.",
"045":"정답 ② know. Either A or B는 B(children 복수)에 일치.",
"050":"정답 ② are → is. every ~ and ~는 단수 취급.",
"052":"정답 ④ differ → differs. neither는 단수.",
"056":"정답 ① has → have. 주어 60% of forests(복수).",
"057":"정답 ① facilitate → facilitates. 주어 government(단수, 현재).",
"058":"정답 ② have → has. 주어 The variation(단수).",
"062":"정답 ① was. 도치문 주어 a fire(단수).",
"065":"정답 ④ is denied → are denied. 주어 many in the world(복수).",
"076":"정답 ⑤ seems → seem. 선행사 pollutants(복수).",
"079":"정답 ③ he was → they were. 주어 the coach and the team captain(복수).",
"081":"정답 ① has been → was. until 1797(과거)이라 현재완료 불가.",
"083":"정답 ③ had taken. 발견(과거)보다 이전 동작 → 과거완료.",
"090":"정답 ④ was → is. what our health is like(일반적 사실, 현재).",
"096":"정답 ② complete. 시간부사절(as soon as)에서 미래는 현재로.",
"108":"정답 ① has been pursuing → pursued. until he graduated last May(과거)와 충돌.",
"120":"정답 ④ knows → knew. The last time ~ was named(과거)에 시제 일치.",
"130":"정답 ④ were to fail. 가정법 미래(if S were to 동사원형).",
"150":"정답 ④ I decided. it's about time + 가정법 과거.",
"161":"정답 ② that they think. 삽입절 they think + 목적격 관계절.",
"162":"정답 ② who. they say는 삽입, speaks의 주어 → 주격 who.",
"166":"정답 ② who → whose. whose desire was ~(소유격 관계대명사).",
"167":"정답 ② whom → of whom/whose. the diagnosis of whom is known.",
"169":"정답 ④ whose. whose short-wave radio(소유격, 명사 앞).",
"173":"정답 ③ that. the first man 뒤에는 관계대명사 that(주격); whom 불가.",
"174":"정답 ④ that → which. through which(전치사 + 관계대명사). 전치사 + that 불가.",
"175":"정답 ④ that → which. 계속적 용법(콤마) 뒤에는 that 불가.",
"176":"정답 ③ what → that/which. 선행사 a budget가 있으므로 what 불가.",
"177":"정답 ① What. What ~ lies behind slang is ~(주어 역할 명사절).",
"179":"정답 ① what. made me what I am(현재의 나).",
"180":"정답 ④ what words are. A is to B what C is to D 구문.",
"181":"정답 ① whatever its size. no matter what its size(양보).",
"182":"정답 ③ happens. Whatever happens(현재형으로 미래 표현).",
"184":"정답 ② whenever. 절을 이끄는 부사절 접속사. however는 부적합.",
"186":"정답 ③ whoever. came의 주어 → 주격 복합관계대명사.",
"188":"정답 ④ where. a dry place where ~(장소 관계부사).",
"189":"정답 ② where. the White House, where the president works(관계부사).",
"191":"정답 ① where ~ in의 in 중복. universe where I live(in 삭제).",
"192":"정답 ④ the way. the way (that) ~; the way how는 불가.",
"193":"정답 ② The way I look at it. 내가 보기엔(관용).",
"194":"정답 ③ existing → exist. the reason journalists exist(관계절 동사).",
"195":"정답 ④ but. not one of us but wishes ~(유사관계대명사 but = that ~ not).",
"196":"정답 ⑤ There is no man but commits errors(누구나 실수한다).",
"197":"정답 ① at which. the rate at which you comprehend.",
"198":"정답 ④ which tend. in which tend의 in 불필요 → which tend(주격).",
"200":"정답 ② for which I am grateful(전치사 + 관계대명사). 나머지는 전치사 누락/중복.",
"202":"정답 ③ disappointed → disappointing. 시험이 실망스러운 것(능동).",
"203":"정답 ② nonpolluted → nonpolluting. 오염시키지 않는 차(능동).",
"207":"정답 ① Reading → Having read. 완료 분사구문(읽고 난 뒤).",
"208":"정답 ① Having eaten → Eating. 먹는 동안 일어난 일(동시동작).",
"209":"정답 ③ having been assumed → having assumed(능동: 그들이 추정).",
"213":"정답 ② Not having met him before. 부정 + 완료 분사구문.",
"214":"정답 ③ him watching. with + 목적어 + 분사(능동).",
"216":"정답 ① 현수분사. traveling의 주체는 the idea가 아니라 him.",
"221":"정답 ① ; however. 두 독립절은 세미콜론 + however로 연결.",
"222":"정답 ② but. 대조(진짜 달걀은 아니지만 ~처럼 보임).",
"223":"정답 ④ whereas. 지금(차가운 음식) vs 예전(갓 지은 식사) 대조.",
"226":"정답 ② to ability → ability. 병렬(of intellect, aptitude … or ability).",
"231":"정답 ③ Whether. Whether ~ or ~ depends on(명사절).",
"232":"정답 ④ Whether or not. ~인지 아닌지(명사절 주어).",
"233":"정답 ① whether the federal government. whether A or B.",
"236":"정답 ③ although. 절을 이끄는 접속사. despite는 명사를 받음.",
"239":"정답 ② until. ~이 확인될 때까지 응답 안 함.",
"241":"정답 ③ the president's not informing them. 동명사 의미상 주어(소유격) + 부정.",
"242":"정답 ② him → his. 동명사 의미상 주어는 소유격.",
"244":"정답 ③ me → my. 동명사 의미상 주어는 소유격.",
"245":"정답 ④ having stolen. confess to + 동명사(완료: 이전 행위).",
"246":"정답 ② to waste → wasting. avoid + 동명사.",
"247":"정답 ② to buy → buying. finish + 동명사.",
"250":"정답 ① receiving. acknowledge + 동명사.",
"251":"정답 ② get → getting. devotion to(전치사 to) + 동명사.",
"256":"정답 ⑤ worth of telling → worth telling. worth + 동명사(of 불가).",
"259":"정답 ④ to testing. be opposed to(전치사 to) + 동명사.",
"260":"정답 ④ to boosting. contribute to(전치사 to) + 동명사.",
"261":"정답 ④ for him to decide. 의미상 주어 for + 목적격 + to부정사.",
"262":"정답 ③ to giving → to give. the time for ~ to give(부정사).",
"263":"정답 ② For. For + 명사 + to부정사(~가 …하려면).",
"264":"정답 ③ for — to feel loved. in order for + 목적어 + to부정사.",
"265":"정답 ③ if. if they are to be healthy(be to: 의도/조건).",
"267":"정답 ④ urged. urge + 목적어 + to부정사. call for는 이 구문 불가.",
"268":"정답 ④ I accept. demand + (that) + 주어 + (should)동사원형(가정법 현재).",
"271":"정답 ④ sustaining → to sustain. hope + to부정사.",
"274":"정답 ③ to pretend to be in control. hope + to부정사.",
"275":"정답 ③ to have begun — to run. 과거 시작(완료부정사) + compel + 목적어 + to부정사.",
"277":"정답 ① to have learned → to learn. had hoped to 동사원형(이루지 못한 소망).",
"279":"정답 ③ considered marrying ~, but decided not to. consider + 동명사.",
"283":"정답 ① was originated → originated. originate는 자동사(수동 불가).",
"288":"정답 ② to be reminded of. 창밖만 봐도 ~을 떠올리게 된다(수동 부정사).",
"289":"정답 ④ was convincing → was convinced. 확신하는(수동).",
"290":"정답 ③ was denied. deny + 사람 + 사물의 수동(was denied time off).",
"291":"정답 ② which is considered. 계속적 관계절(콤마) + 수동.",
"292":"정답 ① is acknowledged. acknowledge A as B의 수동.",
"293":"정답 ④ are not allowed. 주어 the desires(복수) + 수동.",
"294":"정답 ③ help the housework → help with the housework.",
"297":"정답 ② wasn't noticed entering. 지각동사 수동태(~ing 유지).",
"298":"정답 ④ It is believed. It is believed that ~(가주어 수동).",
"299":"정답 ③ is said. Politics(단수) + be said to be.",
"300":"정답 ④ are supposed. be supposed to 동사원형(~하기로 되어 있다).",
"305":"정답 ② should have finished. 지난 금요일에 끝냈어야 했다(후회).",
"308":"정답 ③ must have been. 과거에 대한 강한 추측(틀림없이 ~였다).",
"309":"정답 ① must have been being interrogated(과거진행 수동 + 과거 추측).",
"312":"정답 ② need not have gone. 갔지만 갈 필요 없었다.",
"316":"정답 ① who used to using → who are used to using(~에 익숙하다).",
"318":"정답 ③ could have been broken. 깨졌을 수도 있었다(과거 가능성).",
"320":"정답 ③ the prisoner be sentenced. suggestion that + (should)동사원형.",
"321":"정답 ④ not so sweet. not so ~ as(원급 부정). sweeter 중복 불가.",
"323":"정답 ③ as. not so much A as B.",
"324":"정답 ③ as. as many ~ as.",
"327":"정답 ③ the better suited. 둘 중(of the two) 비교 → 비교급 + the.",
"328":"정답 ① the larger of which. 사무실이 둘이므로 비교급 larger.",
"330":"정답 ② I don't like him the less because ~(none the less).",
"333":"정답 ① is the sport → the sport is. the + 비교급 절은 도치하지 않음.",
"335":"정답 ① much more. 긍정문(자유는 물론 생명도) → much more.",
"336":"정답 ② less. 부정문(하물며 부정직은) → still less.",
"337":"정답 ③ no less beautiful than ~(누이만큼 아름답다).",
"338":"정답 ① fastest. runs fastest among ~(부사 최상급).",
"340":"정답 ③ most famous. 소유격 뒤 최상급은 the 없이.",
"341":"정답 ② easier. much + 비교급.",
"345":"정답 ③ the most. by far the most exciting(최상급 강조).",
"346":"정답 ④ the most important import. 주어 = 수입품(By far the most important import of Korea is oil).",
"347":"정답 ③ as great as. 배수사 + as ~ as.",
"349":"정답 ③ twice as much as. 돈은 much(불가산).",
"352":"정답 ③ as much effort. twice as much effort (as).",
"353":"정답 ④ twice as likely. 배수사 + as ~ as.",
"354":"정답 ② the Earth → the Earth's / that of the Earth. 비교대상 일치(기후끼리).",
"356":"정답 ④ Englishman → an Englishman's. 비교대상 일치(억양끼리).",
"358":"정답 ② me → I. than + 주격(than I did).",
"359":"정답 ④ planet is → planet (does). than any other + 단수명사.",
"360":"정답 ④ by what → (upon) what. 병렬(upon ~ rather than upon ~).",
"361":"정답 ④ isn't he. is going to be nominated의 부가의문문.",
"362":"정답 ② will you. 명령문의 부가의문문.",
"363":"정답 ③ I don't think he is smart, is he?(부정 전이).",
"366":"정답 ① there have → have there. Hardly ever 문두 → 도치.",
"367":"정답 ③ do meteors blaze. Rarely 문두 → 도치.",
"372":"정답 ③ it is finding → is it finding. only now 문두 → 도치.",
"374":"정답 ② so will I. so + 조동사 + 주어.",
"375":"정답 ④ John does so → so does John. 동의 도치.",
"376":"정답 ④ Neither do I. 부정 동의(나도 안 그렇다).",
"378":"정답 ② Here comes your teacher. 명사 주어는 도치, 대명사는 도치 불가.",
"379":"정답 ③ was sitting the guest of honor. 장소부사 + 동사 + 주어(완전도치).",
"382":"정답 ① clothings → clothing. 불가산명사(복수형 없음).",
"383":"정답 ② some information. information은 불가산.",
"388":"정답 ② makes → make. The statistics(수치, 복수).",
"390":"정답 ④ There was little wine left in the bottle(불가산 + little).",
"396":"정답 ④ billions → billion. 숫자 뒤 단위는 단수($15 billion).",
"398":"정답 ⑤ hundred → hundreds. hundreds of years.",
"400":"정답 ① some of John's friends. 복수 → were.",
"405":"정답 ④ She looked me in the face(신체 부위 the, 관용).",
"407":"정답 ② of Rocky Mountains → the Rocky Mountains. 산맥은 the.",
"408":"정답 ① in Netherlands → in the Netherlands. 국가명에 the.",
"409":"정답 ② in the 1840s. in the + 연대.",
"410":"정답 ④ Teachers for the mentally retarded(정신지체아를 위한 교사).",
"412":"정답 ② the door to the door → door to door(무관사 관용).",
"415":"정답 ③ what kind of substance. kind of + 무관사 명사.",
"417":"정답 ② a night. so + 형용사 + a + 명사.",
"418":"정답 ① quite a short time. quite a + 형용사 + 명사 어순.",
"420":"정답 ② too honest a. too + 형용사 + a + 명사.",
"421":"정답 ③ itself → themselves. 주어 people(복수).",
"422":"정답 ② themselves → them. 관찰 대상은 ants(목적격 them).",
"424":"정답 ④ themselves → them. interest의 목적어(주어와 다름).",
"425":"정답 ① unconsciously. in spite of oneself = 자기도 모르게.",
"427":"정답 ③ one. 잃어버린 시계 대신 같은 종류 하나 → one.",
"430":"정답 ① such a thing like → such a thing as.",
"432":"정답 ③ another → the other. 둘 중 나머지는 the other.",
"433":"정답 ④ the other. 두 발 중 나머지 하나 → the other.",
"438":"정답 ④ every of → every one of / each of.",
"440":"정답 ① their own → its own. Every fuel(단수).",
"443":"정답 ② alike. 서술용법(are exactly alike).",
"444":"정답 ① not alike → unlike. alike는 전치사로 못 씀(unlike).",
"445":"정답 ④ authentic Japanese food. 형용사 어순(의견 + 국적 + 명사).",
"447":"정답 ③ big blue plastic. 어순(크기 + 색 + 재료).",
"450":"정답 ③ they were difficult to answer(tough 구문).",
"451":"정답 ② for us to get on with. 의미상 주어 for + to부정사.",
"452":"정답 ④ worth. be worth + 명사.",
"453":"정답 ④ is not worthy가 오류. worthy는 of 필요.",
"454":"정답 ③ strong enough to walk. 형용사 + enough + to부정사.",
"458":"정답 ① most. most people(대부분의 사람들).",
"459":"정답 ④ most of. most of the + 명사.",
"460":"정답 ③ most → almost. almost all the money.",
"462":"정답 ④ by ship. 교통수단 by + 무관사.",
"464":"정답 ① in. in color(관용).",
"470":"정답 ② between. distinguish between A and B.",
"471":"정답 ④ to → and. between A and B.",
"473":"정답 ③ as. present A as B(~로서 주다).",
"474":"정답 ③ like a wealthy man. feel like + 명사(as if는 절을 받음).",
"479":"정답 ④ Save that there are ~(~을 제외하면). There are는 런온(접속 불가).",
"480":"정답 ① As far as I remember ~. 나머지는 as regards / besides / except 오류."
};
