// LOGIC TREE V502 — Categories 061-070
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"061",words:["bountiful", "freehanded", "generous", "hospitable", "lavish", "liberal", "magnanimous", "munificent", "openhanded", "ungrudging", "unstinting", "Lilliputian", "narrow-minded", "hidebound", "indulgent", "permissive", "tolerant"]},
  {id:"062",words:["apposite", "appropriate", "apt", "germane", "meet", "pertinent", "proper", "relevant", "suitable"]},
  {id:"063",words:["extraneous", "extrinsic", "impertinent", "improper", "inappropriate", "inapt", "irrelevant", "unsuitable"]},
  {id:"064",words:["buffoon", "clown", "motley"]},
  {id:"065",words:["agog", "febrile", "feral", "ferocious", "fierce", "frantic", "frenetic", "frenzied"]},
  {id:"066",words:["afflict", "aggrieve", "annoy", "bait", "distress", "excruciate", "gruel", "infest", "molest", "persecute", "pester", "rankle", "torment", "torture", "tribulate", "wreak", "harass", "harrow"]},
  {id:"067",words:["credo", "creed", "doctrine", "tenet"]},
  {id:"068",words:["amend", "correct", "debug", "disabuse", "emend", "qualify", "recast", "reclaim", "rectify", "redress", "revamp"]},
  {id:"069",words:["curmudgeon", "hoarder", "miser", "niggard", "skinflint"]},
  {id:"070",words:["classify", "demarcate", "discriminate", "ramify"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "Lilliputian":"소인국의; 편협한 사람",
  "afflict":"괴롭히다",
  "aggrieve":"(사람을) 학대하다",
  "agog":"(열망·호기심·기대 등으로) 열광하여",
  "amend":"(의안 등을) 수정하다",
  "annoy":"괴롭히다",
  "apposite":"적절한",
  "appropriate":"-에 적합한",
  "apt":"적절한",
  "bait":"괴롭히다",
  "bountiful":"관대한",
  "buffoon":"어릿광대",
  "classify":"분류하다",
  "clown":"광대",
  "correct":"바로잡다",
  "credo":"신조",
  "creed":"교의",
  "curmudgeon":"구두쇠; 심술궂은 사람",
  "debug":"-의 결함을 조사하여 제거하다",
  "demarcate":"-을 분리하다",
  "disabuse":"-의 어리석음을 깨우치다",
  "discriminate":"구별하다",
  "distress":"비탄, 고통",
  "doctrine":"교리",
  "emend":"(문서·잘못 따위를) 교정하다",
  "excruciate":"몹시 고통을 주다",
  "extraneous":"무관계한; 연고 없는",
  "extrinsic":"비본질적인",
  "febrile":"열광적인",
  "feral":"야성적인",
  "ferocious":"사나운",
  "fierce":"흉포한",
  "frantic":"미친 듯 날뛰는",
  "freehanded":"아낌없이 쓰는",
  "frenetic":"발광한",
  "frenzied":"열광한",
  "generous":"아량 있는",
  "germane":"밀접한 관계가 있는",
  "gruel":"호되게 벌주다",
  "harass":"괴롭히다",
  "harrow":"약탈하다",
  "hidebound":"편협한",
  "hoarder":"축적가",
  "hospitable":"후히 대접하는",
  "impertinent":"무례한",
  "improper":"부적당한",
  "inappropriate":"온당치 않은",
  "inapt":"부적당한",
  "indulgent":"눈감아 주는",
  "infest":"(해충·동물 등이) 떼 지어 몰려들다",
  "irrelevant":"부적절한; 무관계한",
  "lavish":"(소비 따위가) 분별없는",
  "liberal":"관대한",
  "magnanimous":"도량이 넓은",
  "meet":"적합한, 어울리는",
  "miser":"구두쇠",
  "molest":"(짓궂게) 괴롭히다",
  "motley":"잡색의, 얼룩덜룩한",
  "munificent":"인색하지 않은",
  "narrow-minded":"마음이 좁은",
  "niggard":"인색한 사람, 구두쇠",
  "openhanded":"손이 큰, 아끼지 않는",
  "permissive":"응석을 받아주는",
  "persecute":"(종교·주의 따위를 이유로) 박해하다",
  "pertinent":"타당한",
  "pester":"고통을 주다",
  "proper":"적당한",
  "qualify":"누그러뜨리다, 진정하다",
  "ramify":"작게 구분되다",
  "rankle":"-을 짜증나게 하다",
  "recast":"고쳐 만들다",
  "reclaim":"교정하다",
  "rectify":"시정(是正)하다",
  "redress":"(부정·불균형 따위를) 고치다",
  "relevant":"(당면한 문제에) 관련된",
  "revamp":"개조하다, 수리하다",
  "skinflint":"인색한 사람, 구두쇠",
  "suitable":"-에 적당한",
  "tenet":"주의(doctrine)",
  "tolerant":"관대한",
  "torment":"고통",
  "torture":"고문",
  "tribulate":"억압하다",
  "ungrudging":"아끼지 않는",
  "unstinting":"무제한으로 주어진, 무조건의",
  "unsuitable":"부적당한",
  "wreak":"(분노를) 터뜨리다"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "061":"관대한, 후한, 인심 좋은",
  "062":"관련된, 적절한, 중용한",
  "063":"관련 없는, 부적절한",
  "064":"광대",
  "065":"광란의, 맹렬한",
  "066":"괴롭히다",
  "067":"교의, 신조",
  "068":"교정하다, 수정하다",
  "069":"구두쇠",
  "070":"구분하다, 구별하다"
});
