// LOGIC TREE V502 — Categories 031-040
// Auto-generated from V502.pdf pages 9-10

window.__V502_EXT__ = window.__V502_EXT__ || {};
window.__V502_EXT__.categories = window.__V502_EXT__.categories || [];
window.__V502_EXT__.wordMeanings = window.__V502_EXT__.wordMeanings || {};
window.__V502_EXT__.categorySummaries = window.__V502_EXT__.categorySummaries || {};
window.__V502_EXT__.confusionNotes = window.__V502_EXT__.confusionNotes || {};

window.__V502_EXT__.categories.push(
  {
    id: "031",
    words: [
      "idle",
      "indolent",
      "slothful",
      "slovenly",
      "sluggard",
      "sluggish",
      "slouch",
      "sloven",
    ],
  },
  {
    id: "032",
    words: [
      "revulsion",
      "upheaval",
      "vicissitude",
    ],
  },
  {
    id: "033",
    words: [
      "adage",
      "aphorism",
      "apothegm",
      "apophthegm",
      "dictum",
      "epigram",
      "gnome",
      "maxim",
      "precept",
      "witticism",
    ],
  },
  {
    id: "034",
    words: [
      "coda",
      "denouement",
      "envoy",
      "epilogue",
      "explicit",
      "finale",
      "peroration",
      "outrance",
      "upshot",
    ],
  },
  {
    id: "035",
    words: [
      "conjugal",
      "connubial",
      "marital",
      "matrimonial",
      "nuptial",
    ],
  },
  {
    id: "036",
    words: [
      "humility",
      "modesty",
      "humbleness",
    ],
  },
  {
    id: "037",
    words: [
      "border",
      "bound",
      "boundary",
      "brim",
      "brink",
      "edge",
      "fringe",
      "margin",
      "rim",
      "verge",
    ],
  },
  {
    id: "038",
    words: [
      "alert",
      "vigilant",
      "wary",
      "watchful",
      "wide-awake",
    ],
  },
  {
    id: "039",
    words: [
      "abase",
      "belittle",
      "contemn",
      "debase",
      "degrade",
      "deprecate",
      "despise",
      "disdain",
      "disparage",
      "scorn",
      "underestimate",
      "underrate",
      "understate",
      "minimize",
      "contemptuous",
      "disdainful",
      "scornful",
      "contemptible",
      "despicable",
      "ignominious",
      "ignoble",
      "humble",
      "scurvy",
    ],
  },
  {
    id: "040",
    words: [
      "brash",
      "rash",
      "headlong",
      "heady",
      "impetuous",
      "imprudent",
      "impulsive",
      "precipitant",
      "precipitate",
      "precipitous",
      "flippant",
      "frivolous",
      "giddy",
      "nervous",
      "restive",
      "skittish",
      "levity",
    ],
  }
);

Object.assign(window.__V502_EXT__.wordMeanings, {
  // 031 — lazy / idle
  idle: "태만한",
  indolent: "나태한",
  slothful: "굼뜬",
  slovenly: "(옷차림이) 단정치 못한",
  sluggard: "게으름쟁이",
  sluggish: "게으른",
  slouch: "구부정한 걸음걸이",
  sloven: "꾀죄죄한 사람",

  // 032 — upheaval
  revulsion: "(감정의 격변) 혐오; 불쾌",
  upheaval: "(사회 등의) 대격변",
  vicissitude: "변화",

  // 033 — adage / saying / epigram
  adage: "격언",
  aphorism: "금언, 격언",
  apothegm: "격언",
  apophthegm: "격언",
  dictum: "(권위자, 전문가의) 공식 견해",
  epigram: "경구, 짧은 풍자시",
  gnome: "격언",
  maxim: "격언",
  precept: "교훈, 격언",
  witticism: "재치 있는 말",

  // 034 — finale / ending
  coda: "악곡의 종결부",
  denouement: "연극의 대단원",
  envoy: "시, 산문, 연극의 종결부",
  epilogue: "발문, 산문의 종결부",
  explicit: "소설 등의 대미",
  finale: "악곡의 마지막 악장, 연극의 마지막 장",
  peroration: "연설의 종결부",
  outrance: "싸움의 끝",
  upshot: "일의 결말",

  // 035 — marital / conjugal
  conjugal: "결혼의, 배우자의",
  connubial: "결혼의, 부부의",
  marital: "남편의, 혼인의",
  matrimonial: "결혼의",
  nuptial: "결혼(식)의",

  // 036 — humility
  humility: "겸손",
  modesty: "겸손",
  humbleness: "겸손함; 하찮음",

  // 037 — border / edge
  border: "테두리",
  bound: "(안쪽에서 본) 경계(선)",
  boundary: "경계(선)",
  brim: "(컵 등의) 가장자리",
  brink: "(벼랑 따위의) 가장자리",
  edge: "끝머리",
  fringe: "(스카프, 숄 따위의) 술 장식; 가장자리",
  margin: "가장자리",
  rim: "(특히 원형물의) 가장자리",
  verge: "가장자리",

  // 038 — alert / vigilant
  alert: "방심 않는",
  vigilant: "자지 않고 지키는",
  wary: "경계하는",
  watchful: "주의하는",
  "wide-awake": "완전히 잠이 깬; 정신을 바짝 차린",

  // 039 — despise / scorn
  abase: "깎아내리다",
  belittle: "얕잡다",
  contemn: "모욕하다",
  debase: "(인품·품위·가치 따위를) 떨어뜨리다",
  degrade: "지위를 낮추다",
  deprecate: "업신여기다; 반대하다",
  despise: "경멸하다",
  disdain: "업신여기다; 업신여김",
  disparage: "폄하하다",
  scorn: "경멸하다",
  underestimate: "과소평가하다",
  underrate: "경시하다",
  understate: "삼가서 말하다",
  minimize: "경시하다, 얕보다",
  contemptuous: "경멸적인",
  disdainful: "업신여기는",
  scornful: "경멸하는",
  contemptible: "비열한",
  despicable: "경멸할 만한",
  ignominious: "수치스러운",
  ignoble: "비열한",
  humble: "(신분 등이) 천한; 겸손한",
  scurvy: "상스러운; 괴혈병",

  // 040 — brash / rash / reckless
  brash: "경솔한, 분별없는",
  rash: "경솔한, 분별없는",
  headlong: "성급한, 매우 서두는",
  heady: "무모한",
  impetuous: "성급한, 충동적인",
  imprudent: "경솔한",
  impulsive: "충동적인",
  precipitant: "경솔한, 덤벙이는",
  precipitate: "조급히 구는, 경솔한",
  precipitous: "경솔한, 무모한",
  flippant: "경박한",
  frivolous: "경솔한",
  giddy: "경솔한, 들뜬",
  nervous: "흥분하기 쉬운; 신경질적인",
  restive: "마음이 들뜬",
  skittish: "들뜬; 겁 많은",
  levity: "경박함, 촐싹거림",
});

Object.assign(window.__V502_EXT__.categorySummaries, {
  "031": "lazy / idle",
  "032": "upheaval / revulsion",
  "033": "adage / saying / epigram",
  "034": "finale / ending",
  "035": "marital / conjugal",
  "036": "humility / modesty",
  "037": "border / edge",
  "038": "alert / vigilant",
  "039": "despise / scorn",
  "040": "brash / rash / reckless",
});

Object.assign(window.__V502_EXT__.confusionNotes, {
  // 031
  idle: "게으른, 빈둥거리는. 기계의 '공회전' 뜻도 있어 문맥 주의.",
  indolent: "나태한. 의학적으로는 '무통성(통증이 없는)' 궤양을 뜻하기도.",
  slothful: "나무늘보(sloth)처럼 굼뜬. 느리고 게으른 느낌.",
  slovenly: "옷차림이나 외모가 단정치 못한. 게으름이 겉모습으로 드러난 경우.",
  sluggard: "'게으름쟁이' 명사형. 형용사 sluggish와 구분.",
  sluggish: "형용사. 느리고 활기 없는.",
  slouch: "구부정한 자세/걸음걸이. 게으른 태도의 상징적 모습.",
  sloven: "꾀죄죄하고 단정치 못한 사람. slovenly의 명사형.",

  // 032
  revulsion: "급격한 감정 변화로 인한 혐오감. 'revulsion of feeling'.",
  upheaval: "사회·정치적 대격변. 지질학적으로는 '융기'.",
  vicissitude: "인생의 부침, 변화무쌍함. 주로 복수형(vicissitudes)으로 씀.",

  // 033
  adage: "오랜 세월 전해 내려온 격언. proverb와 유사.",
  aphorism: "짧고 재치 있는 금언. 철학적 정의(定義)의 느낌.",
  apothegm: "aphorism과 거의 동의어. 다소 고어체.",
  apophthegm: "apothegm의 다른 철자.",
  dictum: "권위자의 공식 견해. 'obiter dictum'(방론)이라는 법률 용어로도 쓰임.",
  epigram: "짧고 재치 있는 풍자시. Oscar Wilde의 경구가 대표적.",
  gnome: "짧은 격언. 'gnomic'은 격언체의, 간결한.",
  maxim: "행동 원칙을 제시하는 격언. 'Maxim gun'과 혼동 주의.",
  precept: "도덕적 행동 규범으로서의 격언. 교훈적 성격이 강함.",
  witticism: "재담, 재치 있는 말. epigram보다 가볍고 유머러스함.",

  // 034
  coda: "음악의 종결부. 문학에서는 소설의 마무리 부분.",
  denouement: "프랑스어에서 유래. 소설·연극의 해결·대단원.",
  envoy: "'외교 사절' 뜻이 먼저 떠오르지만, 시의 종결연(stanza)도 뜻함.",
  epilogue: "책·연극의 마지막 부분. prologue(서문)의 반대.",
  explicit: "'분명한' 뜻이 먼저 떠오르지만, 중세 필사본의 'explicit'(끝)는 여기서.",
  finale: "음악·연극의 대미. 'grand finale'.",
  peroration: "연설의 최종 정리 부분. 웅변적으로 결론 맺는 느낌.",
  outrance: "프랑스어 'à outrance'(극한까지). 싸움의 최종 결말.",
  upshot: "일의 최종 결과·결론. 'the upshot is that...' 구문.",

  // 035
  conjugal: "부부 관계의. 'conjugal visit'(부부 면회).",
  connubial: "결혼 생활의 행복한 측면을 강조하는 시적인 단어.",
  marital: "남편(maritus)에 더 기운 단어. 'marital discord'.",
  matrimonial: "혼인 제도 자체에 초점. 'matrimonial proceedings'(혼인 소송).",
  nuptial: "결혼식 자체의. 주로 복수형 nuptials(결혼식).",

  // 036
  humility: "자기를 낮추는 겸손. 기독교적 미덕.",
  modesty: "자기 과시를 삼가는 겸손. 외모·태도의 겸허함.",
  humbleness: "humility와 유사하나 '하찮음, 천함'이라는 중립적·부정적 뜻도 있음.",

  // 037
  border: "가장 일반적인 '경계'. 국가 간 국경, 물건의 테두리.",
  bound: "안쪽에서 본 경계선. 흔히 복수형 bounds(범위, 한계).",
  boundary: "경계선 자체를 가리키는 가장 중립적 단어.",
  brim: "컵·모자 등의 윗 가장자리. 'brimming with tears'.",
  brink: "벼랑·절벽의 가장자리. 비유적으로 '위기의 직전'(on the brink of).",
  edge: "날카로운 모서리·끝. 'cutting edge'(최첨단).",
  fringe: "가장자리 장식술. 비유적으로 '주변부, 변두리'(fringe group).",
  margin: "페이지 여백. 비유적으로 '차이, 여유'(margin of error).",
  rim: "원형 물체의 테두리. 안경테, 바퀴 테.",
  verge: "가장자리. 'on the verge of'(~하기 직전의) 구문.",

  // 038
  alert: "위험에 대비해 방심하지 않는. 'stay alert'.",
  vigilant: "자지 않고 계속 지키는. 경계의 지속성을 강조.",
  wary: "의심을 품고 조심하는. 'be wary of strangers'.",
  watchful: "눈으로 계속 주시하는. vigilant보다 시각적 감시에 초점.",
  "wide-awake": "잠에서 완전히 깨어 정신이 바짝 든. 비유적 경계.",

  // 039
  abase: "자기를 낮추다. 'abase oneself'. 타인을 깎아내린다는 느낌.",
  belittle: "작게(be-little) 만들다. 깔보고 무시하는 태도.",
  contemn: "경멸하다. 'contempt'의 동사형. 현대에는 잘 안 쓰이는 격식어.",
  debase: "품위·가치를 떨어뜨리다. 화폐 가치 절하에도 씀.",
  degrade: "지위·품위를 강등시키다. 생물학적 '분해'와는 다름.",
  deprecate: "업신여기며 반대하다. 'self-deprecating'(자기를 낮추는).",
  despise: "강한 혐오로 경멸하다. 가장 강한 어감의 경멸어.",
  disdain: "우월감에서 나오는 경멸. 상대를 아래로 보는 느낌.",
  disparage: "비방하여 가치를 깎아내리다. 근거 없는 폄하.",
  scorn: "분노 섞인 강한 경멸. despise보다 감정적인 어감.",
  underestimate: "과소평가하다. 능력·가치를 실제보다 낮게 봄.",
  underrate: "과소평가하다. underestimate와 유사하나 더 평가(evaluate)적.",
  understate: "실제보다 축소해서 말하다. 반어법의 수사적 기법.",
  minimize: "최소화하다. 의도적으로 작게 보이게 하다.",
  contemptuous: "경멸감을 드러내는(형용사).",
  disdainful: "업신여기는 태도를 보이는.",
  scornful: "경멸과 조소를 담은.",
  contemptible: "경멸받아 마땅한. 수동적 의미(경멸을 받는 대상).",
  despicable: "경멸스러운. 'Despicable Me'(슈퍼배드)로 익숙할 수 있음.",
  ignominious: "치욕스러운. 공개적 수치와 불명예를 동반.",
  ignoble: "고귀하지 못한, 비열한. noble(고귀한)의 반대.",
  humble: "'겸손한'이라는 긍정적 뜻도 있으나, 여기서는 '천한' 부정적 뜻.",
  scurvy: "괴혈병이라는 의학적 뜻도 있음. 'scurvy trick'(비열한 술책).",

  // 040
  brash: "경솔하고 뻔뻔스러운. 젊은 층의 무모함을 묘사할 때 자주 씀.",
  rash: "성급하게 행동하는. 피부 '발진' 뜻도 있어 문맥 주의.",
  headlong: "머리부터 곤두박질치듯 저돌적으로. 신중함의 결여.",
  heady: "취하게 하는, 도취적인. 무모할 정도로 흥분된 상태.",
  impetuous: "충동적으로 행동하는. 생각보다 행동이 먼저인.",
  imprudent: "신중하지 못한. prudent(신중한)의 반대.",
  impulsive: "충동적인. 통제가 안 되는 즉각적 충동.",
  precipitant: "precipitate의 동의어. 성급하게 굴러떨어지는 느낌.",
  precipitate: "촉진하다/성급한. 화학의 '침전물' 뜻도 있어 문맥 필수 확인.",
  precipitous: "가파른 절벽 같은. 비유적으로 극도로 성급한.",
  flippant: "진지하지 않고 경박한. 시시한 농담을 하는 태도.",
  frivolous: "경박하고 하찮은. 'frivolous lawsuit'(가벼운 소송)처럼 법률 용어로도 씀.",
  giddy: "어지럽고 들뜬. 'giddy with excitement'(들떠서 어쩔 줄 모르는).",
  nervous: "'신경질적인' 뜻이 일반적이나 여기서는 '들뜬, 불안정한'.",
  restive: "안절부절 못하는. 참을성 없이 들떠 있는 상태.",
  skittish: "잘 놀라는. 말(馬)의 성질을 묘사할 때 자주 씀. 025와 중복 단어.",
  levity: "경박함. 'levity of character'. 무거운(gravity) 상황에 어울리지 않는 가벼움.",
});

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abase":"창피를 주다",
  "adage":"격언",
  "alert":"방심 않는",
  "aphorism":"금언, 격언",
  "apophthegm":"격언",
  "apothegm":"격언",
  "belittle":"얕잡다, 하찮게 보다",
  "border":"테두리",
  "bound":"(안쪽에서 본) 경계(선)",
  "boundary":"경계(선)",
  "brash":"경솔한, 분별없는",
  "brim":"(컵 등의) 가장자리",
  "brink":"(벼랑 따위의) 가장자리",
  "coda":"악곡의 종결부",
  "conjugal":"결혼의, 배우자의",
  "connubial":"결혼의, 부부의",
  "contemn":"모욕하다",
  "contemptible":"비열한",
  "contemptuous":"경멸적인",
  "debase":"(인품·품위·가치 따위를) 떨어뜨리다",
  "degrade":"지위를 낮추다, 타락시키다",
  "denouement":"연극의 대단원",
  "deprecate":"(강력히) 반대하다, 비난하다",
  "despicable":"경멸할 만한",
  "despise":"경멸하다",
  "dictum":"(권위자, 전문가의) 공식 견해",
  "disdain":"업신여기다; 업신여김",
  "disdainful":"업신여기는",
  "disparage":"폄하하다",
  "edge":"끝머리",
  "envoy":"시, 산문, 연극의 종결부",
  "epigram":"경구, 짧은 풍자시",
  "epilogue":"발문, 산문의 종결부",
  "explicit":"(진술 따위가) 뚜렷한; (소설 등의) 대미",
  "finale":"악곡의 마지막 악장, 연극의 마지막 장",
  "flippant":"경솔한",
  "fringe":"(스카프, 숄 따위의) 술 장식",
  "frivolous":"보잘것없는; 경솔한",
  "giddy":"경솔한, 들뜬",
  "gnome":"격언",
  "headlong":"성급한, 매우 서두는",
  "heady":"무모한",
  "humble":"(신분 등이) 천한; 겸손한; 굴욕을 주다",
  "humbleness":"겸손함; 하찮음",
  "humility":"겸손",
  "idle":"빈둥거리다, 태만한",
  "ignoble":"비열한",
  "ignominious":"수치스러운",
  "impetuous":"성급한, 충동적인",
  "imprudent":"경솔한",
  "impulsive":"충동적인",
  "indolent":"나태한",
  "levity":"경박함, 촐싹거림",
  "margin":"가장자리",
  "marital":"남편의, 혼인의",
  "matrimonial":"결혼의",
  "maxim":"격언",
  "minimize":"경시하다, 얕보다",
  "modesty":"겸손",
  "nervous":"흥분하기 쉬운; 신경질적인",
  "nuptial":"결혼(식)의",
  "outrance":"싸움의 끝",
  "peroration":"연설의 종결부",
  "precept":"교훈, 격언; 영장",
  "precipitant":"경솔한, 덤벙이는",
  "precipitate":"경솔한; 재촉하다",
  "precipitous":"경솔한, 무모한",
  "rash":"경솔한, 성급한, 분별없는",
  "restive":"(불만, 따분함 등으로) 가만있지 못하는",
  "revulsion":"(감정의 격변) 혐오; 불쾌",
  "rim":"(특히 원형물의) 가장자리",
  "scorn":"경멸하다",
  "scornful":"경멸하는",
  "scurvy":"상스러운; 괴혈병",
  "skittish":"들뜬; 겁 많은",
  "slothful":"굼뜬",
  "slouch":"구부정하니 서다",
  "sloven":"꾀죄죄한 사람",
  "slovenly":"(옷차림이) 단정치 못한",
  "sluggard":"게으름쟁이",
  "sluggish":"게으른, 나태한",
  "underestimate":"과소평가하다",
  "underrate":"과소평가하다",
  "understate":"(수 따위를) 적게 말하다",
  "upheaval":"(사회 등의) 대격변",
  "upshot":"(최후의) 결과, 일의 결말",
  "verge":"가장자리",
  "vicissitude":"변화",
  "vigilant":"자지 않고 지키는",
  "wary":"주의 깊은, 경계하는",
  "watchful":"주의하는",
  "witticism":"재치 있는 말",
});
