// LOGIC TREE V502 — Categories 141-200 (manually verified)
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.categories.push(
  {id:"141",words:["feculent", "filthy", "mangy", "mucky", "nasty", "sordid", "squalid", "humble", "ignoble", "ignominious", "vile"]},
  {id:"142",words:["immaculate", "innocent", "sterilized", "sterile", "unblemished", "unspotted", "unsullied", "untarnished"]},
  {id:"143",words:["adulterated", "contaminated"]},
  {id:"144",words:["smirch", "besmirch", "bedraggle", "daub", "defile", "denigrate", "distain", "imbrue", "muck", "smear", "sully", "vitiate", "asperse", "calumniate", "carp", "cavil", "defame", "dent", "derogate", "inveigh", "libel", "malign", "rail", "reprobate", "revile", "slander", "traduce", "vilify"]},
  {id:"145",words:["ephemeral", "evanescent", "fleeting", "frail", "fugacious", "fugitive", "momentary", "transient", "transitory", "vanishing"]},
  {id:"146",words:["boulder", "cobble", "gravel", "pebble", "lapidary", "lapidify", "petrify", "petroglyph", "petrography", "petrology"]},
  {id:"147",words:["commensurate", "equivalent", "tantamount"]},
  {id:"148",words:["accede", "assent", "concede", "concord", "concur", "consent"]},
  {id:"149",words:["awesome", "conspicuous", "enormous", "notable", "noticeable", "pronounced", "redoubtable", "remarkable", "salient", "stupendous"]},
  {id:"150",words:["convolute", "hem", "wind"]},
  {id:"151",words:["bare", "bespeak", "betray", "blunder", "blab", "bolt", "blurt", "bruit", "debunk", "disclose", "divulge", "reveal", "snitch", "squeal", "tattle", "dig", "disinter", "exhume", "unbury", "unearth", "adduce", "evince", "exemplify"]},
  {id:"152",words:["fretful", "nervous", "restive", "restless", "skittish"]},
  {id:"153",words:["club", "flail", "flog", "lash", "trounce", "welt", "whip"]},
  {id:"154",words:["shove", "jostle", "elbow", "push"]},
  {id:"155",words:["windfall", "serendipity", "fluke", "jackpot"]},
  {id:"156",words:["desiccated", "dehydrated", "parched", "scorched", "sear", "sere"]},
  {id:"157",words:["wizardry", "legerdemain", "prestidigitation", "jugglery", "thaumaturgy"]},
  {id:"158",words:["juggler", "prestidigitator", "thaumaturgist", "thaumaturge", "wizard"]},
  {id:"159",words:["bravado", "overboldness", "presumption", "rashness", "recklessness", "temerity"]},
  {id:"160",words:["glut", "gorge", "gratify", "humor", "satisfy", "slake"]},
  {id:"161",words:["impalpable", "intangible", "untouchable", "imperceptible", "unappreciable"]},
  {id:"162",words:["palpable", "tangible", "touchable", "perceptible", "appreciable"]},
  {id:"163",words:["acronym", "pleonasm", "oxymoron", "gaffe", "malapropism", "neologism", "archaism", "solecism", "periphrasis", "circumlocution", "euphemism", "hypocorism", "roundabout expression", "bouquet", "flattery", "blandishment", "hyperbole", "bombast", "grandiloquence", "pomposity", "fustian", "harangue", "tirade", "screed", "panegyric", "encomium", "eulogy", "tribute", "compliment", "plaudit", "laudation", "obloquy", "opprobrium", "invective", "diatribe", "vituperation", "traducement", "billingsgate", "parlance", "phraseology", "equivoke", "pun", "technicality", "terminology"]},
  {id:"164",words:["desiccate", "dehydrate", "parch", "sear", "scorch"]},
  {id:"165",words:["annihilate", "carnage", "decimate", "demolish", "eradicate", "exterminate", "extirpate", "holocaust", "massacre", "sterilize"]},
  {id:"166",words:["hobble", "stutter", "stammer", "stumble"]},
  {id:"167",words:["babble", "gabble", "gibber", "jabber", "patter", "rattle"]},
  {id:"168",words:["equivocate", "prevaricate", "hedge", "palter", "quibble", "shuffle", "tergiversate", "waffle"]},
  {id:"169",words:["babble", "falter", "mumble", "murmur", "mutter", "drone", "chant", "prattle", "stammer", "stumble", "stutter"]},
  {id:"170",words:["amphigory", "babble", "balderdash", "blather", "drivel", "folderole", "fudge", "piffle", "prate", "prattle", "rigmarole", "trumpery", "twaddle"]},
  {id:"171",words:["babble", "blabber", "blather", "chatter", "drivel", "piffle", "prate", "prattle", "rattle", "twaddle"]},
  {id:"172",words:["chatty", "diffuse", "garrulous", "long-winded", "loquacious", "prolix", "redundant", "talkative", "verbose", "voluble", "wordy"]},
  {id:"173",words:["guarded", "reserved", "restrained", "smoldered", "standoffish", "stifled", "uncommunicative"]},
  {id:"174",words:["calm", "mum", "mute", "reserved", "reticent", "taciturn", "uncommunicative"]},
  {id:"175",words:["flavor", "gusto", "relish", "savor", "smack", "taste", "zest"]},
  {id:"176",words:["affable", "genial", "congenial", "bland", "gentle", "lenient", "mild", "suave"]},
  {id:"177",words:["insipid", "tasteless", "unpalatable", "unsavory", "vapid"]},
  {id:"178",words:["ambrosial", "delectable", "delicious", "mellifluous", "mellow", "palatable", "sapid", "tasteful"]},
  {id:"179",words:["acerb", "acerbic", "acid", "acidulent", "acidulous", "acrimonious", "caustic", "cutting", "edgy", "incisive", "mordant", "piquant", "pungent", "racy", "tangy", "trenchant", "truculent", "vitriolic"]},
  {id:"180",words:["blunder", "falter", "flicker", "hover", "linger", "oscillate", "palter", "resile", "scruple", "stagger", "vacillate", "waver", "irresolute", "indecisive"]},
  {id:"181",words:["abase", "abash", "humble", "humiliate", "mortify"]},
  {id:"182",words:["bribe", "corrupt", "lubricate", "suborn", "tamper", "corruptible", "mercenary", "venal"]},
  {id:"183",words:["absorb", "allure", "attract", "captivate", "douse", "enchant", "engage", "engross", "enrapture", "enthrall", "entrance", "fetch", "immerse", "inebriate", "infatuate", "intoxicate", "mesmerize", "preoccupy", "prepossess", "ravish", "rivet", "smite", "steep", "strike", "transfix", "transport"]},
  {id:"184",words:["abdicate", "abjure", "abnegate", "abolish", "abrogate", "desist", "disclaim", "relinquish", "renounce", "repudiate", "waive"]},
  {id:"185",words:["bite", "chew", "chomp", "crunch", "munch", "gnaw", "gobble", "gorge", "gulp", "guzzle", "swill", "nibble", "quaff", "raven", "sip", "slurp", "swallow"]},
  {id:"186",words:["defunct", "extinct"]},
  {id:"187",words:["inventory", "manifest", "necrology", "roll", "roster", "rota", "slate"]},
  {id:"188",words:["behest", "decree", "edict", "fiat", "injunction", "mandate", "ordain"]},
  {id:"189",words:["acute", "agile", "argute", "astute", "brilliant", "canny", "keen", "longheaded", "perspicacious", "sagacious", "sapient", "shrewd", "smart"]},
  {id:"190",words:["cogitate", "contemplate", "meditate", "muse", "opine", "ponder", "pore", "ruminate", "speculate"]},
  {id:"191",words:["demonstrative", "effusive", "explicit", "forthright", "outspoken"]},
  {id:"192",words:["affront", "disgrace", "dishonor", "indignity"]},
  {id:"193",words:["derogative", "derogatory", "pejorative"]},
  {id:"194",words:["defame", "defile", "denigrate", "derogate", "smear", "smirch", "besmirch", "muck", "vilify", "vitiate", "sully", "compromise", "becloud", "grime", "begrime", "asperse", "calumniate", "defame", "derogate", "inveigh", "libel", "malign", "rail", "reprobate", "revile", "slander", "traduce", "vilify", "vituperate"]},
  {id:"195",words:["agnomen", "alias", "appellation", "cognomen", "denomination", "diminutive", "hypocorism", "epithet", "incognito", "misnomer", "moniker", "nomenclature", "pseudonym", "sobriquet", "vernacular"]},
  {id:"196",words:["accumulate", "amass", "garner", "hoard"]},
  {id:"197",words:["ambiguous", "equivocal", "hazy", "murky", "nebulous", "obscure", "opaque", "turbid", "vague"]},
  {id:"198",words:["raucous", "hoarse", "gruff"]},
  {id:"199",words:["confiscate", "expropriate", "impress", "levy", "sequester", "sequestrate", "commandeer", "exact"]},
  {id:"200",words:["apathetic", "impassive", "indifferent", "phlegmatic", "stolid", "blase", "insensate", "lackadaisical", "languid", "lazy", "lethargic", "listless", "nonchalant", "sluggish"]},
);
Object.assign(window.__V502_EXT__.categorySummaries,{
  "141":"\ub354\ub7ec\uc6b4, \ube44\ucc9c\ud55c",
  "142":"\ub354\ub7fd\ud600\uc9c0\uc9c0 \uc54a\uc740",
  "143":"\ub354\ub7fd\ud600\uc9c4",
  "144":"\ub354\ub7fd\ud788\ub2e4, \uba85\uc608\ub97c \uc190\uc0c1\uc2dc\ud0a4\ub2e4",
  "145":"\ub367\uc5c6\ub294, \uc77c\uc2dc\uc801\uc778",
  "146":"\ub3cc",
  "147":"\ub3d9\ub4f1\ud55c, \uac19\uc740 \ud06c\uae30\uc758",
  "148":"\ub3d9\uc758\ud558\ub2e4",
  "149":"\ub450\ub4dc\ub7ec\uc9c4, \ub208\uc5d0 \ub744\ub294",
  "150":"\ub458\ub458 \ub9d0\ub2e4",
  "151":"\ub4dc\ub7ec\ub0b4\ub2e4, \ubc1d\ud600\ub0b4\ub2e4, \ud3ed\ub85c\ud558\ub2e4",
  "152":"\ub4e4\ub72c, \ucc28\ubd84\ud558\uc9c0 \ubabb\ud55c",
  "153":"\ub54c\ub9ac\ub2e4",
  "154":"\ub5a0\ubc00\ub2e4",
  "155":"\ub73b\ubc16\uc758 \ud589\uc6b4",
  "156":"\ub9c8\ub978, \ubb3c\uae30\uac00 \uc5c6\ub294",
  "157":"\ub9c8\ubc95, \ub9c8\uc220",
  "158":"\ub9c8\ubc95\uc0ac, \ub9c8\uc220\uc0ac",
  "159":"\ub9cc\uc6a9",
  "160":"\ub9cc\uc871\uc2dc\ud0a4\ub2e4",
  "161":"\ub9cc\uc9c8 \uc218 \uc5c6\ub294, \uc2e4\uccb4\uac00 \uc5c6\ub294",
  "162":"\ub9cc\uc9c8 \uc218 \uc788\ub294, \uc778\uc9c0\ud560 \uc218 \uc788\ub294",
  "163":"\ub9d0, \uc5b4\ubc95",
  "164":"\ub9d0\ub9ac\ub2e4, \ubc14\uc2f9 \ub9c8\ub974\uac8c \ud558\ub2e4",
  "165":"\ub9d0\uc0b4\ud558\ub2e4, \ubc15\uba78\ud558\ub2e4",
  "166":"\ub9d0\uc744 \ub354\ub4ec\ub2e4",
  "167":"\ub9d0\uc744 \uc54c\uc544\ub4e3\uc9c0 \ubabb\ud558\ub3c4\ub85d \ube60\ub974\uac8c \uc7ac\uc798\ub300\ub2e4",
  "168":"\ub9d0\uc744 \uc5bc\ubc84\ubb34\ub9ac\ub2e4, \ubaa8\ud638\ud558\uac8c \ub9d0\ud558\ub2e4, \ud551\uacc4\ub97c \ub300\ub2e4",
  "169":"\ub9d0\uc744 \ubd88\ubd84\uba85\ud558\uac8c \uc911\uc5bc\uac70\ub9ac\ub2e4",
  "170":"(\uc4f8\ub370\uc5c6\ub294/\uc758\ubbf8 \uc5c6\ub294) \ub9d0",
  "171":"(\uc4f8\ub370\uc5c6\ub294/\uc758\ubbf8 \uc5c6\ub294) \ub9d0\uc744 \ub298\uc5b4\ub193\ub2e4",
  "172":"\ub9d0\uc774 \ub9ce\uc740, \uc7a5\ud669\ud55c",
  "173":"\ub9d0(\ud589\ub3d9)\uc774 \uc2e0\uc911\ud55c, \uac10\uc815\uc744 \ub4dc\ub7ec\ub0b4\uc9c0 \uc54a\ub294",
  "174":"\ub9d0\uc774 \uc5c6\ub294, \uacfc\ubb35\ud55c",
  "175":"\ub9db, \ud48d\ubbf8, \uc7ac\ubbf8",
  "176":"\ub9db\uc774 \uc21c\ud55c",
  "177":"\ub9db\uc774 \uc5c6\ub294",
  "178":"\ub9db\uc774 \uc788\ub294",
  "179":"(\ub9db, \ud0dc\ub3c4, \uc5b8\ud589\uc774) \uc2e0\ub784\ud55c, \ud1b5\ub82c\ud55c, \uc790\uadf9\uc801\uc778",
  "180":"\ub9dd\uc124\uc774\ub2e4, \uc8fc\uc800\ud558\ub2e4",
  "181":"\ub9dd\uc2e0\uc744 \uc8fc\ub2e4",
  "182":"\ub9e4\uc218\ud558\ub2e4, \ud0c0\ub77d\uc2dc\ud0a4\ub2e4",
  "183":"\ub9e4\ud639\uc2dc\ud0a4\ub2e4, \ub10b\uc744 \ube7c\uc557\ub2e4, \ubab0\ub450\ud558\uac8c \ud558\ub2e4",
  "184":"(\uc2b5\uad00, \uad8c\ub9ac, \uc758\ubb34 \ub4f1\uc744) \ub9f9\uc138\ucf54 \ub04a\ub2e4",
  "185":"\uba39\uace0 \ub9c8\uc2dc\ub294 \ubaa8\uc591",
  "186":"\uba78\uc885\ud55c",
  "187":"\uba85\ub2e8, \uba85\ubd80",
  "188":"\uba85\ub839, \uc5c4\uba85",
  "189":"\uba85\ubbfc\ud55c, \ucd1d\uba85\ud55c",
  "190":"\uba85\uc0c1\ud558\ub2e4, \uc219\uace0\ud558\ub2e4",
  "191":"\uba85\uc2dc\uc801\uc778, \ud130\ub193\uace0 \ub9d0\ud558\ub294",
  "192":"\uba85\uc608\uc190\uc0c1, \ubd88\uba85\uc608",
  "193":"\uba85\uc608\ub97c \uc190\uc0c1\uc2dc\ud0a4\ub294, \ubd88\uba85\uc608\uc2a4\ub7ec\uc6b4",
  "194":"\uba85\uc608\ub97c \uc190\uc0c1\uc2dc\ud0a4\ub2e4, \uac00\uce58\ub97c \ub5a8\uc5b4\ub728\ub9ac\ub2e4",
  "195":"\uba85\uce6d, \ubcc4\uba85, \uac00\uba85",
  "196":"\ubaa8\uc544\ub450\ub2e4, \uc313\uc544\ub450\ub2e4",
  "197":"\ubaa8\ud638\ud55c",
  "198":"\ubaa9\uc774 \uc270",
  "199":"\ubab0\uc218(\uc555\uc218)\ud558\ub2e4, \uc9d5\uc218\ud558\ub2e4",
  "200":"\ubb34\uad00\uc2ec\ud55c, \ub0c9\ub2f4\ud55c, \ubb34\uac10\ub3d9\ud55c",
});

Object.assign(window.__V502_EXT__.confusionNotes,{
  "adulterated":"adulterate(불순물을 섞다)+ed. 품질을 떨어뜨린.",
  "asperse":"as(쪽으로)+sperse(뿌리다). 물을 뿌리듯 험담하다.",
  "bedraggle":"be+ draggle(질질 끌다). 진흙탕에 질질 끌어 더럽히다.",
  "besmirch":"be(강하게)+smirch. (명예·인격을) 심하게 손상시키다.",
  "calumniate":"calumny(중상모략)의 동사. 거짓으로 헐뜯다.",
  "carp":"트집 잡다, 투덜거리다. 잉어(carp)와 동철자.",
  "cavil":"사소한 일에 트집 잡다. 하찮은 불평.",
  "contaminated":"접촉하여 더럽혀진. 오염된. 환경·식품 오염에 자주 씀.",
  "daub":"(페인트·진흙 등을) 바르다, 더럽히다. 조잡하게 칠하다.",
  "defame":"de(아래로)+fame(명성). 명예를 훼손하다. 'defamation(명예훼손)'.",
  "defile":"de(완전히)+file(더럽히다). (신성을) 모독하다, 더럽히다.",
  "denigrate":"de(완전히)+nigr(검다)+ate. (인격·명예를) 검게 하다, 훼손하다.",
  "dent":"(명성에) 흠을 내다. 찌그러뜨리다의 비유적 용법.",
  "derogate":"de(떨어져)+rogate(묻다). 가치를 떨어뜨리다, 훼손하다.",
  "distain":"dis(제거)+stain(얼룩). 명예를 손상시키다; 변색시키다.",
  "ephemeral":"ep(위에)+hemer(하루)+al. 하루살이 같은. 덧없는, 순간적인.",
  "evanescent":"e(밖으로)+van(사라지다)+escent. 김처럼 사라지는.",
  "feculent":"탁하고 더러운. fecul(찌꺼기)+ent. 액체의 혼탁함.",
  "filthy":"filth(오물)+y. 불결한. 가장 강한 더러움 표현.",
  "fleeting":"fleet(빠르게 지나가다)+ing. 쏜살같은, 덧없는.",
  "frail":"부서지기 쉬운, 덧없는. 노인의 쇠약함에도 씀.",
  "fugacious":"fug(달아나다)+acious. 덧없는, 변하기 쉬운. 희귀어.",
  "fugitive":"fug(달아나다)+itive. 일시적인; 탈주하는.",
  "humble":"겸손한(긍정), 천한(부정). 문맥으로 구분. 'humble origins(미천한 출신)'.",
  "ignoble":"ig(아닌)+noble(고귀한). 비열한, 고귀하지 못한.",
  "ignominious":"ig+ nomin(이름)+ious. 수치스러운. 공개적 망신.",
  "imbrue":"(손·칼을 피로) 물들이다, 더럽히다. 폭력적 느낌.",
  "immaculate":"im(아닌)+maculate(얼룩진). 흠 없는, 순결한. 종교적 순결.",
  "innocent":"해롭지 않은, 순결한. 결백한, 무죄의(법률).",
  "inveigh":"in(안으로)+veigh(나르다). 통렬히 비난하다. 'inveigh against'.",
  "libel":"(문서로) 명예를 훼손하다. 인쇄물에 의한 명예훼손(slander는 구두).",
  "malign":"악의적으로 비방하다. 형용사로 '해로운(malignant)' 뜻도.",
  "mangy":"mange(옴)+y. 옴이 오른, 불결한. 동물·사람에 씀.",
  "momentary":"moment(순간)+ary. 순간의, 잠깐의.",
  "muck":"오물로 더럽히다; 망쳐놓다. 'muck up(망치다)'.",
  "mucky":"muck(오물)+y. (수단이) 비열한. 진흙투성이의 뜻도.",
  "nasty":"몹시 불결하고 불쾌한. 태도·냄새·맛 모두에 씀.",
  "rail":"욕을 퍼붓다, 악담하다. 'rail against/at' 구문.",
  "reprobate":"비난하다; 타락한 사람. 신에게 버림받은(종교적).",
  "revile":"re(강하게)+vile(비열한). 매도하다, 심하게 욕하다.",
  "slander":"구두로 중상모략하다. libel(문서 명예훼손)과 구분.",
  "smear":"(기름 따위를) 바르다, 더럽히다. 비방(smear campaign) 뜻도.",
  "smirch":"더럽히다; (명예)를 손상하다. 작은 얼룩에서 비유적 오점으로.",
  "sordid":"지저분하고 심보가 더러운. 도덕적 타락을 암시.",
  "squalid":"더럽고 누추한. 주거 환경의 참혹함에 자주 씀.",
  "sterile":"살균한; 불모의. 생명체가 살 수 없는. 창의성 없는(비유).",
  "sterilized":"살균한. 세균을 완전히 제거한. 불임 수술 뜻도.",
  "sully":"(명예 따위를) 훼손하다. 깨끗한 것을 더럽히다.",
  "traduce":"tra(가로질러)+duce(이끌다). 비방하다, 헐뜯다.",
  "transient":"trans(건너)+ient(가는). 일시적인; 지나가는. 무상함.",
  "unblemished":"blemish(흠)가 없는. 완벽한 평판·피부.",
  "unspotted":"오점이 없는. 도덕적으로 깨끗한. 'spotless'의 격식어.",
  "unsullied":"sully(더럽히다)되지 않은. 순수성이 보존된.",
  "untarnished":"tarnish(변색)되지 않은. 명예가 손상되지 않은.",
  "vile":"비열하고 혐오스러운. 도덕적으로 극도로 타락한.",
  "vilify":"vile(비열한)+fy(만들다). 비난하다, 깎아내리다.",
  "vitiate":"vit(결함)+ate. 가치·효력을 떨어뜨리다, 손상시키다.",
});

// Additional confusion notes
Object.assign(window.__V502_EXT__.confusionNotes,{
  "accede":"ac(쪽으로)+cede(가다). (요구 등에) 동의하다. 왕위에 오르다 뜻도.",
  "adduce":"ad(쪽으로)+duce(이끌다). 증거·이유를 제시하다. 법정 용어.",
  "assent":"as(쪽으로)+sent(느끼다). 찬성하다. 공식적 동의.",
  "bare":"(비밀·마음 등을) 털어놓다. 드러내다. 벌거벗은 뜻과 연결.",
  "bespeak":"be+speak. -을 나타내다, 보이다. 'His actions bespeak confidence.'",
  "betray":"(감정·비밀을) 무심코 드러내다. 배신하다 뜻과 구분.",
  "blab":"무심코 비밀을 누설하다. 수다스럽게 말하다.",
  "boulder":"커다란 반석. 사람 키보다 큰 바위.",
  "bruit":"bru(소리)+it. 소문을 널리 퍼뜨리다. 'bruited about'.",
  "cobble":"자갈, 조약돌. cobblestone(조약돌 포장도로).",
  "commensurate":"com(함께)+mensur(측정)+ate. 같은 크기의, 비례하는.",
  "concede":"con(함께)+cede(가다). 인정하다; 양보하다. 마지못해 동의.",
  "concord":"con(함께)+cord(마음). 마음이 일치함, 화합. concordant(일치하는).",
  "concur":"con(함께)+cur(달리다). 의견 일치를 보다. 'I concur'.",
  "consent":"con(함께)+sent(느끼다). 동의하다. 'informed consent(사전 동의)'.",
  "conspicuous":"con(완전히)+spic(보다)+uous. 눈에 띄는. 시선을 완전히 끄는.",
  "convolute":"con(함께)+volute(말다). 둘둘 감다. convoluted(뒤얽힌, 복잡한).",
  "debunk":"de(제거)+bunk(허튼소리). 정체를 폭로하다, 가짜임을 밝히다.",
  "disclose":"dis(반대)+close(닫다). 닫힌 것을 열다, 폭로하다.",
  "divulge":"di(떨어져)+vulge(대중). 대중에게 알리다, 누설하다.",
  "elbow":"팔꿈치로 밀다. 'elbow one's way through(밀치고 나아가다)'.",
  "equivalent":"equi(같은)+val(가치)+ent. 동등한 가치의.",
  "evince":"e(밖으로)+vince(이기다). 감정 등을 분명히 나타내다.",
  "exemplify":"example(예시)+ify. 예증하다, 예를 들어 설명하다.",
  "exhume":"ex(밖으로)+hume(땅). 땅에서 파내다. 발굴하다.",
  "flail":"도리깨질하다; 연속으로 때리다. 팔·다리를 마구 휘두르다.",
  "flog":"매질하다, 채찍질하다. 가혹한 체벌. 'flog a dead horse(헛수고)'.",
  "fluke":"요행. 우연한 성공. 'a fluke goal(운 좋은 골)'.",
  "fretful":"fret(초조해하다)+ful. 초조하고 안절부절 못하는.",
  "gravel":"자갈더미. 도로·공사장의 쇄석.",
  "hem":"(사람·물건을) 에워싸다. 옷단(hem) 뜻도.",
  "jackpot":"(복권의) 1등 당첨금; 대성공. 'hit the jackpot(대박 나다)'.",
  "jostle":"(난폭하게) 떠밀다. 붐비는 곳에서 어깨로 밀치다.",
  "lash":"채찍질하다; 몹시 꾸짖다. 속눈썹(eyelash) 뜻도.",
  "notable":"note(주목하다)+able. 두드러진; 주목할 만한. 저명한 인물(명사).",
  "noticeable":"notice(알아차리다)+able. 이목을 끄는; 현저한.",
  "pebble":"둥근 자갈. 물에 씻겨 매끄러운 작은 돌.",
  "pronounced":"pronounce(선언하다)+ed. 뚜렷한, 현저한. 분명히 드러난.",
  "restive":"rest(쉬다)+ive. 마음이 들뜬, 안정되지 못한. 말이 앞으로 안 가려 할 때.",
  "restless":"rest+less. 쉬지 못하는, 침착하지 못한.",
  "reveal":"re(뒤로)+veal(베일). 베일을 벗기다. 가장 일반적인 '드러내다'.",
  "salient":"sali(뛰어오르다)+ent. 눈에 띄는, 현저한. 'salient point(핵심)'.",
  "serendipity":"우연히 좋은 것을 발견하는 능력. 'serendipitous discovery'.",
  "shove":"밀치다. 거칠게 미는 느낌. push보다 강함.",
  "skittish":"말이 잘 놀라는; 겁 많은; 활발한. 변덕스럽게 움직이는.",
  "snitch":"밀고하다. 학교에서 고자질하다(snitch on).",
  "squeal":"(돼지처럼) 끽 소리 지르다; 밀고하다. 속어.",
  "tantamount":"tant(그만큼)+amount(양). 동등한, 상당하는. 'tantamount to treason'.",
  "tattle":"고자질하다. 어린이 말투. tattletale(고자쟁이).",
  "trounce":"호되게 패주다, 완파하다. 경기에서 압승할 때도 씀.",
  "unearth":"un+earth(땅). 땅에서 꺼내다; (진실을) 밝혀내다.",
  "welt":"(채찍 등으로) 때리다; (피부에 난) 채찍 자국.",
  "wind":"나선상을 이루다, 휘감기다. 시계 태엽을 감다(wind a watch).",
  "windfall":"바람에 떨어진 과일; 뜻밖의 횡재. 예상치 못한 행운.",
});

// Additional notes batch 3
Object.assign(window.__V502_EXT__.confusionNotes,{
  "acerb":"신랄한, 거친. 신맛에서 비유적 태도로 확장.",
  "acrimonious":"acri(날카로운)+monious. 매서운, 신랄한. 특히 말씨름에.",
  "acronym":"acro(끝)+nym(이름). 두문자어. 'NASA, NATO' 등.",
  "ambrosial":"ambrosia(신들의 음식)+al. 아주 맛 좋은. 신성한 맛.",
  "amphigory":"무의미하고 우스운 글. 헛소리 문학 장르.",
  "annihilate":"an(쪽으로)+nihil(무)+ate. 전멸시키다, 완전히 파괴하다.",
  "archaism":"archa(고대의)+ism. 고어. 옛말.",
  "babble":"(아기가) 옹알이하다; 더듬거리며 말하다. 바벨탑(Babel)에서.",
  "balderdash":"허튼소리. 16세기부터 쓰인 말.",
  "blather":"재잘거리다. 계속 의미 없는 말을 하다.",
  "bravado":"겉으로 드러내는 허세. 실제 용기보다 과시에 가까움.",
  "caustic":"caust(태우다)+ic. 부식성의; 신랄한. 'caustic remark(독설)'.",
  "chant":"(단순 반복 곡조를) 부르다, 영창하다.",
  "chatty":"chat(잡담)+y. 수다스러운. 친근한 대화를 좋아하는.",
  "decimate":"decim(10분의 1)+ate. 원래 '10명 중 1명을 죽이다'. 많은 이를 죽이다.",
  "dehydrated":"de(제거)+hydr(물)+ated. 탈수증세를 보이는.",
  "delectable":"delect(즐겁게 하다)+able. 아주 맛있는, 즐거운.",
  "demolish":"de(아래로)+mol(쌓다)+ish. (건물을) 부수다, 철거하다.",
  "desiccate":"de(완전히)+sicc(마른)+ate. 건조시키다. 말리다.",
  "desiccated":"de(완전히)+sicc(마른)+ated. (풍토 등이) 완전히 건조한.",
  "diffuse":"dis(떨어져)+fuse(붓다). 말을 길게 늘어놓는, 산만한.",
  "drivel":"침 흘리다; 쓸데없는 말을 하다. 멍청한 소리.",
  "drone":"단조로운 어조로 말하다. 수벌(drone)의 윙윙거림에서.",
  "equivocate":"equi(같은)+voc(목소리)+ate. 두 가지 뜻으로 모호하게 말하다.",
  "eradicate":"e(밖으로)+radic(뿌리)+ate. 뿌리 뽑다, 박멸하다.",
  "euphemism":"eu(좋은)+phem(말하다)+ism. 완곡어법. 돌려 말하기.",
  "exterminate":"ex(밖으로)+termin(경계)+ate. 경계 밖으로 몰아내다, 몰살시키다.",
  "extirpate":"ex(밖으로)+stirp(뿌리)+ate. 뿌리째 뽑다, 근절시키다.",
  "folderole":"헛소리. 후렴구(fol-de-rol)에서 유래.",
  "fudge":"허튼소리를 하다; 얼버무리다. 퍼지 초콜릿과 무관.",
  "gabble":"빨리 지껄이다. 알아듣기 힘들게 속사포처럼.",
  "gaffe":"실언, 실수. 사회적 상황에서의 부적절한 발언.",
  "garrulous":"garr(수다)+ulous. 끊임없이 수다스러운. 특히 노인에게.",
  "glut":"배불리 먹이다; 실컷 하게 하다. 과잉 공급의 뜻도.",
  "gorge":"포식하다; 가득 채우다. 협곡(gorge) 뜻도.",
  "gratify":"gratus(기쁜)+fy. 기쁘게 하다; 만족시키다.",
  "guarded":"guard(지키다)+ed. 조심성 있는. 말을 아끼는.",
  "holocaust":"holo(전체)+caust(태우다). 전부 태우다; 대학살.",
  "impalpable":"im(아닌)+palp(만지다)+able. 만질 수 없을 정도로 미세한.",
  "insipid":"in(아닌)+sip(맛)+id. 싱거운, 맛없는. 재미없는 뜻도.",
  "intangible":"in(아닌)+tangible(만질 수 있는). 무형의, 실체 없는.",
  "jabber":"(흥분해서) 재잘대다. 새가 지저귀듯.",
  "juggler":"요술쟁이. juggle(저글링하다)에서.",
  "jugglery":"juggler(요술쟁이)+y. 요술, 마술. 속임수.",
  "legerdemain":"프랑스어 '가벼운 손'. 손으로 하는 요술, 눈속임.",
  "long-winded":"long+wind(숨)+ed. 숨이 길게 이어지는. 장광설의.",
  "loquacious":"loqui(말하다)+acious. 말 많은. 지나치게 수다스러운.",
  "malapropism":"Malaprop 부인(연극 캐릭터)에서. 어법상의 실수.",
  "mordant":"mord(물다)+ant. 물어뜯는 듯한. 신랄한, 독설적인.",
  "mumble":"중얼거리다. 입 속으로 웅얼거리는.",
  "murmur":"나직하게 속삭이다. 불평을 중얼거리다. 심장 잡음(murmur).",
  "mutter":"중얼거리다, 투덜거리다. 불만 섞인 작은 소리.",
  "neologism":"neo(새로운)+log(말)+ism. 신조어. '신조어 만들기'.",
  "overboldness":"지나친 대담함. 무모함에 가까운.",
  "oxymoron":"oxy(날카로운)+moron(어리석은). 모순어법. 'deafening silence'.",
  "palpable":"palp(만지다)+able. 만질 수 있는; 명백한. 'palpable tension'.",
  "palter":"모호한 말로 속이다. 말장난으로 얼버무리다.",
  "parch":"바싹 말리다. 갈증 나게 하다. 'parched throat'.",
  "parched":"(날씨가 더워서) 몹시 건조한. 목이 타는 갈증에도 씀.",
  "piffle":"실없는 말을 지껄이다. 시시한 소리.",
  "piquant":"piqu(찌르다)+ant. (맛이) 톡 쏘는 듯한; 흥미를 돋우는.",
  "pleonasm":"pleon(더 많은)+asm. 장황한 표현, 중복어법.",
  "prate":"쓸데없는 소리하다. 끊임없이 지껄이다.",
  "prattle":"(쓸데없이 마구) 지껄이다. 어린아이의 재잘거림.",
  "prestidigitation":"presti(빠른)+digit(손가락)+ation. 빠른 손놀림의 마술.",
  "prestidigitator":"손재주로 마술을 부리는 사람. 'prestidigitation' 참조.",
  "presumption":"주제넘음, 체면 없음. 건방진 추정. 'presumptuous'의 명사.",
  "prevaricate":"pre(앞서)+vari(다양하게)+cate. 속이기 위해 모호하게 말하다.",
  "prolix":"pro(앞으로)+lix(흐르다). 장황한, 지루할 정도로 긴.",
  "pungent":"pung(찌르다)+ent. 코를 찌르는; 날카로운, 신랄한.",
  "quibble":"다른 트집으로 논점을 피하다. 옥신각신하다.",
  "rashness":"성급함, 무분별함. 결과 생각 않고 행동.",
  "recklessness":"reck(신경 쓰다)+less+ness. 무모함, 개의치 않음.",
  "reserved":"re(뒤로)+serv(지키다)+ed. 말없는, 내성적인. 감정을 드러내지 않는.",
  "reticent":"re(뒤로)+tic(조용한)+ent. 말을 삼가는, 과묵한.",
  "rigmarole":"횡설수설; 복잡하고 긴 절차. 'ragman roll(긴 문서)'에서.",
  "sapid":"sap(맛)+id. 강한 풍미가 있는. insipid의 반대.",
  "scorched":"scorch(그을리다)+ed. 탄, 그을은.",
  "sear":"(강한 불에 겉을) 그슬다, 태우다. 'searing pain(타는 듯한 고통)'.",
  "sere":"시든, 마른. 식물이 말라 비틀어진. sear의 변형.",
  "shuffle":"모호한 태도로 난처함을 피하다. 발을 질질 끌다 뜻도.",
  "slake":"(갈증·욕망을) 해소하다, 채우다. 'slake one's thirst'.",
  "solecism":"Soloi(아테네 식민지)에서. 어법상의 오류.",
  "stammer":"말을 더듬다. 주로 긴장해서. stutter보다 넓은 의미.",
  "sterilize":"sterile(불모의)+ize. 불임케 하다; 살균하다.",
  "stumble":"(말하다가) 더듬거리다. 발이 걸려 넘어지다 뜻도.",
  "stutter":"말을 더듬다. 's-s-stutter'처럼 첫소리 반복.",
  "taciturn":"tacit(무언의)+urn. 과묵한, 말수가 적은.",
  "tangible":"tang(만지다)+ible. 만져서 알 수 있는; 실체적인.",
  "temerity":"지나친 대담함, 만용. 무례할 정도의 용기.",
  "tergiversate":"tergum(등)+versate(돌리다). 등을 돌리다; 변절하다. 말을 얼버무리다.",
  "thaumaturgist":"기적을 행하는 마술사. thaumaturgy를 행하는 사람.",
  "thaumaturgy":"thauma(기적)+turgy(일으키다). 기적을 행하는 마술.",
  "trenchant":"trench(자르다)+ant. (말이) 예리하게 파고드는, 통렬한.",
  "twaddle":"실없는 소리하다. 멍청한 말.",
  "vapid":"vap(증기)+id. 김 빠진 맥주처럼 맛없는. 생기 없는.",
  "verbose":"verb(단어)+ose(가득한). 말이 많은. 군더더기가 많은.",
  "vitriolic":"vitriol(황산)+ic. 황산처럼 독한. 언어가 극도로 신랄한.",
  "voluble":"volu(돌다)+ble. 말이 술술 나오는, 유창한.",
  "wizard":"마법사. 해리포터의 wizard. expert(달인) 뜻도.",
  "wizardry":"wizard(마법사)+ry. 신기, 묘기. 뛰어난 기술.",
});

// Final batch for 141-200
Object.assign(window.__V502_EXT__.confusionNotes,{
  "abase":"a(쪽으로)+base(낮은). (자기를) 낮추다, 창피를 주다.",
  "abash":"a(쪽으로)+bash(당황). 부끄럽게 하다, 당황시키다.",
  "absorb":"ab(떨어져)+sorb(빨아들이다). 마음을 완전히 빼앗다.",
  "affront":"af(쪽으로)+front(이마). 정면으로 맞서 모욕하다.",
  "agnomen":"ad(추가)+nomen(이름). 추가된 별명.",
  "alias":"alius(다른). 가명. 'John Smith, alias James Bond'.",
  "allure":"al(쪽으로)+lure(유혹하다). 마음을 끌다, 매혹하다.",
  "amass":"a(쪽으로)+mass(덩어리). (긁어) 모으다. 대량 축적.",
  "ambiguous":"ambi(양쪽)+igu(이끌다)+ous. 두 가지로 해석되는, 애매한.",
  "apathetic":"a(없는)+path(감정)+etic. 무관심한, 냉담한.",
  "behest":"be+hest(명령). 명령, 지시. 'at the behest of(~의 명령으로)'.",
  "bribe":"뇌물을 주다, 매수하다. 가장 일반적인 '매수'.",
  "callous":"call(굳은살)+ous. 굳은살이 박인; 무감각한, 냉담한.",
  "captivate":"capt(잡다)+ivate. 마음을 사로잡다.",
  "cogitate":"cogit(생각하다)+ate. 숙고하다, 깊이 생각하다.",
  "cognomen":"co(함께)+nomen(이름). 가문 이름, 별명.",
  "confiscate":"con(함께)+fisc(국고)+ate. 몰수하다, 국가가 압수하다.",
  "contemplate":"con(함께)+templ(관찰하다)+ate. 심사숙고하다. 응시하다.",
  "corrupt":"cor(완전히)+rupt(부수다). 부패시키다, 타락시키다.",
  "decree":"de(아래로)+cree(구분하다). 법령, 포고. 왕이나 정부의 결정.",
  "defunct":"de(아래로)+funct(기능하다). 기능을 멈춘, 죽은. 'defunct company'.",
  "edict":"e(밖으로)+dict(말하다). (옛날의) 칙령; 포고.",
  "engross":"en(안으로)+gross(큰). 마음을 완전히 차지하다.",
  "enrapture":"en+rapture(황홀). 황홀케 하다.",
  "enthrall":"en+thrall(노예). 마음을 사로잡아 노예로 만들다.",
  "epithet":"epi(위에)+thet(놓다). 별명, 통칭. 경멸적 형용사구로도 씀.",
  "equivocal":"equi(같은)+voc(목소리)+al. 같은 목소리로 다른 뜻. 모호한.",
  "extinct":"ex(밖으로)+tinct(끄다). 불이 꺼진; 멸종한.",
  "fiat":"fiat(그것이 되라). 권위에 의한 명령. 라틴어 'let it be done'.",
  "forthright":"forth(앞으로)+right(옳은). 솔직하고 직설적인.",
  "garner":"곡창; (지혜·사상 따위의) 축적. 수확하다의 비유.",
  "gobble":"칠면조 울음소리에서. 게걸스럽게 먹다.",
  "gruff":"(소리·목소리가) 굵고 탁한, 퉁명스러운.",
  "guzzle":"벌컥벌컥 마시다, 폭음하다. 액체를 급히 들이키다.",
  "hoard":"축적하다, 저장하다. 특히 비밀리에 모으다. 부정적 뉘앙스.",
  "hoarse":"쉰 목소리의. 감기로 목이 잠긴.",
  "humiliate":"hum(땅)+iliate. 땅에 꿇리다. 창피를 주다.",
  "ignominy":"ig(아닌)+nomin(이름)+y. 불명예, 수치. 이름을 더럽히다.",
  "indecisive":"in(아닌)+decisive(결정적인). 결단성이 없는.",
  "injunction":"in(안으로)+junct(잇다)+ion. (법원의) 금지 명령.",
  "inventory":"invent(찾다)+ory. 상품 재고 목록.",
  "irresolute":"ir(아닌)+resolute(결단력 있는). 우유부단한.",
  "lethargic":"leth(망각)+argic. 무기력한, 나른한. Lethe(망각의 강)에서.",
  "lubricate":"lubric(미끄러운)+ate. 윤활유를 치다; 뇌물로 매끄럽게 하다.",
  "mandate":"mand(명령하다)+ate. (공식) 명령; 위임. 'mandate to govern'.",
  "manifest":"mani(손)+fest(치다). 적하목록. '명백한' 뜻도.",
  "meditate":"medit(숙고하다)+ate. 명상하다, 숙려하다.",
  "mesmerize":"Mesmer(최면술사)에서. 홀리게 하다, 최면 걸다.",
  "mortify":"mort(죽음)+ify. 죽을 만큼 창피하게 하다. 굴욕감.",
  "muse":"뮤즈(예술의 여신)에게 영감을 구하다. 깊이 생각하다.",
  "nebulous":"nebul(구름)+ous. 구름처럼 흐릿한, 애매한.",
  "necrology":"necro(죽은)+logy(기록). 사망자 명부, 사망 기사.",
  "nibble":"조금씩 야금야금 먹다. 작게 베어 먹기.",
  "nonchalant":"non+chal(열)+ant. 열의 없는, 무심한. 쿨한 태도.",
  "opaque":"opaq(그늘진). 불투명한. 이해하기 어려운.",
  "ordain":"or(입)+dain(말하다). (법률·운명이) 규정하다. 성직자 임명.",
  "outspoken":"out+spoken. 거리낌 없는, 숨김없이 말하는.",
  "pejorative":"pejor(더 나쁜)+ative. 경멸적인, 가치를 떨어뜨리는.",
  "phlegmatic":"phlegm(점액)+atic. 점액질의; 냉담하고 둔감한. 4체질설에서.",
  "pseudonym":"pseudo(가짜)+nym(이름). 필명, 가명. 익명과 다름.",
  "quaff":"단숨에 들이키다. 시원하게 마시는 느낌.",
  "raucous":"목이 쉰, 쉰 목소리의. 시끄럽고 소란한.",
  "raven":"폭식하다, 게걸스럽게 먹다. 까마귀(raven)와 동철자.",
  "ravish":"rav(잡아채다)+ish. 황홀하게 하다. 강간하다 뜻도.",
  "rivet":"rivet(대갈못). 고정시키다; (시선·관심을) 사로잡다.",
  "roster":"근무 당번표. 'duty roster(당직표)'.",
  "rota":"당번 명부. 영국 영어에서 자주 씀.",
  "ruminate":"rumin(되새김질)+ate. 반추 동물처럼 곱씹어 생각하다.",
  "sequester":"se(떨어져)+quest(구하다). 격리하다; (재산을) 가압류하다.",
  "sip":"조금씩 홀짝홀짝 마시다. 차·커피를 음미하며 마시기.",
  "slurp":"소리 내어 먹다(마시다). 국수를 후루룩.",
  "smear":"(기름을) 바르다; (명예를) 더럽히다. 'smear campaign(비방 운동)'.",
  "sobriquet":"프랑스어. 별명, 애칭. 친근한 별명.",
  "speculate":"specul(보다)+ate. 사색하다; 투기하다. 관찰에서 추측으로.",
  "stolid":"둔감하고 무표정한. 감정을 전혀 드러내지 않는.",
  "suborn":"sub(아래로)+orn(꾸미다). 매수하다, 특히 위증을 시키다.",
  "tamper":"tamper(함부로 다루다). 뇌물로 매수하다. 조작하다(tamper with).",
  "vacillate":"vacill(흔들리다)+ate. 결정 못 하고 망설이다. 흔들리는.",
  "venal":"ven(팔다)+al. 돈으로 살 수 있는, 매수 가능한.",
  "waver":"wave(파도)+er. 파도처럼 흔들리다. 결정을 못 하다.",
});

// Auto-extracted word meanings (225 words)
Object.assign(window.__V502_EXT__.wordMeanings,{
  "abdicate":"(권리 등을) 버리다, 포기하다",
  "abjure":"맹세하고 버리다",
  "abnegate":"버리다; 자제하다",
  "abolish":"(판례·제도 등을) 폐지하다",
  "abrogate":"(법률·습관 따위를) 폐지하다",
  "accumulate":"(재산 따위를) 축적하다",
  "acerbic":"(기질·태도 등이) 거친",
  "acid":"신랄한",
  "acidulent":"신랄한; 다소 신맛이 도는",
  "acidulous":"신랄한",
  "acute":"혜안의, 명민한",
  "affable":"상냥한",
  "agile":"기민한; 날렵한",
  "appellation":"명칭",
  "appreciable":"감지할 수 있을 정도의",
  "argute":"빈틈없는",
  "astute":"기민한",
  "attract":"-의 마음을 끌다",
  "awesome":"경탄할 만한",
  "becloud":"흐리게 하다",
  "begrime":"(연기·때로) 더럽히다",
  "billingsgate":"런던의 어시장; 악담",
  "bite":"베어 물다",
  "blabber":"헛소리를 지껄이다",
  "bland":"(맛이) 자극적이지 않은, 특별한 맛이 없는",
  "blandishment":"아첨하는 말",
  "blase":"환락에 물린",
  "blunder":"(비밀 등을) 무심코 입 밖에 내다",
  "blurt":"무심코 비밀 따위를 폭로하다",
  "bolt":"무심코 비밀 따위를 폭로하다",
  "bombast":"과장하는 말",
  "bouquet":"아첨하는 말",
  "brilliant":"두뇌가 날카로운",
  "calm":"침착한",
  "canny":"현명한",
  "carnage":"대량 학살",
  "chatter":"재잘거리다",
  "chew":"어금니로 씹다",
  "chomp":"우적우적 깨물다",
  "circumlocution":"완곡어법",
  "club":"곤봉으로 치다",
  "compliment":"칭찬하는 말",
  "compromise":"(명성·신용 등을) 더럽히다",
  "congenial":"(사람이) 마음이 맞는",
  "corruptible":"부패하기 쉬운",
  "crunch":"아삭아삭 깨물다",
  "cutting":"예리한, 통렬한",
  "dehydrate":"탈수하다",
  "delicious":"아주 맛있는",
  "demonstrative":"심정을 토로하는",
  "denomination":"명명, 화폐의 명칭",
  "derogative":"명예를 손상하는",
  "derogatory":"(명예·인격 따위를) 손상시키는",
  "desist":"그만두다, 중지하다",
  "diatribe":"통렬한 비판",
  "dig":"진실을 탐구하다, 찾아내다",
  "diminutive":"소형의, 작은; 애칭",
  "disclaim":"(권리 등을) 포기하다",
  "disgrace":"불명예",
  "dishonor":"불명예",
  "disinter":"(숨겨진 곳에서) 드러내다",
  "douse":"(-에 액체를 흠뻑) 붓다",
  "edgy":"가시 돋친, 신랄한",
  "effusive":"심정을 토로하는",
  "enchant":"매혹하다",
  "encomium":"송덕문",
  "engage":"-의 마음을 끌다",
  "enormous":"거대한, 막대한",
  "entrance":"황홀하게 하다",
  "equivoke":"재담",
  "eulogy":"송덕문",
  "explicit":"(진술이) 뚜렷한",
  "falter":"말을 더듬다",
  "fetch":"매혹하다",
  "flattery":"아첨하는 말",
  "flavor":"맛",
  "flicker":"흔들리다",
  "fustian":"과장하는 말",
  "genial":"(사람이) 마음이 맞는",
  "gentle":"가벼운, 순한",
  "gibber":"(흔히 공포에 질려) 횡설수설하다",
  "gnaw":"앞니로 갉다",
  "grandiloquence":"과장하는 말",
  "grime":"(연기·때로) 더럽히다",
  "gulp":"벌컥벌컥 마시다, 꿀꺽꿀꺽 마시다",
  "gusto":"맛, 풍미",
  "harangue":"꾸짖는 말",
  "hazy":"모호한",
  "hedge":"모호한 입장을 취해 사후 변명거리를 만들다",
  "hobble":"더듬거리며 말하다",
  "hover":"주저하다",
  "humor":"(사람·기질·취미 등을) 만족시키다",
  "hyperbole":"과장하는 말",
  "hypocorism":"완곡어법",
  "immerse":"빠져들게 하다",
  "impassive":"냉정한",
  "imperceptible":"감지할 수 없는",
  "incisive":"날카로운, 통렬한",
  "incognito":"익명(의), 익명자",
  "indifferent":"무관심한",
  "indignity":"수모",
  "inebriate":"취하게 하다",
  "infatuate":"얼빠지게 만들다; 매혹하다",
  "insensate":"감각이 없는",
  "intoxicate":"취하게 하다",
  "invective":"욕설",
  "keen":"(활동·사상 등에) 열정적인",
  "lackadaisical":"열의 없는",
  "languid":"활기 없는",
  "lapidary":"보석공, 돌의, 보석의",
  "lapidify":"돌이 되게 하다",
  "laudation":"칭찬하는 말",
  "lenient":"관대한",
  "levy":"(세금 따위를) 징수하다",
  "linger":"(시간을) 우물쭈물 보내다",
  "listless":"무관심한, 게으른",
  "longheaded":"머리가 좋은; 선견지명이 있는",
  "massacre":"대량 학살하다",
  "mellifluous":"(꿀같이) 단",
  "mellow":"술이 향기로운",
  "mercenary":"보수를 목적으로 하는",
  "mild":"(음식·음료가) 자극이 없는, 부드러운",
  "misnomer":"이름 잘못 부르기(쓰기)",
  "moniker":"별명",
  "mum":"잠자코 있는, 무언의",
  "munch":"아삭아삭 깨물다",
  "murky":"(표현 따위가) 애매한",
  "mute":"무언의",
  "nervous":"신경질적인; 흥분하기 쉬운",
  "nomenclature":"학명",
  "obloquy":"악평",
  "obscure":"(말·의미 따위가) 불분명한",
  "opine":"-라고 생각하다",
  "opprobrium":"맹비난",
  "oscillate":"(마음·의견 따위가) 동요하다",
  "palatable":"(음식 등이) 입에 맞는",
  "panegyric":"송덕문",
  "parlance":"어투, 어조",
  "patter":"속사포처럼 내뱉는 말",
  "perceptible":"인지할 수 있는",
  "periphrasis":"완곡어법",
  "perspicacious":"총명한, 통찰력 있는",
  "petrify":"돌로 만들다, 경화시키다",
  "petroglyph":"암석화",
  "petrography":"암석 분류학",
  "petrology":"암석학",
  "phraseology":"어투, 어조",
  "plaudit":"칭찬하는 말",
  "pomposity":"과장하는 말",
  "ponder":"깊이 생각하다",
  "pore":"곰곰이 생각하다",
  "preoccupy":"마음을 빼앗다",
  "prepossess":"(인물·태도 따위가) 호의를 품게 하다",
  "pun":"재담",
  "push":"밀다",
  "racy":"꾸밈없이 솔직한; 맛이 좋은",
  "rattle":"-에 대해 계속 떠벌리다",
  "redoubtable":"경외할 만한",
  "redundant":"(표현이) 불필요한",
  "relinquish":"(소유물 따위를) 포기하다; 그만두다",
  "relish":"맛, 풍미, 향기",
  "remarkable":"주목할 만한; 현저한",
  "renounce":"거부하다; 단념하다; 버리다",
  "repudiate":"거부하다",
  "resile":"주저하다, 회피하다 (from)",
  "restrained":"삼가는, 자제하는",
  "roll":"명부",
  "roundabout expression":"완곡어법",
  "sagacious":"총명한",
  "sapient":"약은, 영리한",
  "satisfy":"만족시키다",
  "savor":"맛, 풍미; 흥미",
  "scorch":"살짝 태우다, 시들게 하다, 말라죽게 하다",
  "screed":"꾸짖는 말",
  "scruple":"(-하기를) 망설이다",
  "sequestrate":"몰수하다",
  "shrewd":"영리한",
  "slate":"후보자(candidate)의 명부",
  "sluggish":"게으른, 동작이 굼뜬",
  "smack":"맛, 풍미",
  "smart":"현명한",
  "smite":"매혹시키다; 세게 때리다",
  "smoldered":"(감정이) 사무치는",
  "stagger":"망설이다, 주저하다",
  "standoffish":"(남에게) 쌀쌀한, 냉담한",
  "steep":"몰두하게 하다; 가파른",
  "stifled":"(감정 등이) 억눌러진",
  "strike":"-에 몰두하다, 반하다",
  "stupendous":"엄청난, 거대한",
  "suave":"입에 순한, 자극성이 없는",
  "swallow":"마시다, 들이키다, 삼키다",
  "swill":"벌컥벌컥 마시다, 폭음하다",
  "talkative":"이야기하기 좋아하는",
  "tangy":"(맛이) 짜릿한, (냄새가) 톡 쏘는",
  "taste":"미각",
  "tasteful":"감식력이 있는",
  "tasteless":"맛없는",
  "technicality":"전문용어",
  "terminology":"전문용어",
  "thaumaturge":"요술사",
  "tirade":"꾸짖는 말",
  "touchable":"만져 알 수 있는",
  "traducement":"악담",
  "transfix":"선 채로 그 자리에 꼼짝 못하게 하다",
  "transitory":"일시적인, 무상한",
  "transport":"황홀하게 만들다; 수송하다",
  "truculent":"공격적인",
  "trumpery":"허튼 소리",
  "turbid":"흐린, 혼탁한",
  "unappreciable":"너무 작아서 인지할 수 없는",
  "unbury":"무덤에서 파내다; 발굴하다",
  "uncommunicative":"속을 터놓지 않는",
  "unpalatable":"입에 맞지 않는; 맛없는",
  "unsavory":"맛이 좋지 않은",
  "untouchable":"실체가 없는",
  "vague":"막연한, 애매한",
  "vanishing":"사라지는",
  "vernacular":"학명이 아닌 통칭, 속명",
  "vituperate":"호통 치다",
  "vituperation":"악담",
  "waffle":"이해하기 어렵게 쓰거나 말하다",
  "waive":"(권리·요구 등을) 포기하다, 철회하다",
  "whip":"채찍질하다",
  "wordy":"말 많은, 장황한",
  "zest":"풍미, 맛; 향미",
});

// Extracted meanings batch (2 words)
Object.assign(window.__V502_EXT__.wordMeanings,{
  "exact":"강요하다, 받아내다",
  "tribute":"칭찬; 공물",
});
