// LOGIC TREE V502 — Categories 101-110
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"101",words:["conscientious", "meticulous", "punctilious", "scrupulous"]},
  {id:"102",words:["dainty", "demanding", "fastidious", "finical", "finicky", "fussy", "meticulous", "niggling", "overscrupulous", "pernickety", "persnickety", "stickling"]},
  {id:"103",words:["defer", "delay", "linger", "procrastinate", "retard", "stay", "tarry"]},
  {id:"104",words:["convoluted", "labyrinthine", "serpentine", "sinuous", "tortuous", "winding"]},
  {id:"105",words:["admonish", "arraign", "belabor", "berate", "chide", "declaim", "decry", "denounce", "except", "fault", "harangue", "hiss", "impeach", "impugn", "oppugn", "criminate", "incriminate", "recriminate", "rate", "rebuke"]},
  {id:"106",words:["baste", "belabor", "berate", "castigate", "censure", "chastise", "deprecate", "excoriate", "execrate", "flay", "fulminate", "lambaste", "lash", "whip", "rail", "slate", "upbraid", "maul", "blameworthy", "culpable", "impeachable", "objectionable", "reprehensible"]},
  {id:"107",words:["viscous", "viscid", "glutinous", "sticky", "tacky"]},
  {id:"108",words:["seethe", "simmer", "stew"]},
  {id:"109",words:["high-strung", "overtensed", "overwrought"]},
  {id:"110",words:["damp", "dampen", "deject", "depress", "despond", "dishearten", "dispirit"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "admonish":"훈계하다",
  "arraign":"심문하다, 나무라다",
  "baste":"야단치다",
  "belabor":"호되게 꾸짖다",
  "berate":"호되게 꾸짖다",
  "blameworthy":"질책당할 만한",
  "castigate":"혹평하다; 매질하다",
  "censure":"비난하다, (비평가가) 혹평하다",
  "chastise":"꾸짖다",
  "chide":"꾸짖다, -에게 잔소리하다",
  "conscientious":"신중한; 양심적인",
  "convoluted":"소용돌이 모양의; 뒤얽힌",
  "criminate":"비난하다",
  "culpable":"비난할 만한",
  "dainty":"(기호가) 까다로운",
  "damp":"풀이 죽게 하다",
  "dampen":"풀이 죽게 하다",
  "declaim":"-을 비난하다; 연설하다",
  "decry":"(통화 등의) 가치를 떨어뜨리다, 공공연히 비난하다",
  "defer":"경의를 표하다; 미루다",
  "deject":"기를 죽이다",
  "delay":"미루다, 연기하다",
  "demanding":"(사람이) 너무 지나친 요구를 하는",
  "denounce":"맹렬히 비난하다",
  "deprecate":"업신여기다; 반대하다",
  "depress":"풀이 죽게 하다",
  "despond":"실망하다",
  "dishearten":"낙담시키다",
  "dispirit":"-의 기력을 꺾다",
  "except":"반대하다; 제외하다; -을 제외하고",
  "excoriate":"피부를 벗기다; 혹평하다",
  "execrate":"저주하다; 혐오하다",
  "fastidious":"꼼꼼한",
  "fault":"비난하다",
  "finical":"지나치게 공들인",
  "finicky":"지나치게 까다로운",
  "flay":"가죽을 벗기다; 돈을 뜯어내다",
  "fulminate":"심하게 비난하다",
  "fussy":"성가신; 까다로운",
  "glutinous":"점착성의",
  "harangue":"꾸짖는 말",
  "high-strung":"극도로 긴장한",
  "hiss":"쉿하고 꾸짖다",
  "impeach":"탄핵하다; 비난하다",
  "impeachable":"(범죄가) 탄핵 대상이 되는",
  "impugn":"의문을 제기하다",
  "incriminate":"-에게 죄를 씌우다, 고소하다",
  "labyrinthine":"미궁의, 미로와 같은",
  "lambaste":"맹공격하다",
  "lash":"몹시 꾸짖다",
  "linger":"(꾸물거려) 시간이 걸리다",
  "maul":"혹평하다",
  "meticulous":"매우 신중한",
  "niggling":"하찮은 일에 신경 쓰는",
  "objectionable":"못마땅한",
  "oppugn":"비난하다",
  "overscrupulous":"너무 세심한",
  "overtensed":"지나치게 긴장한",
  "overwrought":"너무 긴장한",
  "pernickety":"까다로운",
  "persnickety":"까다로운",
  "procrastinate":"지연하다, 꾸물거리다",
  "punctilious":"세심하고 정밀한",
  "rail":"욕을 퍼붓다, 악담하다",
  "rate":"꾸짖다, 욕설을 퍼붓다",
  "rebuke":"비난하다",
  "recriminate":"맞비난하다",
  "reprehensible":"비난할 만한",
  "retard":"지체시키다",
  "scrupulous":"빈틈없는",
  "seethe":"심하게 펄펄 끓다",
  "serpentine":"꾸불꾸불한; 교활한; 뱀 같은",
  "simmer":"약한 불에 지글지글 끓다",
  "sinuous":"(강 따위가) 구불구불한",
  "slate":"(책 따위를) 혹평하다",
  "stay":"우물쭈물하다",
  "stew":"약한 불에 오랫동안 달이다(졸이다)",
  "stickling":"사소한 일에 구애되는",
  "sticky":"들러붙는",
  "tacky":"끈적끈적한",
  "tarry":"시간이 걸리다, 늦어지다",
  "tortuous":"(길·흐름 따위가) 구불구불한",
  "upbraid":"신랄하게 비판하다",
  "viscid":"끈적이는",
  "viscous":"점성의",
  "whip":"채찍질하다",
  "winding":"굽이치는, 꾸불꾸불한"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "101":"꼼꼼한, 신중한",
  "102":"(지나치게) 꼼꼼한, 까다로운",
  "103":"꾸물대다",
  "104":"꾸불꾸불한",
  "105":"꾸짖다, 비난하다",
  "106":"(심하게) 꾸짖다, (심하게) 비난하다",
  "107":"끈적끈적한",
  "108":"끓다",
  "109":"(지나치게) 긴장하다",
  "110":"낙담하게 하다"
});
