// LOGIC TREE V502 — Categories 021-030
// Auto-generated from V502.pdf pages 7-9
// Loaded before app.v6.js; merged into main data structures at init time.

window.__V502_EXT__ = {};
window.__V502_EXT__.categories = [
  {
    id: "021",
    words: [
      "rebuff",
      "snort",
      "snub",
      "spurn",
      "repel",
      "repulse",
    ],
  },
  {
    id: "022",
    words: [
      "healthful",
      "salubrious",
      "salutary",
      "salutiferous",
      "wholesome",
      "advantageous",
      "auspicious",
      "beneficial",
      "benign",
      "favorable",
      "lucrative",
      "profitable",
      "propitious",
      "toward",
    ],
  },
  {
    id: "023",
    words: [
      "bustle",
      "gallop",
      "rustle",
      "scurry",
      "scuttle",
      "trot",
      "scamp",
      "amble",
      "canter",
      "lope",
      "slither",
      "lumber",
      "waddle",
      "flit",
      "plod",
      "trudge",
      "flop",
      "scuff",
      "shuffle",
      "gambol",
      "dally",
      "dawdle",
      "diddle",
      "idle",
      "loaf",
      "loiter",
      "loll",
      "lounge",
      "maunder",
      "meander",
      "piddle",
      "prowl",
      "ramble",
      "roam",
      "rove",
      "saunter",
      "traipse",
      "wander",
      "dash",
      "rush",
      "scuffle",
      "hobble",
      "limp",
      "mince",
      "stalk",
      "strut",
      "swagger",
      "lurch",
      "reel",
      "shamble",
      "stagger",
      "sway",
      "topple",
      "totter",
      "droop",
      "slouch",
      "crouch",
      "flinch",
      "grovel",
      "quail",
      "recoil",
      "shrink",
      "shrivel",
      "wince",
    ],
  },
  {
    id: "024",
    words: [
      "cowardice",
      "cravenness",
      "funk",
      "timidity",
      "timorousness",
      "trepidation",
    ],
  },
  {
    id: "025",
    words: [
      "caitiff",
      "cowardly",
      "craven",
      "poltroon",
      "pusillanimous",
      "recreant",
      "sissy",
      "skittish",
      "timid",
      "timorous",
      "trepid",
    ],
  },
  {
    id: "026",
    words: [
      "balk",
      "boggle",
      "cower",
      "cringe",
    ],
  },
  {
    id: "027",
    words: [
      "audacious",
      "bold",
      "dauntless",
      "fearless",
      "intrepid",
      "brash",
      "rash",
      "foolhardy",
      "headlong",
      "impetuous",
      "imprudent",
      "impulsive",
      "overbold",
      "reckless",
      "bravado",
      "overboldness",
      "temerity",
      "gallantry",
      "grit",
      "guts",
      "mettle",
      "mettlesome",
      "pluck",
      "plucky",
      "prowess",
      "prow",
      "valiance",
      "valiancy",
      "valiant",
      "valor",
      "valorous",
    ],
  },
  {
    id: "028",
    words: [
      "caitiff",
      "coward",
      "craven",
      "dastard",
      "funk",
      "poltroon",
      "recreant",
      "sissy",
    ],
  },
  {
    id: "029",
    words: [
      "bluster",
      "browbeat",
      "bully",
      "daunt",
      "dismay",
      "hector",
      "intimidate",
      "menace",
      "threaten",
    ],
  },
  {
    id: "030",
    words: [
      "garish",
      "gaudy",
      "gewgaw",
      "loud",
      "meretricious",
      "showy",
      "tatty",
      "tawdry",
      "trumpery",
      "bauble",
      "gaud",
      "trinket",
    ],
  },
];

window.__V502_EXT__.wordMeanings = {
  // 021 — reject / refuse
  rebuff: "퇴짜(하다)",
  snort: "콧방귀를 뀌다",
  snub: "무시하다",
  spurn: "퇴짜 놓다",
  repel: "격퇴하다",
  repulse: "물리치다",

  // 022 — healthy / beneficial
  healthful: "건강에 좋은",
  salubrious: "살기 좋은",
  salutary: "유익한",
  salutiferous: "건강에 유익한",
  wholesome: "건강에 좋은",
  advantageous: "이로운",
  auspicious: "길조의",
  beneficial: "유익한",
  benign: "양성의",
  favorable: "호의적인",
  lucrative: "금전적으로 유리한, 수지가 맞는",
  profitable: "수익성이 있는",
  propitious: "길조의",
  toward: "우호적인",

  // 023 — walking / moving styles
  bustle: "(말이) 빠르게 걷다",
  gallop: "(말이) 빠르게 뛰다",
  rustle: "(말이) 빠르게 걷다",
  scurry: "(말이) 빠르게 걷다",
  scuttle: "(말이) 빠르게 걷다",
  trot: "(말이) 빠르게 걷다",
  scamp: "(말이) 빠르게 걷다",
  amble: "(말이) 천천히 걷다",
  canter: "(말이) 천천히 뛰다",
  lope: "(말이) 천천히 뛰다",
  slither: "(뱀이) 미끄러지듯 기어가다",
  lumber: "(곰이) 쿵쿵거리며 걷다; 무겁게 움직이다",
  waddle: "(오리나 거위가) 뒤뚱뒤뚱 걸어가다",
  flit: "(새가) 훨훨 날다; 가볍고 빠르게 지나가다",
  plod: "발을 질질 끌며 터벅터벅 걷다",
  trudge: "무거운 걸음으로 터벅터벅 걷다",
  flop: "발걸음이 무겁게 터덕터덕 걷다",
  scuff: "발을 질질 끌다",
  shuffle: "발을 질질 끌며 걷다",
  gambol: "껑충껑충 (천천히) 뛰다",
  dally: "미적거리다",
  dawdle: "꾸물거리다",
  diddle: "시간을 낭비하다",
  idle: "빈둥거리다",
  loaf: "어슬렁거리다",
  loiter: "빈둥거리다",
  loll: "나른하게 누워있다",
  lounge: "느긋하게 앉아있다",
  maunder: "두서없이 말하다; 꾸물거리다",
  meander: "이리저리 거닐다",
  piddle: "한가하게 지내다",
  prowl: "(먹이를 찾아) 배회하다",
  ramble: "두서없이 말하다; (전원 속을) 거닐다",
  roam: "(이리저리) 돌아다니다",
  rove: "방랑하다",
  saunter: "한가로이 걷다",
  traipse: "터벅터벅 걷다",
  wander: "거닐다",
  dash: "돌진하다",
  rush: "돌진하다",
  scuffle: "휙 움직이다",
  hobble: "다리를 절다",
  limp: "절뚝거리다",
  mince: "(고상한 척) 짧고 빠르게 걷다",
  stalk: "(거드름을 피우며) 으스대며 걷다",
  strut: "점잔 빼며 걷다",
  swagger: "으스대며 걷다",
  lurch: "(갑자기) 휘청하다",
  reel: "비틀거리다",
  shamble: "비틀걸음으로 걷다",
  stagger: "비틀거리다",
  sway: "흔들리다",
  topple: "넘어지다",
  totter: "비틀거리다",
  droop: "구부정하게 걷다; 풀이 죽다",
  slouch: "구부정하게 서다",
  crouch: "쭈그리다",
  flinch: "움찔하다",
  grovel: "굽실거리다",
  quail: "겁을 먹다",
  recoil: "움츠러들다",
  shrink: "오그라들다",
  shrivel: "위축되다",
  wince: "움찔하고 놀라다",

  // 024 — fear / timidity
  cowardice: "겁",
  cravenness: "소심함",
  funk: "무서움, 겁쟁이",
  timidity: "겁 많음",
  timorousness: "무서워함",
  trepidation: "두려움",

  // 025 — cowardly / fearful
  caitiff: "비열한 자, 겁쟁이",
  cowardly: "겁이 많은",
  craven: "용기 없는",
  poltroon: "겁쟁이",
  pusillanimous: "겁 많은",
  recreant: "용기 없는",
  sissy: "나약한",
  skittish: "겁이 많은",
  timid: "소심한",
  timorous: "겁이 많은",
  trepid: "소심한",

  // 026 — be afraid
  balk: "멈칫거리다",
  boggle: "주춤하다",
  cower: "(겁먹고) 몸을 숙이다",
  cringe: "움츠리다",

  // 027 — fearless / brave
  audacious: "대담한",
  bold: "용감한",
  dauntless: "불굴의",
  fearless: "두려움을 모르는",
  intrepid: "용감무쌍한",
  brash: "경솔한",
  rash: "성급한",
  foolhardy: "무모한",
  headlong: "저돌적으로",
  impetuous: "성급한",
  imprudent: "경솔한",
  impulsive: "충동적인",
  overbold: "지나치게 대담한",
  reckless: "무모한",
  bravado: "허세",
  overboldness: "지나친 대담함",
  temerity: "만용",
  gallantry: "용맹",
  grit: "투지, 기개",
  guts: "배짱",
  mettle: "패기",
  mettlesome: "패기 있는",
  pluck: "용기",
  plucky: "용기 있는",
  prowess: "용기, 무용; 기술, 역량",
  prow: "용기 있는",
  valiance: "용기",
  valiancy: "용맹",
  valiant: "용맹한",
  valor: "용맹",
  valorous: "씩씩한",

  // 028 — coward (noun)
  caitiff: "겁쟁이",
  coward: "비겁자",
  dastard: "비겁자",
  funk: "공포; 겁쟁이",

  // 029 — intimidate / threaten
  bluster: "엄포를 놓다",
  browbeat: "협박(겁박)하다",
  bully: "괴롭히다",
  daunt: "겁먹게 하다",
  dismay: "실망시키다; 실망",
  hector: "위협하다",
  intimidate: "겁을 주다",
  menace: "위협하다",
  threaten: "협박(겁박)하다",

  // 030 — gaudy / tawdry
  garish: "야한",
  gaudy: "천박한",
  gewgaw: "겉만 번지르르한",
  loud: "야한",
  meretricious: "겉치레뿐인",
  showy: "현란한",
  tatty: "닳아 해진",
  tawdry: "저속한",
  trumpery: "야하고 값싼",
  bauble: "싸구려 보석",
  gaud: "싸구려 장식품",
  trinket: "값싼 장신구",
};

window.__V502_EXT__.categorySummaries = {
  "021": "reject / refuse",
  "022": "healthy / beneficial",
  "023": "walking / moving styles",
  "024": "fear / timidity",
  "025": "cowardly / fearful",
  "026": "be afraid",
  "027": "fearless / brave",
  "028": "coward (noun)",
  "029": "intimidate / threaten",
  "030": "gaudy / tawdry",
};

window.__V502_EXT__.confusionNotes = {
  // 021
  rebuff: "'퇴짜'의 대표 단어입니다. 거절의 뉘앙스가 강합니다.",
  snort: "말이 콧김을 내뿜듯 경멸 섞인 거절을 뜻합니다.",
  snub: "일부러 무시하는 느낌으로, 사회적 거절에 가깝습니다.",
  spurn: "발로 차듯 경멸하며 거절하는 강한 어감입니다.",
  repel: "물리적으로 밀어내는 뜻도 있어 '격퇴하다'와 '거절하다' 모두 가능합니다.",
  repulse: "repel과 유사하지만 특히 감정적 거부감이 섞여 있습니다.",

  // 022
  healthful: "건강에 '좋은' (healthy는 '건강한' 상태). healthful은 외부 요인이 건강에 좋다는 뜻.",
  salubrious: "기후나 환경이 살기 좋고 건강에 이로운 느낌입니다.",
  salutary: "경험이나 교훈이 유익한 쪽. 육체적 건강보다 도덕적·정신적 유익을 강조.",
  salutiferous: "salutary + ferrous(운반하는). 건강을 가져다주는 느낌의 희귀 단어.",
  wholesome: "몸과 마음에 두루 좋은, 건전한 느낌.",
  benign: "'양성의' 의학적 뜻이 먼저 떠오르지만, 성격·환경이 온화하고 유익한 의미도 있습니다.",
  propitious: "신이 내린 길조 같은 느낌. auspicious와 유사.",
  toward: "방향 부사로 익숙하지만, '우호적인, 순종적인' 뜻의 형용사가 있습니다.",

  // 023
  bustle: "바쁘게 움직이는 느낌. 'bustling city'처럼 혼잡한 활기의 뉘앙스도 있습니다.",
  gallop: "말의 전속력 질주. canter(구보)와 속도 차이가 있습니다.",
  scurry: "작은 동물이 바쁘게 달리는 느낌. scuttle, scamper와 유사.",
  amble: "말이 천천히 걷는 걸음걸이. 사람에게 쓰면 한가로이 산책하는 느낌.",
  canter: "말의 구보(빠르지만 gallop보다 느림).",
  lope: "말이나 사람이 성큼성큼 뛰는 느낌. 힘 있고 여유 있는 달리기.",
  slither: "뱀처럼 미끄러지듯 나아가는 움직임.",
  lumber: "곰처럼 무겁고 둔하게 움직이는 모습. 동사/명사 모두 가능.",
  waddle: "오리나 펭귄처럼 뒤뚱거리며 걷는 귀여운 느낌.",
  flit: "새나 나비가 훨훨 가볍게 나는 모습. 빠르고 가벼운 움직임.",
  plod: "느리고 무거운 걸음. 터벅터벅. trudge와 유사하나 덜 지친 느낌.",
  trudge: "지쳐서 무겁게 터벅터벅 걷는 모습.",
  hobble: "다리를 절거나 불편하게 걷는 모습. limp와 유사.",
  limp: "다리를 저는 걸음걸이.",
  strut: "뽐내며 걷다. swagger와 유사하나 더 경쾌하고 자랑스러운 느낌.",
  swagger: "으스대며 걷다. 거만함이 강조됨.",
  mince: "(고상한 척) 짧고 빠르게 걷는 모습. 'mincing steps'.",
  lurch: "갑자기 휘청하거나 기우는 움직임. 예상치 못한 방향 전환.",
  reel: "어지러워 비틀거리는 모습. 술 취한 듯한 움직임.",
  shamble: "발을 질질 끌며 느릿느릿 걷는 불안정한 걸음걸이.",
  stagger: "비틀거리며 걷다. reel보다 더 심한 불안정함.",
  topple: "균형을 잃고 넘어지다. 정치적 '전복'의 뜻도.",
  totter: "노인이나 아기가 비틀거리며 걷는 불안정한 모습.",
  droop: "축 처지다. 어깨가 축 처지거나 꽃이 시들 때.",
  slouch: "구부정한 자세로 앉거나 서다. 자세가 나쁜 모습.",
  crouch: "웅크리다. 몸을 낮추고 숨는 느낌.",
  flinch: "놀라거나 두려워서 움찔하는 순간적 반응.",
  grovel: "엎드려 굽실거리다. 비굴한 느낌.",
  quail: "겁을 먹고 움츠러들다. 메추라기(명사) 뜻도 있음.",
  recoil: "총의 반동처럼, 놀라서 뒤로 물러서는 움직임.",
  shrink: "줄어들다, 오그라들다. 겁먹고 몸을 움츠리는 느낌.",
  shrivel: "바싹 마르거나 쪼글쪼글해지다. 열기가 원인인 경우 많음.",
  wince: "통증이나 불쾌감에 얼굴을 찡그리며 움찔하다.",

  // 024
  funk: "'음악 장르' 뜻이 먼저 떠오르지만, '겁, 공포'의 의미도 있습니다.",
  trepidation: "trepid가 어근. 두려움으로 인한 떨림, 불안한 기대.",

  // 025
  caitiff: "비열하고 겁 많은 사람. 고어체로 현대에는 잘 안 쓰입니다.",
  pusillanimous: "pusill(작은) + anim(영혼). 영혼이 작아 겁이 많다는 뉘앙스.",
  recreant: "용기 없이 도망치는 사람. 중세 기사도 맥락의 고어.",
  skittish: "말이 잘 놀라는 성질. 사람에게 쓰면 변덕스럽고 겁 많은 느낌.",
  trepid: "intrepid(용감한)의 반대말. 두려워하는.",

  // 026
  balk: "갑자기 멈추거나 주저하다. 스포츠에서는 '보크(반칙)'.",
  boggle: "놀라서 망설이다. 'mind-boggling'으로 익숙한 단어.",
  cower: "겁먹고 몸을 웅크리다. 피학적이고 수동적인 두려움.",
  cringe: "오그라들다, 민망해하다. 현대에는 '오글거리다'라는 신조어적 용법도.",

  // 027
  audacious: "대담한. 긍정적(용기)과 부정적(무례함) 모두 가능.",
  dauntless: "daunt(겁먹게 하다) + less. 무엇에도 겁먹지 않는.",
  intrepid: "in(not) + trepid(두려워하는). 두려움이 전혀 없는.",
  foolhardy: "fool + hardy. 무모할 정도로 용감한. reckless와 유사.",
  headlong: "머리부터 들이밀 듯 저돌적인. 신중함이 결여된.",
  reckless: "결과를 생각하지 않고 무모한. foolhardy와 유사하나 더 부정적.",
  bravado: "겉으로 드러내는 허세. 실제 용기보다 과시에 가까움.",
  temerity: "지나친 대담함, 만용. 상대방에게 무례하게 느껴질 정도의 용기.",
  mettle: "metal의 변형. 시련 속에서 드러나는 진짜 용기와 인내.",
  prowess: "전투에서의 용맹함. 현대에는 뛰어난 기량 일반을 뜻하기도.",
  valiance: "용기. valiant의 명사형. 다소 고어체.",
  valorous: "용맹한. 전쟁 영웅에게 어울리는 표현.",

  // 028
  dastard: "비겁하고 비열한 사람. 'dastardly act'(비열한 짓).",
  poltroon: "겁쟁이. 이탈리아어에서 유래한 고어체.",
  caitiff: "028에서는 명사 '겁쟁이', 025에서는 형용사 '비열한'으로 쓰입니다.",

  // 029
  bluster: "소리치며 위협하지만 실제 힘은 없는 허풍 섞인 협박.",
  browbeat: "눈썹(brow)으로 때리듯(beat) 으스대며 위협하다.",
  hector: "트로이 전쟁의 Hector에서 유래. 약자를 괴롭히는 허세꾼 느낌.",
  daunt: "겁을 주어 의욕을 꺾다. 주로 수동태로 'daunted by~'로 씀.",
  dismay: "실망과 놀람, 두려움이 섞인 감정.",

  // 030
  garish: "지나치게 화려하고 천박한. 눈에 거슬리는 느낌.",
  gaudy: "값싸고 번지르르한. 천박한 과시.",
  gewgaw: "겉만 번지르르하고 실속 없는 장식품.",
  meretricious: "meretrix(매춘부)에서 유래. 겉만 그럴듯하고 실속 없는.",
  tawdry: "값싸고 천박한. St. Audrey에서 어원이 왔다는 재미있는 유래.",
  trumpery: "겉만 번지르르한 가짜. trump(나팔)과 어원이 같음 (허풍).",
  bauble: "값싼 장신구. 크리스마스 트리 장식 같은 반짝이.",
  trinket: "작고 값싼 장식품. 귀엽지만 대단치 않은 물건.",
};

Object.assign(window.__V502_EXT__.wordMeanings,{
  "advantageous":"이로운",
  "amble":"(말이) 천천히 걷다",
  "audacious":"대담한",
  "auspicious":"길조의",
  "balk":"멈칫거리다, 실망시키다; 장애, 훼방",
  "bauble":"싸구려 보석",
  "beneficial":"유익한",
  "benign":"양성의",
  "bluster":"엄포를 놓다           게으름뱅이",
  "boggle":"주춤하다",
  "bold":"용감한",
  "brash":"경솔한, 분별없는",
  "bravado":"허세",
  "browbeat":"협박[겁박]하다",
  "bully":"괴롭히다",
  "bustle":"(말이) 빠르게 걷다",
  "caitiff":"비열한 자, 겁쟁이",
  "canter":"(말이) 천천히 뛰다",
  "coward":"비겁자",
  "cowardly":"겁이 많은",
  "cower":"(겁먹고) 몸을 숙이다",
  "craven":"용기 없는",
  "cravenness":"소심함",
  "cringe":"굽실거리다, 움츠리다",
  "crouch":"굽실거리다",
  "dally":"미적거리다, (시간 등을) 허비하다",
  "dash":"돌진하다",
  "dastard":"비겁자",
  "daunt":"겁먹게 하다",
  "dauntless":"불굴의, 겁 없는",
  "dawdle":"꾸물거리다",
  "diddle":"속이다, 편취하다                   터무니없이 높은 가격으로 바가지를 씌우다",
  "dismay":"실망시키다; 실망",
  "droop":"구부정하게 걷다; 풀이 죽다, 시들다",
  "favorable":"호의를 보이는",
  "fearless":"두려움을 모르는",
  "flinch":"움찔하다",
  "flit":"(새가) 훨훨 날다; 가볍고 빠르게 지나가다",
  "flop":"발걸음이 무겁게 터덕터덕 걷다",
  "foolhardy":"무모한",
  "funk":"무서움, 겁쟁이",
  "gallantry":"용맹",
  "gallop":"(말이) 빠르게 뛰다",
  "gambol":"껑충껑충 (천천히) 뛰다",
  "garish":"야한; 화려한",
  "gaud":"겉만 번드르르한 값싼 물건",
  "gaudy":"천박한",
  "gewgaw":"겉만 번지르르한, 허울뿐인",
  "grit":"투지, 기개",
  "grovel":"비굴한 태도를 취하다",
  "guts":"배짱",
  "headlong":"성급한, 매우 서두는",
  "healthful":"건강에 좋은",
  "hector":"위협하다",
  "hobble":"다리를 절다, 더듬거리며 말하다",
  "idle":"빈둥거리다, 태만한",
  "impetuous":"성급한, 충동적인",
  "imprudent":"경솔한",
  "impulsive":"충동적인",
  "intimidate":"겁을 주다",
  "intrepid":"두려움을 모르는",
  "limp":"(몸 따위가) 흐느적거리는; 절뚝거리다",
  "loaf":"어슬렁거리다",
  "loiter":"빈둥거리다",
  "loll":"나른하게 누워 있다",
  "lope":"껑충껑충 (천천히) 뛰다",
  "loud":"야한",
  "lounge":"느긋하게 앉아있다                  구부정하게 걷다",
  "lucrative":"금전적으로 유리한, 수지가 맞는   껑충껑충 뛰다",
  "lumber":"(곰이) 쿵쿵거리며 걷다; 무겁게 움직이다",
  "lurch":"(갑자기) 휘청하다; 불리한 입장, 곤경",
  "maunder":"두서없이 말하다; 꾸물거리다",
  "meander":"이리저리 거닐다",
  "menace":"위협하다",
  "meretricious":"겉치레뿐인",
  "mettle":"기질; 기개",
  "mettlesome":"기개 있는, 용기 있는",
  "mince":"(고상한 척) 짧고 빠르게 걷다",
  "overbold":"지나치게 대담한",
  "overboldness":"지나치게 대담함",
  "piddle":"시간을 낭비하다, 한가하게 지내다",
  "plod":"발을 질질 끌며 터벅터벅 걷다",
  "pluck":"용기, 담력",
  "plucky":"용기 있는",
  "poltroon":"겁쟁이",
  "profitable":"수익성이 있는",
  "propitious":"길조의",
  "prow":"용감한, 용맹스런",
  "prowess":"용기, 무용; 기술, 역량",
  "prowl":"(도둑 따위가) 동정을 살피다; (먹이 찾아) 배회하다",
  "pusillanimous":"겁 많은",
  "quail":"겁을 먹다; 메추라기",
  "ramble":"두서없이 말하다; (특히 전원 속을) 거닐다",
  "rash":"경솔한, 성급한, 분별없는",
  "rebuff":"퇴짜(하다)",
  "reckless":"무모한",
  "recoil":"움츠러들다",
  "recreant":"용기 없는",
  "reel":"비틀거림",
  "repel":"혐오감을 느끼게 하다; 격퇴하다",
  "repulse":"구역질나게 하다; 물리치다",
  "roam":"(이리저리) 돌아다니다",
  "rove":"방랑하다",
  "rush":"돌진하다",
  "rustle":"(말이) 빠르게 걷다, 가죽을 훔치다",
  "salubrious":"살기 좋은",
  "salutary":"유익한",
  "salutiferous":"건강에 유익한",
  "saunter":"한가로이 걷다",
  "scamp":"(말이) 빠르게 걷다",
  "scuff":"발을 질질 끌다",
  "scuffle":"격투, 난투; 휙 움직이다",
  "scurry":"빠르게 달리다",
  "scuttle":"(말이) 빠르게 걷다",
  "shamble":"비틀걸음으로 걷다",
  "showy":"화려한, 현란한",
  "shrink":"(수량·가치 등이) 줄어들다, 오그라들다",
  "shrivel":"시들다, 위축되다",
  "shuffle":"모호한 태도(말)로 난처함을 피하다",
  "sissy":"나약한, 유약한",
  "skittish":"들뜬; 겁 많은",
  "slither":"(뱀이) 미끄러지듯 기어가다",
  "slouch":"구부정하니 서다",
  "snort":"콧방귀를 뀌다                 (말이) 천천히 걷다",
  "snub":"무시하다",
  "spurn":"퇴짜 놓다",
  "stagger":"망설이다, 주저하다; 비틀거리다",
  "stalk":"(거드름을 피우며) 으스대며 걷다",
  "strut":"뽐내며 걷다; 지주, 버팀목",
  "swagger":"으스대는 사람",
  "sway":"흔들리다",
  "tatty":"닳아 해진",
  "tawdry":"야한; 값싸고 번지르르한; 저속한",
  "temerity":"무모함, 만용",
  "threaten":"협박[겁박]하다",
  "timid":"소심한",
  "timidity":"겁 많음",
  "timorous":"겁이 많은",
  "timorousness":"무서워함       무모한",
  "topple":"넘어지다",
  "totter":"비틀거리다",
  "toward":"우호적인, 형편 좋은",
  "traipse":"터벅터벅 걷다",
  "trepid":"소심한",
  "trepidation":"두려움",
  "trinket":"값싼 장신구, 시시한 것",
  "trot":"(말이) 빠르게 걷다",
  "trudge":"무거운 걸음으로 터벅터벅 걷다",
  "trumpery":"겉만 번드르르한; 하찮은; 야하고 값싼",
  "valiance":"용기",
  "valiancy":"용맹              겉만 번드르르한 싸구려 물건",
  "valiant":"용감한, 영웅적인",
  "valor":"용맹",
  "valorous":"씩씩한",
  "waddle":"(오리나 거위가) 뒤뚱뒤뚱 걸어가다",
  "wander":"거닐다",
  "wholesome":"건강에 좋은              터벅터벅 걷다",
  "wince":"움찔하고 놀라다",
});
