// LOGIC TREE V502 — Categories 251-300
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"251",words:["ashamed", "bashful", "shamefaced", "shy"]},
  {id:"252",words:["bending", "flexible", "limber", "lissom", "lissome", "lithe", "pliable", "pliant", "supple"]},
  {id:"253",words:["pariah", "outcast", "castaway", "exile"]},
  {id:"254",words:["addendum", "adjunct", "appendix", "appurtenance", "appendage", "concomitant", "codicil"]},
  {id:"255",words:["abnegate", "deprecate", "disapprobate", "disapprove", "disaffirm", "disown", "gainsay", "recant", "repeal", "reprobate", "rescind", "retract", "revoke"]},
  {id:"256",words:["affected", "contrived", "far-fetched", "labored", "mannered", "procrustean", "stereotyped", "strained", "unnatural"]},
  {id:"257",words:["amulet", "charm", "talisman"]},
  {id:"258",words:["sparse", "scanty", "scant", "meager", "scarce"]},
  {id:"259",words:["careless", "crude", "cursory", "delinquent", "derelict", "heedless", "inadvertent", "inattentive", "lax", "negligent", "perfunctory", "remiss", "slipshod", "supine"]},
  {id:"260",words:["unknowing", "unwitting", "unwittingly"]},
  {id:"261",words:["balloon", "bloat", "bulge", "dilate"]},
  {id:"262",words:["arrears", "liability", "obligation", "default", "insolvent"]},
  {id:"263",words:["regenerate", "rehabilitate", "resurrect", "resurge", "resuscitate", "retrieve"]},
  {id:"264",words:["cloister", "insulate", "isolate", "seclude", "segregate", "separate", "sequester", "wean", "disengage", "fragment"]},
  {id:"265",words:["apportion", "allot", "allocate", "assign", "impart", "mete"]},
  {id:"266",words:["breach", "cavity", "chasm", "cleft", "cove", "crack", "crevice", "fission", "fissure", "hiatus", "interstice", "pit", "rift", "schism"]},
  {id:"267",words:["blasphemous", "irreverent", "impious", "profane", "sacrilegious"]},
  {id:"268",words:["partial", "biased", "prejudiced", "bigoted", "tendentious", "jaundiced"]},
  {id:"269",words:["amputate", "cripple", "disable", "dismember", "hamstring", "incapacitate", "maim", "mutilate", "paralyze"]},
  {id:"270",words:["acarpous", "arid", "bare", "barren", "bleak", "desolate", "forlorn", "impoverished", "infertile", "sterile", "unproductive", "waste"]},
  {id:"271",words:["misadventure", "mischance", "mishap", "haplessness"]},
  {id:"272",words:["abhorrence", "abomination", "antipathy", "aversion", "disgust", "loathing", "malaise", "nausea", "odium", "pique", "repugnance", "repulsion", "resentment", "revulsion", "umbrage"]},
  {id:"273",words:["disgust", "repel", "nauseate", "repulse", "revolt", "sicken"]},
  {id:"274",words:["abhorrent", "disgusting", "fulsome"]},
  {id:"275",words:["aggrieve", "disgruntle", "dissatisfy"]},
  {id:"276",words:["grieve", "grouch", "grouse", "growl", "grumble", "grump", "grunt", "ramble", "repine", "snivel", "whine"]},
  {id:"277",words:["hazy", "murky", "nebulous", "opaque", "turbid", "vague"]},
  {id:"278",words:["loner", "lone wolf", "maverick", "nonconformist", "recusant"]},
  {id:"279",words:["iniquity", "turpitude", "vileness", "villainy"]},
  {id:"280",words:["iniquitous", "naughty", "scurvy", "vile", "villainous", "wicked"]},
  {id:"281",words:["fecund", "fertile", "fructuous", "fruitful", "productive", "prolific"]},
  {id:"282",words:["ignoble", "Ignominious", "vile"]},
  {id:"283",words:["dormant", "immobile", "inanimate", "inert", "lackadaisical", "languid", "leaden", "lethargic", "listless", "sluggish", "torpid", "vegetating"]},
  {id:"284",words:["absorb", "engulf", "imbibe"]},
  {id:"285",words:["barefaced", "brazen", "shameless"]},
  {id:"286",words:["brazenness", "chutzpah", "contumely", "effrontery", "gall", "hubris", "impudence", "impudicity"]},
  {id:"287",words:["inflexible", "rigid", "stark", "stiff"]},
  {id:"288",words:["charlatan", "con man", "empiric", "faker", "fraud", "humbug", "imposter", "mountebank", "quack", "sharper", "swindler", "sham", "shaver", "shyster"]},
  {id:"289",words:["affirm", "assert", "aver", "avouch", "avow", "confess", "contend", "hold", "maintain", "predicate", "profess"]},
  {id:"290",words:["valid", "veritable", "verifiable", "authentic"]},
  {id:"291",words:["attest", "authenticate", "confirm", "corroborate", "ratify", "substantiate", "validate", "verify"]},
  {id:"292",words:["casual", "fitful", "incidental", "intermittent", "spasmodic", "sporadic"]},
  {id:"293",words:["carnal", "corporal", "corporeal", "fleshy", "somatic"]},
  {id:"294",words:["adipose", "bloated", "burly", "buxom", "corpulent", "obese", "plump", "portly", "pudgy", "squat", "stout", "tumid"]},
  {id:"295",words:["affable", "agreeable", "amiable", "amicable", "bland", "even-tempered", "gentle", "genial", "lenient", "mild", "suave"]},
  {id:"296",words:["bruise", "contusion", "lesion", "mayhem"]},
  {id:"297",words:["ransack", "rummage"]},
  {id:"298",words:["abbreviation", "apocope", "elision", "omission", "retrench", "syncopation"]},
  {id:"299",words:["abbreviate", "omit", "retrench", "syncopate"]},
  {id:"300",words:["cursory", "perfunctory", "slipshod"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "Ignominious":"수치스러운",
  "abbreviate":"생략하다",
  "abbreviation":"생략",
  "abhorrence":"혐오",
  "abhorrent":"몹시 싫은",
  "abnegate":"버리다; 자제하다",
  "abomination":"혐오",
  "absorb":"흡수하다",
  "acarpous":"열매 맺지 않는",
  "addendum":"(책의) 부록",
  "adipose":"지방이 많은",
  "adjunct":"부속물",
  "affable":"상냥한",
  "affected":"부자연한; 영향을 받은",
  "affirm":"단언하다",
  "aggrieve":"(사람을) 학대하다",
  "agreeable":"호감을 주는, 상냥한",
  "allocate":"할당하다",
  "allot":"분배하다",
  "amiable":"온후한, 친절한",
  "amicable":"우호적인, 친화적인",
  "amputate":"(손이나 발을) 자르다, 절단하다",
  "amulet":"부적",
  "antipathy":"반감",
  "apocope":"(발음에서) 어미음 탈락",
  "appendage":"부가물",
  "appendix":"부속물",
  "apportion":"할당하다",
  "appurtenance":"부속물, 종속물",
  "arid":"(토지가) 바싹 마른",
  "arrears":"체납금",
  "ashamed":"수줍어하는",
  "assert":"역설하다",
  "assign":"할당하다",
  "attest":"-을 증명하다",
  "authentic":"믿을 만한; 진정한",
  "authenticate":"진짜임을 증명하다",
  "aver":"주장하다; 진술하다",
  "aversion":"혐오감",
  "avouch":"-을 단언하다",
  "avow":"맹세하다",
  "balloon":"부풀다",
  "bare":"(비밀·마음 등을) 털어놓다, 폭로하다",
  "barefaced":"뻔뻔스러운",
  "barren":"(땅이) 불모의",
  "bashful":"부끄러워하는",
  "bending":"구부림",
  "biased":"편향된, 선입견이 있는",
  "bigoted":"편협한; 고집불통의",
  "bland":"(말·태도가) 온화한, 부드러운",
  "blasphemous":"불경한, 모독적인",
  "bleak":"황폐한, 쓸쓸한",
  "bloat":"부풀게 하다",
  "bloated":"거만한",
  "brazen":"철면피의",
  "brazenness":"낯 두꺼움",
  "breach":"파괴, 터진 곳, 불이행",
  "bruise":"타박상",
  "bulge":"부풀다",
  "burly":"굵고 튼튼한",
  "buxom":"포동포동한",
  "careless":"부주의한",
  "carnal":"육체의",
  "casual":"그때그때의, 일시적인",
  "cavity":"구멍",
  "charlatan":"협잡꾼; 돌팔이 의사",
  "charm":"부적",
  "chasm":"(지면·바위 따위의) 깊게 갈라진 틈",
  "chutzpah":"뻔뻔스러움, 후안무치",
  "cleft":"갈라진 틈",
  "cloister":"은둔시키다",
  "codicil":"유언장을 보충하는 목록",
  "con man":"사기꾼",
  "concomitant":"부수물",
  "confess":"(과실·죄를) 고백하다",
  "confirm":"확정하다",
  "contend":"주장하다; 다투다",
  "contrived":"인위적인",
  "contumely":"오만불손",
  "contusion":"타박상",
  "corporal":"육체의",
  "corporeal":"육체의; 물질적인",
  "corpulent":"뚱뚱한",
  "corroborate":"입증하다",
  "cove":"골짜기",
  "crack":"갈라진 금, 균열",
  "crevice":"갈라진 틈, 균열, 터진 곳",
  "cripple":"불구(절름발이)가 되게 하다",
  "crude":"투박한",
  "cursory":"조잡한, 엉성한",
  "default":"채무 불이행",
  "delinquent":"직무 태만의",
  "deprecate":"업신여기다; 반대하다",
  "derelict":"의무 태만의",
  "desolate":"황폐한; 황량한",
  "dilate":"팽창시키다",
  "disable":"불구로 만들다",
  "disaffirm":"부정하다; 취소하다",
  "disapprobate":"허가하지 않다",
  "disapprove":"탐탁잖아 하다; 반대하다",
  "disengage":"풀다, 분리하다",
  "disgruntle":"-에게 불만을 품게 하다.",
  "disgust":"(심한) 싫증, 혐오",
  "disgusting":"역겨운",
  "dismember":"-의 손발을 자르다",
  "disown":"의절하다",
  "dormant":"동면의, 휴지의",
  "effrontery":"뻔뻔스러움",
  "elision":"발음 생략",
  "empiric":"돌팔이 의사; 경험주의자",
  "engulf":"삼켜버리다; 몰두케 하다",
  "even-tempered":"마음이 평정한",
  "exile":"추방하다, 귀양 보내다",
  "faker":"날조자, 협잡꾼",
  "far-fetched":"부자연스러운",
  "fecund":"(땅이) 비옥한",
  "fertile":"(땅이) 비옥한; 다산의",
  "fission":"분열",
  "fissure":"터진 자리, 틈, 균열",
  "fitful":"발작적인, 일정치 않은",
  "fleshy":"살의",
  "flexible":"구부리기 쉬운; 융통성 있는",
  "forlorn":"버려진, 버림받은",
  "fragment":"분해하다",
  "fraud":"사기꾼",
  "fructuous":"열매 맺는, 다산적인",
  "fruitful":"비옥한",
  "fulsome":"칭찬이 지나쳐서 불쾌한",
  "gainsay":"반대하다",
  "gall":"성나게 하다",
  "genial":"(사람이) 마음이 맞는",
  "gentle":"가벼운, 순한",
  "grieve":"슬프게 하다",
  "grouch":"불평을 하다",
  "grouse":"불평하다, 투덜대다",
  "growl":"투덜거리다; 으르렁거리다",
  "grumble":"불평하다",
  "grump":"불평하다",
  "grunt":"돼지의 울음소리",
  "hamstring":"불구를 만들다",
  "haplessness":"불행함",
  "hazy":"모호한",
  "heedless":"부주의한",
  "hiatus":"틈, 누락, 휴회",
  "hold":"주장하다, 생각하다",
  "hubris":"자만심",
  "humbug":"사기꾼",
  "ignoble":"비열한",
  "imbibe":"(공기·연기 등을) 빨아들이다",
  "immobile":"고정된, 움직이지 않는",
  "impart":"나누어 주다",
  "impious":"불신앙의, 경건치 않은",
  "imposter":"협잡꾼",
  "impoverished":"가난해진; 힘을 잃은",
  "impudence":"뻔뻔스러움",
  "impudicity":"파렴치",
  "inadvertent":"부주의한, 태만한",
  "inanimate":"생명 없는, 무생물의",
  "inattentive":"부주의한",
  "incapacitate":"무능력하게 하다",
  "incidental":"임시의, 우연의",
  "inert":"(육체적, 정신적으로) 활발하지 못한",
  "infertile":"(땅이) 비옥하지 않은; 불모의",
  "inflexible":"구부러지지 않는, 완고한",
  "iniquitous":"부정한, 불법의",
  "iniquity":"부정, 불법",
  "insolvent":"지급불능의",
  "insulate":"절연(단열, 방음)하다; 격리하다",
  "intermittent":"간헐적인",
  "interstice":"갈라진 틈",
  "irreverent":"불경한, 불손한",
  "isolate":"고립시키다, 분리하다",
  "jaundiced":"편견을 가진",
  "labored":"억지의",
  "lackadaisical":"열의 없는",
  "languid":"활기 없는",
  "lax":"해이한",
  "leaden":"무기력한; 납빛의",
  "lenient":"관대한",
  "lesion":"손상",
  "lethargic":"노곤한, 무기력한",
  "liability":"(개인·회사의) 부채",
  "limber":"유연한; 재빠른",
  "lissom":"유연한, 부드러운",
  "lissome":"유연한, 부드러운",
  "listless":"무관심한, 게으른",
  "lithe":"나긋나긋한; 유연한",
  "loathing":"몹시 싫어함",
  "lone wolf":"독불장군",
  "loner":"단독 행동하는 사람",
  "maim":"불구가 되게 하다",
  "maintain":"주장하다, 단언하다",
  "malaise":"(도덕적·사회적 퇴락에 대한) 막연한 불안",
  "mannered":"자연스럽지 못한",
  "maverick":"이단자",
  "mayhem":"신체 상해",
  "meager":"빈약한",
  "mete":"(형벌·보수 따위를) 할당하다",
  "mild":"(음식·음료가) 부드러운, 자극성이 없는",
  "misadventure":"불운",
  "mischance":"불운, 불행",
  "mishap":"불운한 일",
  "mountebank":"사기꾼; 돌팔이 의사[약사]",
  "murky":"(표현 따위가) 애매한",
  "mutilate":"(수족 따위를) 절단하다",
  "naughty":"사악한; 장난스러운",
  "nausea":"메스꺼움",
  "nauseate":"구역질나게 만들다",
  "nebulous":"애매한",
  "negligent":"소홀한",
  "nonconformist":"비(非)순응주의자",
  "obese":"살찐",
  "obligation":"채무, 채권",
  "odium":"증오",
  "omission":"생략",
  "omit":"빼다, 생략하다",
  "opaque":"불투명한",
  "outcast":"부랑자",
  "paralyze":"마비시키다; 무력하게 만들다",
  "pariah":"(사회에서) 추방당한 사람",
  "partial":"불공평한, 편파적인",
  "perfunctory":"형식적인, 마지못한",
  "pique":"화, 불쾌",
  "pit":"구멍(을 파다)",
  "pliable":"휘기 쉬운; 나긋나긋한",
  "pliant":"나긋한",
  "plump":"부드럽고 풍만한",
  "portly":"살찐",
  "predicate":"단언하다",
  "prejudiced":"편견을 가진, 편파적인",
  "procrustean":"지나치게 획일적인",
  "productive":"풍요의, 비옥한",
  "profane":"신성을 더럽히다; 신성 모독의",
  "profess":"공언[주장]하다; -인 척 하다",
  "prolific":"비옥한; 다작의",
  "pudgy":"부피(무게)가 있는",
  "quack":"돌팔이 의사",
  "ramble":"두서없이 말하다; (특히 전원 속을) 거닐다",
  "ransack":"뒤지다",
  "ratify":"비준하다",
  "recant":"(신앙·주장 등을) 바꾸다, 취소하다",
  "recusant":"복종 거부자",
  "regenerate":"갱생시키다, 재건하다, 회생시키다",
  "rehabilitate":"재활 치료를 하다",
  "remiss":"태만한",
  "repeal":"무효로 하다, 폐지하다",
  "repel":"격퇴하다",
  "repine":"불평하다",
  "reprobate":"비난하다; 타락한; 방탕아",
  "repugnance":"혐오",
  "repulse":"물리치다",
  "repulsion":"퇴짜; 거절",
  "rescind":"(법률·행위 등을) 폐지하다",
  "resentment":"노함, 분개",
  "resurge":"부활하다, 재생하다",
  "resurrect":"(사상·관례 등을) 부활시키다",
  "resuscitate":"(과거의 것을) 부흥하다",
  "retract":"(앞서 한 말·약속·명령 등을) 철회하다",
  "retrench":"삭제하다",
  "retrieve":"만회하다",
  "revoke":"(명령·약속·특권 따위를) 무효로 하다",
  "revolt":"불쾌함을 갖게 하다",
  "revulsion":"(감정의 격변) 혐오; 불쾌",
  "rift":"갈라진 틈",
  "rigid":"굳은, 완고한",
  "rummage":"샅샅이 뒤지다",
  "sacrilegious":"(신성) 모독의",
  "scant":"불충분한",
  "scanty":"부족한",
  "scarce":"(음식물·돈·등이) 부족한",
  "schism":"(단체의) 분리, 분열",
  "scurvy":"상스러운; 괴혈병",
  "seclude":"(사람·장소 따위를) 분리하다",
  "segregate":"격리하다",
  "separate":"불화하게 하다",
  "sequester":"격리시키다",
  "sham":"사기꾼",
  "shamefaced":"숫기가 없는",
  "shameless":"부끄러움을 모르는",
  "sharper":"사기꾼",
  "shaver":"사기꾼; 이발사",
  "shy":"부끄럼 타는",
  "shyster":"사기꾼; 악덕 변호사",
  "sicken":"-에 구역질나게 하다",
  "slipshod":"부주의한",
  "sluggish":"게으른",
  "snivel":"칭얼거리다",
  "somatic":"신체의",
  "sparse":"(인구 따위가) 빈약한",
  "spasmodic":"발작적인",
  "sporadic":"산발적인",
  "squat":"웅크리다; 낮고 폭이 좁은; 땅딸막한",
  "stark":"삭막한",
  "stereotyped":"정형화된",
  "sterile":"흉작의; 자식을 못 낳는, 불임의",
  "stiff":"뻣뻣한",
  "stout":"살찐, 뚱뚱한",
  "strained":"일부러 꾸민, 부자연한",
  "suave":"입에 순한, 자극성이 없는",
  "substantiate":"실증하다",
  "supine":"게으른, 무관심한",
  "supple":"유연한; 순응성이 있는",
  "swindler":"사기꾼",
  "syncopate":"중략하다",
  "syncopation":"중략",
  "talisman":"부적",
  "tendentious":"편향의",
  "torpid":"움직이지 않는, 마비된",
  "tumid":"과장된, 부어오른",
  "turbid":"흐린",
  "turpitude":"간악, 비열(한 행위)",
  "umbrage":"불쾌, 노여움",
  "unknowing":"자신도 알아채지 못하는",
  "unnatural":"일부러 꾸민 듯한",
  "unproductive":"불모의; (-을) 생산하지 않는",
  "unwitting":"자신도 모르는",
  "unwittingly":"부지불식간에",
  "vague":"막연한, 애매한",
  "valid":"근거가 확실한; 유효한",
  "validate":"입증하다",
  "vegetating":"(식물처럼) 활기 없는 생활을 하는",
  "verifiable":"입증할 수 있는",
  "verify":"확인하다",
  "veritable":"진정한",
  "vile":"비열한",
  "vileness":"비열함",
  "villainous":"악한 같은",
  "villainy":"나쁜 짓, 악행",
  "waste":"황폐케 하다",
  "wean":"(나쁜 버릇 따위를) 단념시키다; 젖을 떼다",
  "whine":"(개 따위가) 낑낑거리다",
  "wicked":"악한"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "251":"부끄럼 타는",
  "252":"부드러운, 유연한, 구부리기 쉬운",
  "253":"부랑아, 추방자",
  "254":"부속물, 종속물, 부록",
  "255":"부인하다, 부정하다",
  "256":"부자연스러운, 억지로 짜 맞춘",
  "258":"부족한, 빈약한",
  "259":"부주의한, 해이한",
  "260":"부지불식간의(에), 우연한",
  "261":"부풀리다",
  "263":"부활시키다, 재생시키다",
  "264":"분리하다, 떼어놓다, 격리시키다",
  "265":"분배하다",
  "266":"분열, 틈",
  "267":"불경스러운, 신성모독의",
  "268":"불공정한, 편파적인, 편견이 있는",
  "269":"불구로 만들다",
  "270":"불모의, 황폐한, 쓸모없는, 완전히 결핍된",
  "272":"불쾌감",
  "273":"불쾌하게 하다",
  "274":"불쾌한, 싫은",
  "275":"불평하게 하다, 불만을 품게 하다",
  "276":"불평하다",
  "277":"불투명한, 흐린, 불명료한, 모호한",
  "278":"비 순응주의자, 독불장군",
  "279":"비열(한 행동), 사악(한 행동)",
  "280":"비열한, 사악한",
  "281":"비옥한",
  "282":"비천한, 비열한",
  "283":"비활동적인, 힘없는, 동작(반응)이 느린",
  "284":"빨아들이다",
  "285":"뻔뻔스러운, 철면피의, 후안무치의",
  "286":"뻔뻔스러움, 철면피, 후안무치",
  "287":"뻣뻣한, 경직된",
  "288":"사기꾼, 가짜 전문가",
  "289":"사실이라고 주장하다, 단언하다, 공표하다",
  "290":"사실인, 옳은",
  "291":"사실임을 확인하다, 입증하다, 실증하다",
  "292":"산발적인, 단속적인",
  "293":"살의, 육체의, 신체의",
  "294":"살찐",
  "295":"상냥한, 온화한",
  "296":"상해",
  "297":"샅샅이 뒤지다",
  "298":"생략",
  "299":"생략하다",
  "300":"서둘러서 엉성하게 한"
});
