// LOGIC TREE V502 — Categories 201-250
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"201",words:["arid", "muggy", "sultry", "sweltering", "torrid"]},
  {id:"202",words:["abrupt", "bluff", "blunt", "brusque", "coarse", "cross", "curt", "glum", "gruff", "harsh", "point-blank", "unaffable", "saturnine", "surly", "sullen", "sulky"]},
  {id:"203",words:["affront", "chutzpa", "chutzpah", "contumely", "effrontery", "hubris", "insolence", "presumption", "presumptuousness", "indecorum", "impropriety"]},
  {id:"204",words:["boorish", "churlish", "contumelious", "haughty", "imperious", "impertinent", "impolite", "improper", "indecent", "indecorous", "insolent", "loutish", "presumptuous", "unseemly"]},
  {id:"205",words:["appalling", "diabolical", "dread", "dreadful", "eerie", "fearful", "fearsome", "fell", "fiendish", "gaunt", "ghastly", "grim", "grisly", "gruesome", "hideous", "horrendous", "lurid", "macabre", "morbid"]},
  {id:"206",words:["exuberant", "lush", "luxuriant", "profuse", "rank"]},
  {id:"207",words:["implicit", "unspoken", "tacit"]},
  {id:"208",words:["bury", "earth", "inhume"]},
  {id:"209",words:["auction", "barter", "hawk", "peddle", "tout"]},
  {id:"210",words:["cloy", "glut", "jade", "sate", "satiate", "stoke", "surfeit", "weary"]},
  {id:"211",words:["blase", "cloyed", "surfeited", "satiated", "sated"]},
  {id:"212",words:["oily", "slick", "slimy", "unctuous"]},
  {id:"213",words:["bon vivant", "gourmet", "gourmand", "gormand"]},
  {id:"214",words:["amuck", "berserk", "irate"]},
  {id:"215",words:["rampage", "rage"]},
  {id:"216",words:["daffy", "delirious", "demented", "deranged", "distracted", "distrait", "distraught", "insane"]},
  {id:"217",words:["agile", "keen", "nimble", "spry", "sprightly"]},
  {id:"218",words:["aquatic", "marine", "maritime", "nautical", "naval", "pelagian", "pelagic"]},
  {id:"219",words:["dolt", "dope", "dullard", "dunce", "goof", "gook", "goon", "idiot", "imbecile", "moron", "muggins", "oaf", "patch", "simpleton", "zany"]},
  {id:"220",words:["crass", "cretinous", "doltish", "dopey", "fatuous", "hebetudinous", "idiotic", "imbecilic", "inane", "moronic", "vacuous"]},
  {id:"221",words:["amphigory", "balderdash", "drivel", "folderole", "rig(a)marole", "fandango", "fandangle", "folly"]},
  {id:"222",words:["contradict", "demur", "deny", "deprecate", "disapprobate", "disapprove", "expostulate", "gainsay", "object", "oppose", "protest", "remonstrate", "reprobate", "repugn"]},
  {id:"223",words:["revolt", "rebellion", "riot", "sedition", "insurrection", "insurrectionist"]},
  {id:"224",words:["revolt", "rebel", "subvert", "insurrectionize"]},
  {id:"225",words:["effuse", "eject", "emanate", "emit", "eructate", "exude", "erupt", "gush", "radiate", "spew", "vomit"]},
  {id:"226",words:["beget", "engender", "procreate", "spawn", "initiate", "create"]},
  {id:"227",words:["burnished", "effulgent", "flamboyant", "lustrous", "radiant", "refulgent", "resplendent", "incandescent", "opalescent", "fluorescent"]},
  {id:"228",words:["errant", "itinerant", "migratory", "nomadic", "peripatetic", "roving", "vagrant", "wandering"]},
  {id:"229",words:["immoderate", "intemperate", "incontinent", "degenerate", "dissolute", "indulging", "reprobate", "sybarite", "unrestrained", "unguarded"]},
  {id:"230",words:["circumvent", "debar", "encumber", "foil"]},
  {id:"231",words:["disloyalty", "double-dealing", "infidelity", "treachery", "betrayal", "duplicity", "perfidy", "treason", "recreancy", "tergiversation"]},
  {id:"232",words:["strut", "buttress", "prop", "girder", "beam"]},
  {id:"233",words:["dazzling", "effulgent", "lustrous", "refulgent", "resplendent"]},
  {id:"234",words:["blaze", "glint", "glisten", "glow", "radiate", "resplend", "scintillate", "spangle", "opalesce", "incandesce", "luminesce", "fluoresce"]},
  {id:"235",words:["burgeon", "effloresce", "flourish", "mushroom", "proliferate", "prosper", "thrive", "wax"]},
  {id:"236",words:["bastinado", "comeuppance", "gruel", "lash", "nemesis", "pillory", "retribution", "scourge", "whip"]},
  {id:"237",words:["deluge", "flood", "inundation", "spate"]},
  {id:"238",words:["deluge", "flood", "inundate"]},
  {id:"239",words:["affection", "caprice", "fad", "humor", "maggot", "mood", "temper", "vagary", "whim", "whimsy"]},
  {id:"240",words:["capricious", "changeable", "fickle", "mercurial", "volatile", "whimsical"]},
  {id:"241",words:["apostate", "pervert", "betrayer", "defector", "deserter", "heretic", "quisling", "renegade", "slacker", "traitor", "turncoat"]},
  {id:"242",words:["mutate", "transmute", "metamorphose", "alter", "convert", "calcify", "petrify", "ossify", "liquefy"]},
  {id:"243",words:["ungainly", "uncouth", "graceless", "seamy", "unbecomingly"]},
  {id:"244",words:["detain", "pigeonhole", "shelve", "shunt", "table"]},
  {id:"245",words:["nemesis", "reprisal", "requite", "requital", "retaliation", "retortion", "retorsion", "retribution", "revanche", "revenge", "vengeance"]},
  {id:"246",words:["avenge", "requite", "retaliate", "retort", "retribute", "revenge", "reciprocate"]},
  {id:"247",words:["atone", "expiate", "reciprocate", "recompense", "recoup", "reimburse", "remunerate", "render", "repair", "requite", "retrieve"]},
  {id:"248",words:["commonplace", "conventional", "mediocre", "ordinary", "pedestrian", "prosaic", "quotidian", "run-of-the-mill", "stock"]},
  {id:"249",words:["aegis", "egis", "custody", "guardianship"]},
  {id:"250",words:["acquiescent", "amenable", "compliant", "governable", "malleable", "manageable", "meek", "obedient", "submissive", "supple", "tractable"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abrupt":"퉁명스러운",
  "acquiescent":"(수동적으로) 묵묵히 따르는",
  "aegis":"보호",
  "affection":"성질; 애정",
  "affront":"과감히 맞서다; 모욕하다; 모욕",
  "agile":"기민한; 날렵한",
  "alter":"변하다",
  "amenable":"(충고 등에) 순종하는",
  "amphigory":"무의미하고 우스운 글",
  "amuck":"미친 듯이 날뛰는",
  "apostate":"배교자",
  "appalling":"섬뜩하게 하는",
  "aquatic":"물속에서 자라는",
  "arid":"(토지가) 바싹 마른",
  "atone":"죄 값을 치르다, 죄 값을 보상하다",
  "auction":"경매하다",
  "avenge":"(사건에 대해) 복수를 하다",
  "balderdash":"같잖은 소리",
  "barter":"교환하다",
  "bastinado":"태형에 처하다",
  "beam":"대들보, 도리",
  "beget":"(어떤 결과를) 부르다, 야기하다",
  "berserk":"(화가 나서) 미쳐 날뛰는",
  "betrayal":"배신",
  "betrayer":"배신자",
  "blase":"환락에 물린",
  "blaze":"눈부시게 빛나다",
  "bluff":"[포커] (패가 센 것처럼 꾸며 상대를) 속이다",
  "blunt":"퉁명스러운",
  "bon vivant":"미식가; 유쾌한 사람",
  "boorish":"야비한; 촌스러운",
  "brusque":"무뚝뚝한",
  "burgeon":"급성장하다",
  "burnished":"닦은",
  "bury":"매장하다; 감추다",
  "buttress":"지지하다, 보강하다",
  "calcify":"석회석(limestone)으로 만들다, 경화시키다",
  "caprice":"변덕",
  "capricious":"변덕스러운",
  "changeable":"변하기 쉬운",
  "churlish":"예절 없는",
  "chutzpa":"뻔뻔스러움, 후안무치",
  "chutzpah":"뻔뻔스러움, 후안무치",
  "circumvent":"함정에 빠뜨리다; 피해가다",
  "cloy":"(쾌락·사치 등에) 넌더리나게 만들다",
  "cloyed":"물린",
  "coarse":"거친",
  "comeuppance":"인과응보, 마땅한 벌",
  "commonplace":"평범한, 개성이 없는",
  "compliant":"남이 시키는 대로 하는",
  "contradict":"부정하다; 반박하다",
  "contumelious":"오만불손한",
  "contumely":"오만불손",
  "conventional":"진부한, 전통적인",
  "convert":"개종시키다",
  "crass":"우둔한, 매우 어리석은",
  "create":"창조하다",
  "cretinous":"바보 같은",
  "cross":"까다로운, 성마른",
  "curt":"퉁명스러운",
  "custody":"구금",
  "daffy":"미친; 어리석은",
  "dazzling":"눈부신, 현혹적인",
  "debar":"(- 하는 것을) 방해하다",
  "defector":"배반자",
  "degenerate":"약화되다",
  "delirious":"(일시적인) 정신 착란한",
  "deluge":"쇄도; 폭우",
  "demented":"발광한",
  "demur":"이의를 제기하다",
  "deny":"부인하다",
  "deprecate":"업신여기다; 반대하다",
  "deranged":"혼란된, 미친",
  "deserter":"탈영병",
  "detain":"붙들어 두다, 구금하다",
  "diabolical":"악마의",
  "disapprobate":"허가하지 않다",
  "disapprove":"탐탁잖아 하다; 반대하다",
  "disloyalty":"불충, 불성실",
  "dissolute":"방종한",
  "distracted":"마음이 산란한",
  "distrait":"(불안·근심으로) 멍한",
  "distraught":"(흥분해서) 완전히 제정신이 아닌",
  "dolt":"멍청이",
  "doltish":"멍청한",
  "dope":"얼간이; 마약",
  "dopey":"바보 같은",
  "double-dealing":"표리 있는 언행, 배신",
  "dread":"무서운",
  "dreadful":"무시무시한",
  "drivel":"쓸데없는 말",
  "dullard":"멍청이",
  "dunce":"열등생, 저능아",
  "duplicity":"이중성, 표리부동",
  "earth":"묻다; 감추다",
  "eerie":"섬뜩한",
  "effloresce":"번영하다",
  "effrontery":"뻔뻔스러움",
  "effulgent":"빛나는",
  "effuse":"발산시키다",
  "egis":"보호",
  "eject":"내보내다",
  "emanate":"(어떤 느낌 특질 등을) 발하다",
  "emit":"(빛 열 가스 소리 등을) 내다",
  "encumber":"방해하다",
  "engender":"(상태 등을) 발생시키다",
  "errant":"(행동이) 잘못된",
  "eructate":"-을 분출하다",
  "erupt":"(화산이) 분출하다",
  "expiate":"죄 값을 치르다, 죄 값을 보상하다",
  "expostulate":"-에 대해 이의를 제기하다",
  "exuberant":"풍부한",
  "exude":"(특정한 느낌 등이) 물씬 풍기다",
  "fad":"일시적 유행",
  "fandangle":"어리석은 짓",
  "fandango":"어리석은 행위",
  "fatuous":"어리석은",
  "fearful":"무서운",
  "fearsome":"(얼굴 등이) 무서운",
  "fell":"잔인한",
  "fickle":"마음이 잘 변하는",
  "fiendish":"귀신같은; 잔인한",
  "flamboyant":"현란한",
  "flood":"범람, 쇄도",
  "flourish":"번창하다",
  "fluoresce":"형광을 내다",
  "fluorescent":"형광을 내는",
  "foil":"(특히 불법적인 것을) 좌절시키다",
  "folderole":"헛소리",
  "folly":"어리석은 행동",
  "gainsay":"반대하다",
  "gaunt":"기분이 섬뜩한",
  "ghastly":"무서운, 소름끼치는",
  "girder":"대들보",
  "glint":"(작게) 반짝거리다",
  "glisten":"젖은 것이 반짝거리다",
  "glow":"특히 뜨거운 것이 계속 은은히 빛나다",
  "glum":"뚱한, 음울한",
  "glut":"차고 넘침",
  "goof":"바보",
  "gook":"황색인종 (모욕적인 말)",
  "goon":"바보, 멍청이",
  "gormand":"대식가",
  "gourmand":"대식가",
  "gourmet":"미식가",
  "governable":"순응성이 있는",
  "graceless":"품위 없는",
  "grim":"소름끼치는",
  "grisly":"섬뜩한",
  "gruel":"호되게 벌주다",
  "gruesome":"무시무시한",
  "gruff":"(소리·목소리가) 굵고 탁한",
  "guardianship":"후견인의 보호",
  "gush":"(액체가) 솟구치다",
  "harsh":"가혹한, 거친",
  "haughty":"거만한",
  "hawk":"거리에서 큰 소리로 외치며 팔다",
  "hebetudinous":"우둔한; 무기력한",
  "heretic":"이단자",
  "hideous":"섬뜩한",
  "horrendous":"무서운",
  "hubris":"자만심",
  "humor":"-의 비위를 맞추다",
  "idiot":"천치, 바보",
  "idiotic":"바보 같은",
  "imbecile":"저능한",
  "imbecilic":"어리석은",
  "immoderate":"무절제한",
  "imperious":"고압적인",
  "impertinent":"무례한",
  "implicit":"암시적인",
  "impolite":"무례한, 버릇없는",
  "improper":"부적당한",
  "impropriety":"부도덕",
  "inane":"어리석은; 무의미한",
  "incandesce":"백열광을 내다",
  "incandescent":"백열광을 내는",
  "incontinent":"절제 없는",
  "indecent":"버릇없는",
  "indecorous":"버릇없는",
  "indecorum":"버릇없음",
  "indulging":"탐닉하는",
  "infidelity":"(배우자나 애인에 대한) 부정",
  "inhume":"매장하다; 감추다",
  "initiate":"시작하다, 개시하다",
  "insane":"정신 이상의",
  "insolence":"무례함",
  "insolent":"버릇없는",
  "insurrection":"반란",
  "insurrectionist":"폭동 선동자",
  "insurrectionize":"폭동을 일으키다",
  "intemperate":"무절제한",
  "inundate":"-가 쇄도하다",
  "inundation":"범람, 충만",
  "irate":"성난",
  "itinerant":"떠돌아다니는",
  "jade":"녹초가 되게 하다",
  "keen":"날카로운, 예리한",
  "lash":"몹시 꾸짖다",
  "liquefy":"액(liquid)화시키다",
  "loutish":"버릇없는; 촌뜨기 같은",
  "luminesce":"냉광을 발하다",
  "lurid":"소름끼치는",
  "lush":"무성한",
  "lustrous":"윤기가 흐르는",
  "luxuriant":"번성한",
  "macabre":"섬뜩한",
  "maggot":"변덕; 구더기",
  "malleable":"펴 늘일 수 있는; 유순한",
  "manageable":"다루기 쉬운",
  "marine":"바다의",
  "maritime":"바다의, 해양의",
  "mediocre":"보통의",
  "meek":"온순한",
  "mercurial":"민활한; 변덕스러운",
  "metamorphose":"변형시키다",
  "migratory":"이주하는",
  "mood":"(일시적인) 기분",
  "morbid":"섬뜩한; 병적인",
  "moron":"멍텅구리",
  "moronic":"저능아의",
  "muggins":"얼간이",
  "muggy":"무더운",
  "mushroom":"우후죽순처럼 늘어나다",
  "mutate":"돌연변이가 되다",
  "nautical":"선박의; 해상의",
  "naval":"해군의",
  "nemesis":"응당 받아야 하는 벌",
  "nimble":"(동작이) 빠른",
  "nomadic":"유목의",
  "oaf":"백치, 바보",
  "obedient":"순종하는",
  "object":"반대하다",
  "oily":"기름기가 함유된",
  "opalesce":"단백광을 내다",
  "opalescent":"우윳빛을 내는",
  "oppose":"(계획·정책 등에) 반대하다",
  "ordinary":"평범한",
  "ossify":"뼈로 만들다, 경화시키다",
  "patch":"바보, 얼간이",
  "peddle":"행상하다",
  "pedestrian":"단조로운; 보행자",
  "pelagian":"심해의",
  "pelagic":"원양의",
  "perfidy":"불신",
  "peripatetic":"이동해 다니는",
  "pervert":"배교자",
  "petrify":"돌로 만들다, 경화시키다",
  "pigeonhole":"정리함에 두고 뒤로 미루다",
  "pillory":"(남들이 보는데서) 강력히 비판하다",
  "point-blank":"퉁명스럽고 직설적인",
  "presumption":"주제넘음",
  "presumptuous":"주제넘은",
  "presumptuousness":"주제넘음, 건방짐",
  "procreate":"자손을 낳다",
  "profuse":"풍부한",
  "proliferate":"급격히 늘다",
  "prop":"-을 지지하다, 보강하다; 받침대",
  "prosaic":"단조로운",
  "prosper":"번영하다",
  "protest":"항의하다",
  "quisling":"부역자",
  "quotidian":"매일의, 흔해빠진",
  "radiant":"빛나는",
  "radiate":"(사람이 어떤 검정 특질 등을) 내뿜다",
  "rage":"격노",
  "rampage":"(성나서) 날뛰기",
  "rank":"무성한, 울창한",
  "rebel":"반란을 일으키다",
  "rebellion":"반란",
  "reciprocate":"보복하다",
  "recompense":"보상하다",
  "recoup":"-에게 보상하다",
  "recreancy":"불성실, 변절",
  "refulgent":"환히 빛나는",
  "reimburse":"(빚 따위를) 갚다",
  "remonstrate":"정식으로 항의하다",
  "remunerate":"보상하다; 보수를 주다",
  "render":"-에 보답하다",
  "renegade":"변절자",
  "repair":"(부정·죄 등을) 보상하다",
  "reprisal":"앙갚음, 보복",
  "reprobate":"비난하다; 타락한; 방탕아",
  "repugn":"-에 반대하다",
  "requital":"보복",
  "requite":"앙갚음하다",
  "resplend":"빛나다, 반짝이다",
  "resplendent":"빛나는",
  "retaliate":"보복하다",
  "retaliation":"보복",
  "retorsion":"(높은 관세에 의한) 보복",
  "retort":"(비난·모욕 따위에) 보복하다",
  "retortion":"(높은 관세에 의한) 보복",
  "retribute":"복수하다",
  "retribution":"강력한 응징",
  "retrieve":"만회하다",
  "revanche":"복수",
  "revenge":"원수를 갚다",
  "revolt":"불쾌함을 갖게 하다",
  "rig(a)marole":"횡설수설; (불필요하게 길고) 복잡한 절차",
  "riot":"폭동",
  "roving":"방랑하는",
  "run-of-the-mill":"흔히 있는",
  "sate":"물리게 하다",
  "sated":"-에 물린",
  "satiate":"물리게 하다",
  "satiated":"충분히 만족한",
  "saturnine":"무뚝뚝한; 음침한",
  "scintillate":"불꽃을 내다",
  "scourge":"징계하다",
  "seamy":"보기 흉한, 지저분한",
  "sedition":"폭동, 선동",
  "shelve":"(해결 따위를) 미루다",
  "shunt":"(기차의) 선로를 바꾸다; 이동시키다",
  "simpleton":"얼간이, 숙맥",
  "slacker":"책임 회피자; 게으름뱅이",
  "slick":"미끄러운; 겉만 번드르르한",
  "slimy":"(더럽고) 끈적끈적한",
  "spangle":"금속 조각으로 장식하다",
  "spate":"대량, 다수; 홍수",
  "spawn":"(어떤 결과 상황을) 낳다",
  "spew":"뿜어져 나오다",
  "sprightly":"기운찬, 쾌활한",
  "spry":"기운찬",
  "stock":"표준의, 평범한; 재고의",
  "stoke":"실컷 먹다",
  "strut":"뽐내며 걷다",
  "submissive":"복종하는",
  "subvert":"(체제를) 전복시키다",
  "sulky":"뾰루퉁한",
  "sultry":"무더운, 후덥지근한",
  "sullen":"언짢은",
  "supple":"유연한; 순응성이 있는",
  "surfeit":"과다",
  "surfeited":"과식한, 물린",
  "surly":"퉁명스러운",
  "sweltering":"더위 먹은",
  "sybarite":"사치와 향락을 일삼는 무리",
  "table":"(의안을) 무기 연기하다; 묵살하다",
  "tacit":"무언의",
  "temper":"기질, 성질",
  "tergiversation":"속임, 변절",
  "thrive":"번창하다",
  "torrid":"몹시 더운",
  "tout":"강권하다; 격찬하다",
  "tractable":"다루기 쉬운",
  "traitor":"배반자",
  "transmute":"변형시키다",
  "treachery":"배반",
  "treason":"반역죄",
  "turncoat":"변절자",
  "unaffable":"퉁명스러운",
  "unbecomingly":"어울리지 않게; 온당치 못하게",
  "uncouth":"투박한; 상스러운",
  "unctuous":"기름 같은; 상냥한",
  "ungainly":"어색한",
  "unguarded":"언행을 조심하지 않는, 경솔한",
  "unrestrained":"(언행 등이) 억제되지 않은",
  "unseemly":"꼴사나운; 꼴사납게",
  "unspoken":"입 밖에 내지 않는",
  "vacuous":"멍청한",
  "vagary":"변덕",
  "vagrant":"부랑자",
  "vengeance":"원수 갚기",
  "volatile":"변하기 쉬운",
  "vomit":"토하다",
  "wandering":"(정처 없이) 돌아다니는",
  "wax":"증대하다",
  "weary":"피로한, 지쳐 있는",
  "whim":"잘 변하는 마음",
  "whimsical":"마음이 잘 변하는",
  "whimsy":"잘 변하는 마음",
  "whip":"채찍질하다",
  "zany":"(재미있게) 엉뚱한"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "201":"무더운",
  "202":"무뚝뚝한, 퉁명스러운",
  "203":"무례, 모욕",
  "204":"무례한",
  "205":"무서운, 무시무시한",
  "206":"무성한, 울창한, 우거진, 풍부한",
  "207":"묵시적인",
  "208":"묻다, 감추다",
  "209":"물건을 파는 여러 유형",
  "210":"물리게 하다, 싫증나게 하다",
  "211":"물린, 싫증이 난",
  "212":"미끈거리는",
  "213":"미식가, 식도락가",
  "214":"미쳐 날뛰는",
  "215":"미쳐 날뛰다",
  "216":"미친, 실성한",
  "217":"민첩한, 기운찬",
  "218":"바다의",
  "219":"바보",
  "220":"바보 같은, 어리석은",
  "221":"바보 같은 말, 행동",
  "222":"반대하다, 이의를 제기하다",
  "223":"반란, 폭동 → 반란자",
  "224":"반란을 일으키다",
  "225":"(빛, 열, 냄새 따위를) 발산(분출)하다, 스며 나오다",
  "226":"발생시키다",
  "227":"밝게 빛나는",
  "228":"방랑하는, 이리저리 떠돌아다니는",
  "229":"방탕한, 무절제한, 쾌락에 탐닉하는",
  "230":"방해하다, 좌절시키다",
  "231":"배신, 불충, 불성실",
  "232":"버팀목",
  "233":"번쩍이는, 빛을 내는",
  "234":"번쩍번쩍 빛을 내다",
  "235":"번영하다, 번성하다, 융성하다",
  "236":"벌(하다)",
  "237":"범람, 쇄도",
  "238":"범람하다, 쇄도하다",
  "239":"변덕",
  "240":"변덕스러운, 변화하기 쉬운",
  "241":"변절자",
  "242":"변화시키다, 변형시키다, 경화(액화, 기화)시키다",
  "243":"(춤 따위의 동작이) 어색한, 보기 흉한",
  "244":"보류하다",
  "245":"보복, 복수",
  "246":"보복하다, 복수하다",
  "247":"보상하다, 보답하다",
  "248":"보통의, 일상의, 그저 그런, 평범한",
  "249":"보호",
  "250":"복종하는, 다루기 쉬운"
});
