// LOGIC TREE V502 — Categories 201-300 (manually verified)
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.categories.push(
  {id:"201",words:["arid", "muggy", "sulky", "sweltering", "torrid"]},
  {id:"202",words:["abrupt", "bluff", "blunt", "brusk", "brusque", "coarse", "cross", "curt", "glum", "gruff", "harsh", "point-blank", "unaffable", "saturnine", "surly", "sullen", "sulky"]},
  {id:"203",words:["affront", "chutzpa", "chutzpah", "contumely", "effrontery", "hubris", "insolence", "presumption", "presumptuousness", "indecorum", "impropriety"]},
  {id:"204",words:["boorish", "churlish", "contumelious", "haughty", "imperious", "impertinent", "impolite", "improper", "indecent", "indecorous", "insolent", "loutish", "presumptuous", "unseemly"]},
  {id:"205",words:["appalling", "diabolical", "dread", "dreadful", "eerie", "fearful", "fearsome", "fell", "fiendish", "gaunt", "ghastly", "grim", "grisly", "gruesome", "hideous", "horrendous", "lurid", "macabre", "morbid"]},
  {id:"206",words:["exuberant", "lush", "luxuriant", "profuse", "rank"]},
  {id:"207",words:["implicit", "unspoken", "tacit"]},
  {id:"208",words:["bury", "earth", "inhume"]},
  {id:"209",words:["auction", "barter", "hawk", "peddle", "tout"]},
  {id:"210",words:["cloy", "glut", "jade", "sate", "satiate", "stoke", "surfeit", "weary"]},
  {id:"211",words:["blase", "cloyed", "surfeited", "satiated", "sated"]},
  {id:"212",words:["oily", "slick", "slimy", "unctuous"]},
  {id:"213",words:["bon vivant", "gourmet", "gourmand", "gormand", "epicure", "gastronome", "gastronomer"]},
  {id:"214",words:["amuck", "berserk", "irate"]},
  {id:"215",words:["rampage", "rage"]},
  {id:"216",words:["daffy", "delirious", "demented", "deranged", "distracted", "distrait", "distraught", "insane"]},
  {id:"217",words:["agile", "keen", "nimble", "spry", "sprightly"]},
  {id:"218",words:["aquatic", "marine", "maritime", "nautical", "naval", "pelagian", "pelagic"]},
  {id:"219",words:["dolt", "dope", "dullard", "dunce", "goof", "gook", "goon", "idiot", "imbecile", "moron", "muggins", "oaf", "patch", "simpleton", "zany"]},
  {id:"220",words:["crass", "cretinous", "doltish", "dopey", "fatuous", "hebetudinous", "idiotic", "imbecilic", "inane", "moronic", "vacuous"]},
  {id:"221",words:["amphigory", "balderdash", "drivel", "folderole", "rigmarole", "fandango", "fandangle", "folly"]},
  {id:"222",words:["contradict", "demur", "deny", "deprecate", "disapprobate", "disapprove", "expostulate", "gainsay", "object", "oppose", "protest", "remonstrate", "reprobate", "repugn"]},
  {id:"223",words:["revolt", "rebellion", "riot", "sedition", "insurrection", "insurrectionist", "treason", "mutiny", "insurgence", "insurgency", "subversion"]},
  {id:"224",words:["revolt", "rebel", "subvert", "insurrectionize"]},
  {id:"225",words:["effuse", "eject", "emanate", "emit", "eructate", "exude", "erupt", "gush", "radiate", "spew", "vomit"]},
  {id:"226",words:["beget", "engender", "procreate", "spawn", "initiate", "create"]},
  {id:"227",words:["burnished", "effulgent", "flamboyant", "lustrous", "radiant", "refulgent", "resplendent", "incandescent", "opalescent", "fluorescent"]},
  {id:"228",words:["errant", "itinerant", "migratory", "nomadic", "peripatetic", "roving", "vagrant", "wandering"]},
  {id:"229",words:["immoderate", "intemperate", "incontinent", "degenerate", "dissolute", "indulging", "reprobate", "sybarite", "unrestrained", "unguarded"]},
  {id:"230",words:["circumvent", "debar", "encumber", "foil", "stall", "forestall", "hamper", "hinder", "impede", "intervene", "nip", "preclude", "stem", "thwart", "arrest", "stunt", "dwarf"]},
  {id:"231",words:["disloyalty", "double-dealing", "infidelity", "treachery", "betrayal", "duplicity", "perfidy", "treason", "recreancy", "tergiversation"]},
  {id:"232",words:["strut", "buttress", "prop", "girder", "beam"]},
  {id:"233",words:["dazzling", "effulgent", "flamboyant", "glinting", "glistening", "glittering", "incandescent", "iridescent", "radiant", "resplendent", "shining", "sparkling", "twinkling"]},
  {id:"234",words:["blaze", "glint", "glisten", "glow", "radiate", "resplend", "scintillate", "spangle", "opalesce", "incandesce", "luminesce", "fluoresce"]},
  {id:"235",words:["burgeon", "effloresce", "flourish", "mushroom", "proliferate", "prosper", "thrive", "wax"]},
  {id:"236",words:["bastinado", "comeuppance", "gruel", "lash", "nemesis", "pillory", "retribution", "scourge", "whip"]},
  {id:"237",words:["deluge", "flood", "inundation", "spate"]},
  {id:"238",words:["deluge", "flood", "inundate"]},
  {id:"239",words:["affection", "caprice", "fad", "humor", "maggot", "mood", "temper", "vagary", "whim"]},
  {id:"240",words:["crotchety", "erratic", "faddish", "fickle", "freakish", "labile", "mercurial", "mobile", "mutable", "vagarious", "vagrant", "volatile", "whimsical"]},
  {id:"241",words:["apostate", "pervert", "betrayer", "defector", "deserter", "heretic", "quisling", "renegade", "slacker", "traitor", "turncoat"]},
  {id:"242",words:["mutate", "transmute", "metamorphose", "alter", "hydrate", "vaporize", "evaporate", "grate", "pulverize", "incinerate", "cremate", "inflame", "cauterize", "vitrify"]},
  {id:"243",words:["ungainly", "uncouth", "graceless", "seamy", "unbecomingly"]},
  {id:"244",words:["detain", "pigeonhole", "shelve", "shunt", "table"]},
  {id:"245",words:["nemesis", "reprisal", "requite", "requital", "retaliation", "retortion", "retorsion", "retribution", "revanche", "revenge", "vengeance"]},
  {id:"246",words:["avenge", "redress", "reprisal", "retaliate", "revenge", "vindicate", "vindictive"]},
  {id:"247",words:["atonement", "compensate", "indemnify", "offset", "recoup", "reimburse", "remunerate", "reparation", "restitute", "restitution", "indemnification", "recompense"]},
  {id:"248",words:["average", "common", "commonplace", "conventional", "everyday", "mediocre", "middling", "ordinary", "pedestrian", "prosaic", "regular", "routine"]},
  {id:"249",words:["aegis", "auspices", "care", "charge", "custody", "guardianship", "keeping", "protection", "safeguard", "shield", "tutelage", "ward"]},
  {id:"250",words:["amenable", "compliant", "docile", "obedient", "submissive", "tractable"]},
);
Object.assign(window.__V502_EXT__.categorySummaries,{
  "201":"\ubb34\ub354\uc6b4",
  "202":"\ubb34\ub69d\ub69d\ud55c, \ud241\uba85\uc2a4\ub7ec\uc6b4",
  "203":"\ubb34\ub840, \ubaa8\uc695",
  "204":"\ubb34\ub840\ud55c",
  "205":"\ubb34\uc11c\uc6b4, \ubb34\uc2dc\ubb34\uc2dc\ud55c",
  "206":"\ubb34\uc131\ud55c, \uc6b8\ucc3d\ud55c, \uc6b0\uac70\uc9c4, \ud48d\ubd80\ud55c",
  "207":"\ubb35\uc2dc\uc801\uc778",
  "208":"\ubb3b\ub2e4, \uac10\ucd94\ub2e4",
  "209":"\ubb3c\uac74\uc744 \ud30c\ub294 \uc5ec\ub7ec \uc720\ud615",
  "210":"\ubb3c\ub9ac\uac8c \ud558\ub2e4, \uc2eb\uc99d\ub098\uac8c \ud558\ub2e4",
  "211":"\ubb3c\ub9b0, \uc2eb\uc99d\uc774 \ub09c",
  "212":"\ubbf8\ub048\uac70\ub9ac\ub294",
  "213":"\ubbf8\uc2dd\uac00, \uc2dd\ub3c4\ub77d\uac00",
  "214":"\ubbf8\uccd0 \ub0a0\ub6f0\ub294",
  "215":"\ubbf8\uccd0 \ub0a0\ub6f0\ub2e4",
  "216":"\ubbf8\uce5c, \uc2e4\uc131\ud55c",
  "217":"\ubbfc\ucca9\ud55c, \uae30\uc6b4\ucc2c",
  "218":"\ubc14\ub2e4\uc758",
  "219":"\ubc14\ubcf4",
  "220":"\ubc14\ubcf4 \uac19\uc740, \uc5b4\ub9ac\uc11d\uc740",
  "221":"\ubc14\ubcf4 \uac19\uc740 \ub9d0, \ud589\ub3d9",
  "222":"\ubc18\ub300\ud558\ub2e4, \uc774\uc758\ub97c \uc81c\uae30\ud558\ub2e4",
  "223":"\ubc18\ub780, \ud3ed\ub3d9",
  "224":"\ubc18\ub780\uc744 \uc77c\uc73c\ud0a4\ub2e4",
  "225":"(\ube5b, \uc5f4, \ub0c4\uc0c8 \ub530\uc704\ub97c) \ubc1c\uc0b0(\ubd84\ucd9c)\ud558\ub2e4",
  "226":"\ubc1c\uc0dd\uc2dc\ud0a4\ub2e4",
  "227":"\ubc1d\uac8c \ube5b\ub098\ub294",
  "228":"\ubc29\ub791\ud558\ub294, \uc774\ub9ac\uc800\ub9ac \ub5a0\ub3cc\uc544\ub2e4\ub2c8\ub294",
  "229":"\ubc29\ud0d5\ud55c, \ubb34\uc808\uc81c\ud55c, \ucf8c\ub77d\uc5d0 \ud0d0\ub2c9\ud558\ub294",
  "230":"\ubc29\ud574\ud558\ub2e4, \uc88c\uc808\uc2dc\ud0a4\ub2e4",
  "231":"\ubc30\uc2e0, \ubd88\ucda9, \ubd88\uc131\uc2e4",
  "232":"\ubc84\ud300\ubaa9",
  "233":"\ubc88\uca4d\uc774\ub294, \ube5b\uc744 \ub0b4\ub294",
  "234":"\ubc88\uca4d\ubc88\uca4d \ube5b\uc744 \ub0b4\ub2e4",
  "235":"\ubc88\uc601\ud558\ub2e4, \ubc88\uc131\ud558\ub2e4, \uc735\uc131\ud558\ub2e4",
  "236":"\ubc8c(\ud558\ub2e4)",
  "237":"\ubc94\ub78c, \uc1c4\ub3c4",
  "238":"\ubc94\ub78c\ud558\ub2e4, \uc1c4\ub3c4\ud558\ub2e4",
  "239":"\ubcc0\ub355",
  "240":"\ubcc0\ub355\uc2a4\ub7ec\uc6b4, \ubcc0\ud654\ud558\uae30 \uc26c\uc6b4",
  "241":"\ubcc0\uc808\uc790",
  "242":"\ubcc0\ud654\uc2dc\ud0a4\ub2e4, \uacbd\ud654(\uc561\ud654, \uae30\ud654)\uc2dc\ud0a4\ub2e4",
  "243":"(\ucda4 \ub530\uc704\uc758 \ub3d9\uc791\uc774) \uc5b4\uc0c9\ud55c, \ubcf4\uae30 \ud749\ud55c",
  "244":"\ubcf4\ub958\ud558\ub2e4",
  "245":"\ubcf4\ubcf5, \ubcf5\uc218",
  "246":"\ubcf4\ubcf5\ud558\ub2e4, \ubcf5\uc218\ud558\ub2e4",
  "247":"\ubcf4\uc0c1\ud558\ub2e4, \ubcf4\ub2f5\ud558\ub2e4",
  "248":"\ubcf4\ud1b5\uc758, \uc77c\uc0c1\uc758, \uadf8\uc800 \uadf8\ub7f0, \ud3c9\ubc94\ud55c",
  "249":"\ubcf4\ud638",
  "250":"\ubcf5\uc885\ud558\ub294, \ub2e4\ub8e8\uae30 \uc26c\uc6b4",
});

Object.assign(window.__V502_EXT__.confusionNotes,{
  "abrupt":"ab(떨어져)+rupt(부수다). 퉁명스러운, 무뚝뚝한. 갑작스러운.",
  "agile":"날렵하고 민첩한. 육체·정신 모두에 씀. 'agile mind(기민한 두뇌)'.",
  "amuck":"미친 듯이 날뛰는. 'run amuck(미쳐 날뛰다)'. 말레이어에서.",
  "aquatic":"물속에서 자라는/사는. 수생 동식물.",
  "arid":"완전히 건조한. 비가 안 와서 메마른. 비유적 '무미건조한'.",
  "auction":"경매. 가장 높은 입찰자에게 파는.",
  "barter":"물물교환하다. 돈 없이 물건끼리 교환.",
  "berserk":"(화가 나서) 미쳐 날뛰는. 바이킹 전사(berserker)에서.",
  "blase":"(쾌락에) 물린, 싫증난. 프랑스어. 탈력적인 무관심.",
  "bluff":"무뚝뚝하지만 정직한. 절벽(bluff) 뜻도. 허세 부리다.",
  "blunt":"무딘; 퉁명스러운. 직설적이고 배려 없는.",
  "boorish":"boor(촌뜨기)+ish. 야비하고 촌스러운. 예의 없는.",
  "brusque":"무뚝뚝한, 퉁명스러운. abrupt와 유사.",
  "churlish":"churl(천한 자)+ish. 무뚝뚝하고 예의 없는. 심술궂은.",
  "chutzpah":"뻔뻔스러움, 대담함. 이디시어에서 유래. 긍정/부정 모두.",
  "cloy":"(쾌락·음식에) 넌더리나게 하다, 물리게 하다.",
  "contumely":"(언어·태도의) 오만, 무례, 모욕. 격식어.",
  "crass":"우둔하고 매우 무신경한. 'crass ignorance(철면피 무지)'.",
  "curt":"짧고 퉁명스러운. 간결하지만 무례한 느낌.",
  "delirious":"(열병으로) 의식이 혼미한; 광란의. 'delirious with joy'.",
  "demented":"de(아래로)+ment(정신)+ed. 정신이 나간, 발광한.",
  "deranged":"de(제거)+ranged(정리된). 정리가 안 된, 미친.",
  "distraught":"dis(떨어져)+traught(끌려간). 완전히 제정신 아닌, 반미친.",
  "dolt":"멍청이. dull(둔한)과 같은 어원.",
  "dread":"무서운, 두려운. 명사로 '공포'. 형용사로 '무시무시한'.",
  "dunce":"열등생, 저능아. Duns Scotus(스콜라 철학자)에서. 반대자들이 붙인 멸칭.",
  "eerie":"섬뜩한, 으스스한. 초자연적인 두려움.",
  "effrontery":"ef(밖으로)+front(이마)+ery. 뻔뻔스럽게 나서는. 철면피.",
  "epicure":"미식가, 식도락가. 에피쿠로스(Epicurus) 철학에서 유래.",
  "exuberant":"ex(밖으로)+uber(비옥한)+ant. 풍부한, 넘쳐나는. 활기찬.",
  "fatuous":"fatu(바보)+ous. 바보 같은, 우스꽝스러운. 'fatuous smile'.",
  "ghastly":"무서운, 소름끼치는. 창백하고 귀신 같은.",
  "glut":"배불리다; 과잉 공급. 싫증나게 하다.",
  "gourmet":"미식가. 음식에 조예 깊은 사람. gourmand(대식가)와 구분.",
  "grisly":"소름끼치게 무서운. 유혈이 낭자한 느낌.",
  "gruesome":"무시무시한, 끔찍한. 잔혹한 장면에 씀.",
  "hawk":"(길거리에서) 외치며 팔다. 매(hawk) 뜻도.",
  "hubris":"그리스 비극의 오만. 신에 도전하는 교만. 파멸을 부르는.",
  "imbecile":"저능한, 천치. 의학적으로는 중등도 지적장애(과거 용어).",
  "implicit":"암시적인, 묵시적인. 'implicit trust(절대적 신뢰)'.",
  "inane":"어리석고 무의미한. 내용 없는 공허함.",
  "inhume":"in(안으로)+hume(땅). 땅에 묻다, 매장하다.",
  "insolence":"무례하고 오만한 태도. 아랫사람에게 건방진.",
  "lurid":"소름끼치는; (색이) 야한. 선정적인 묘사에도 씀.",
  "lush":"무성한, 우거진. 호화로운(lush hotel). 술고래 뜻도.",
  "luxuriant":"luxury(사치)에서. 무성하게 자란; 풍부한.",
  "macabre":"죽음과 관련된 섬뜩함. 'danse macabre(죽음의 무도)'.",
  "marine":"바다의. 해병대(Marine). 바다 생물.",
  "maritime":"바다의, 해양의. 해운·해상 무역에 자주 씀.",
  "morbid":"죽음·질병에 집착하는; 병적인. 'morbid curiosity(병적 호기심)'.",
  "moron":"멍텅구리. 그리스어 moros(어리석은). 의학적 용어였으나 현재 모욕적.",
  "muggy":"후텁지근한, 무더운. 습도가 높아 찝찝한 날씨.",
  "nautical":"naut(선원)+ical. 항해의, 선박의. 'nautical mile(해리)'.",
  "naval":"nav(배)+al. 해군의. 'naval battle(해전)'.",
  "nimble":"(동작이) 빠르고 가벼운. 손재주·두뇌 회전에 씀.",
  "oaf":"백치, 바보, 덩치만 큰 멍청이. 고블린(elf)에서 변형.",
  "oily":"기름진; 아첨하는. slick과 유사한 부정적 뉘앙스.",
  "peddle":"행상하다, 조금씩 팔다. 'peddle influence(영향력을 팔다)'.",
  "pelagic":"원양의, 심해의. 연안이 아닌 먼 바다.",
  "profuse":"pro(앞으로)+fuse(붓다). 넘칠 정도로 풍부한.",
  "rank":"무성한; 악취 나는; 등급. 문맥에 따라 다양.",
  "sate":"완전히 만족시키다; 물리게 하다. satiate의 단축형.",
  "satiate":"충분히 만족시키다; 물리게 할 정도로.",
  "slick":"미끄러운; 겉만 번지르르한. 솜씨 좋은(긍정) 뜻도.",
  "sprightly":"sprite(요정)+ly. 요정처럼 활기찬. 생기발랄한.",
  "spry":"(특히 노인이) 활발하고 재빠른. 나이에도 정정한.",
  "surfeit":"과식하게 하다, 물리게 하다. sur-(넘치게)+feit(만들다).",
  "sweltering":"swelter(더위 먹다)+ing. 더위 먹은 듯한, 찌는 듯한.",
  "tacit":"무언의, 암묵의. 'tacit agreement(암묵적 동의)'.",
  "torrid":"몹시 더운, 열대의. 'torrid zone(열대)'. 격정적인(torrid affair).",
  "tout":"(물건을) 강매하다, 억지로 권하다. 암표상(tout).",
  "unctuous":"기름 같은; 지나치게 상냥한, 아첨하는. 위선적 느낌.",
  "vacuous":"vac(빈)+uous. 텅 빈 듯 멍청한. 공허한 표정.",
  "zany":"Zanni(이탈리아 희극 하인 캐릭터). 엉뚱하고 익살맞은.",
});

// Batch 2
Object.assign(window.__V502_EXT__.confusionNotes,{
  "apostate":"apo(떨어져)+state(서다). 신앙을 버린 배교자. 변절자.",
  "beget":"be+get. (아이를) 낳다; (결과를) 초래하다. 고어체.",
  "burgeon":"burgeon(싹). 싹이 트다; 급성장하다. 'burgeoning population'.",
  "burnished":"burnish(닦다)+ed. 광택 나게 닦은. 빛나는.",
  "buttress":"(건물 벽의) 버팀대, 지지대. 비유적 '지지, 뒷받침'.",
  "caprice":"변덕, 일시적 충동. 이유 없는 급격한 변화.",
  "circumvent":"circum(주위를)+vent(가다). 둘러서 가다; (규칙을) 회피하다.",
  "comeuppance":"come up(다가오다)+ance. 인과응보. 마땅히 받을 벌.",
  "contradict":"contra(반대)+dict(말하다). 반대하여 말하다, 부정하다.",
  "dazzling":"현혹적일 정도로 눈부신. 'dazzling performance(눈부신 공연)'.",
  "deluge":"대홍수; 쇄도. Noah의 대홍수(the Deluge). 'a deluge of complaints'.",
  "demur":"de(아래로)+mur(머무르다). 주저하며 이의를 제기하다.",
  "detain":"de(아래로)+tain(잡다). 붙잡아 두다, 구금·보류하다.",
  "dissolute":"dis(떨어져)+solute(풀린). 방종한, 문란한.",
  "duplicity":"du(둘)+plic(접다)+ity. 이중성, 표리부동.",
  "effloresce":"ef+flor(꽃)+esce. 꽃피다; 번영하다. 화학 '풍화하다'.",
  "effuse":"ef(밖으로)+fuse(붓다). (빛·열·감정을) 발산시키다.",
  "emanate":"e(밖으로)+man(흐르다)+ate. (냄새·빛이) 스며 나오다.",
  "encumber":"en+cumber(방해하다). 방해하다, 짐을 지우다. 'encumbered with debt'.",
  "engender":"en(안에서)+gender(생성하다). (감정·상황을) 발생시키다.",
  "errant":"err(방황하다)+ant. (행동이) 잘못된; 떠도는. 'knight errant(방랑 기사)'.",
  "eructate":"e(밖으로)+ruct(트림)+ate. 분출하다. 화산·트림에 씀.",
  "expostulate":"ex(밖으로)+postul(요구하다)+ate. 강하게 항의하다, 간곡히 타이르다.",
  "exude":"ex(밖으로)+sude(땀). (땀·자신감 등이) 배어 나오다.",
  "fickle":"fick(변하다)+le. 마음이 잘 변하는, 변덕스러운.",
  "flourish":"flor(꽃)+ish. 꽃피우다, 번창하다. 칼 휘두르기 동작.",
  "foil":"(계략을) 좌절시키다. fencing의 플뢰레(foil).",
  "forestall":"fore(미리)+stall(세우다). 미리 막다, 기선을 제압하다.",
  "gainsay":"gain(반대)+say(말하다). 반대하다, 부정하다. 고어체.",
  "girder":"(건물·교량의) 대들보, 거더.",
  "hamper":"방해하다, 훼방 놓다. 바구니(hamper) 뜻도.",
  "heretic":"hairesis(선택하다). 이단자. 정통 교리를 거부한.",
  "impede":"im(안으로)+pede(발). 발을 묶다, 방해하다.",
  "insurrection":"in(위로)+surrection(일어나다). 무장 봉기, 폭동.",
  "intemperate":"in(아닌)+temperate(절제된). 무절제한. 특히 음주에.",
  "inundation":"in(안으로)+unda(파도)+tion. 범람, 쇄도. 'inundation of applications'.",
  "itinerant":"itiner(여행)+ant. 이곳저곳 떠돌아다니는. 순회하는.",
  "lustrous":"luster(광택)+ous. 윤기가 흐르는, 반짝이는.",
  "mercurial":"Mercury(수성, 신의 전령). 수은처럼 활발하고 변덕스러운.",
  "metamorphose":"meta(변화)+morph(형태)+ose. 형태를 완전히 바꾸다. 변태.",
  "nemesis":"Nemesis(그리스 복수의 여신). 피할 수 없는 응징, 인과응보.",
  "nomadic":"nomad(유목민)+ic. 유목의, 정착하지 않는.",
  "ossify":"oss(뼈)+ify. 뼈로 굳어지다; 경직되다. 조직의 경직화.",
  "perfidy":"per(통해)+fidy(믿음). 신의를 저버림, 불신. 'perfidious Albion'.",
  "peripatetic":"peri(주위를)+pate(걷다)+tic. 걸어 다니는; 아리스토텔레스 학파.",
  "petrify":"petr(돌)+ify. 돌로 만들다; 경악하게 하다. 'petrified with fear'.",
  "pillory":"(과거의) 목·손을 구멍에 넣어 묶는 형틀; 공개 망신 주다.",
  "preclude":"pre(미리)+clude(닫다). 미리 차단하다, 못하게 하다.",
  "proliferate":"proli(자손)+fer(나르다)+ate. (세포처럼) 급격히 증식하다.",
  "quisling":"Vidkun Quisling(노르웨이 나치 부역자)에서. 매국노, 부역자.",
  "remonstrate":"re(다시)+monstr(보여주다)+ate. 이의를 공식 제기하다.",
  "renegade":"re(다시)+neg(부정하다)+ade. 변절자, 배신자.",
  "reprisal":"re(다시)+pris(잡다)+al. 보복. 주로 군사적·정치적 앙갚음.",
  "retaliation":"re(다시)+tali(같은)+ation. '눈에는 눈' 식 보복.",
  "retribution":"re(뒤로)+tribut(주다)+ion. 되갚음, 응징. 인과응보.",
  "scourge":"채찍; 징계하다, 응징하다. 'scourge of God(신의 채찍)'.",
  "sedition":"se(떨어져)+dit(가다)+ion. (국가 전복) 선동. 반역보다 약함.",
  "shelve":"shelf(선반)+e. 선반에 올려두다; 뒤로 미루다.",
  "spawn":"(물고기가) 알을 낳다; (결과를) 대량 생산하다.",
  "subversion":"sub(아래로)+version(돌리다). 아래에서 뒤집기, 체제 전복.",
  "sybarite":"Sybaris(고대 그리스 사치 도시) 사람. 사치와 쾌락 탐닉자.",
  "thrive":"번창하다. 고대 노르드어 '잡다(grasp)'에서. 성공적으로 성장.",
  "thwart":"(계획을) 좌절시키다, 방해하다. 노 젓는 자리(thwart).",
  "traitor":"조국·친구를 배신한 자. 가장 강한 배신자 표현.",
  "transmute":"trans(건너)+mute(바꾸다). 본질을 변화시키다. 연금술 용어.",
  "treachery":"treach(속이다)+ery. 배반, 배신 행위.",
  "turncoat":"coat(외투)를 뒤집어 입다. 변절자. 기회주의적 배신.",
  "uncouth":"un+couth(알려진). 무례하고 상스러운. 미개한.",
  "ungainly":"un+gainly(우아한). 어색하고 보기 흉한. 동작이 둔한.",
  "vagary":"vag(방황)+ary. 예측 불가한 변화, 엉뚱한 생각. 주로 복수 vagaries.",
  "vagrant":"방랑자, 부랑자. 일정한 주거 없는.",
  "vengeance":"venge(복수)+ance. 피의 복수. 가장 강한 복수의 표현.",
  "volatile":"vol(날다)+atile. 날아가는; 휘발성의; 변덕스러운.",
  "wax":"(달이) 차다; 점점 커지다; 증대하다. 밀랍(wax) 뜻도.",
  "whim":"갑작스러운 변덕, 일시적 욕구. 'on a whim(충동적으로)'.",
  "whimsical":"whim+ical. 엉뚱하고 변덕스러운. 기발하고 재미있는(긍정).",
});

// Auto-extracted word meanings (246 words)
Object.assign(window.__V502_EXT__.wordMeanings,{
  "aegis":"보호",
  "affection":"성질; 애정",
  "affront":"과감히 맞서다; 모욕하다; 모욕",
  "alter":"변하다",
  "amenable":"(충고 등에) 순종하는",
  "amphigory":"무의미하고 우스운 글",
  "appalling":"섬뜩하게 하는",
  "arrest":"막다, (병의 진행을) 억제하다",
  "avenge":"(사건에 대해) 복수를 하다",
  "balderdash":"같잖은 소리",
  "bastinado":"태형에 처하다",
  "beam":"대들보, 도리",
  "betrayal":"배신",
  "betrayer":"배신자",
  "blaze":"눈부시게 빛나다",
  "bon vivant":"미식가; 유쾌한 사람",
  "bury":"매장하다; 감추다",
  "cauterize":"소각하다",
  "chutzpa":"뻔뻔스러움, 후안무치",
  "cloyed":"물린",
  "coarse":"거친",
  "commonplace":"평범한, 개성이 없는",
  "compliant":"남이 시키는 대로 하는",
  "contumelious":"무례한",
  "conventional":"진부한, 전통적인",
  "create":"창조하다",
  "cremate":"소각하다",
  "cretinous":"바보 같은",
  "cross":"까다로운, 성마른",
  "crotchety":"변덕스러운",
  "custody":"보호, 감독",
  "daffy":"미친; 어리석은",
  "debar":"(- 하는 것을) 방해하다",
  "defector":"배반자",
  "degenerate":"약화되다",
  "deny":"부인하다",
  "deprecate":"-에 불찬성을 주장하다",
  "deserter":"탈영병",
  "diabolical":"극악무도한",
  "disapprobate":"허가하지 않다",
  "disapprove":"탐탁잖아 하다; 반대하다",
  "disloyalty":"불충, 불성실",
  "distracted":"마음이 산란한",
  "distrait":"(불안·근심으로) 멍한",
  "doltish":"멍청한",
  "dope":"얼간이; 마약",
  "dopey":"바보 같은",
  "double-dealing":"표리 있는 언행, 배신",
  "dreadful":"무시무시한",
  "drivel":"계속 쓸데없는 말을 하다",
  "dullard":"멍청이",
  "dwarf":"-의 발육을 방해하다",
  "earth":"-에 흙을 덮다",
  "effulgent":"찬란히 빛나는",
  "eject":"내보내다",
  "emit":"(빛 열 가스 소리 등을) 내다",
  "erratic":"일정하지 않은, 변하기 쉬운",
  "erupt":"(화산이) 분출하다",
  "evaporate":"수증기로 만들다",
  "fad":"일시적 유행",
  "faddish":"일시적 유행을 좇는",
  "fandangle":"어리석은 짓",
  "fandango":"어리석은 행위",
  "fearful":"무서운",
  "fearsome":"(얼굴 등이) 무서운",
  "fell":"잔인한",
  "fiendish":"귀신같은; 잔인한",
  "flamboyant":"현란한, 화려한",
  "flood":"물밀 듯이 밀려들다",
  "fluoresce":"형광을 내다",
  "fluorescent":"형광을 내는",
  "folderole":"헛소리",
  "folly":"어리석은 행동",
  "freakish":"변덕스러운",
  "gastronome":"미식가",
  "gastronomer":"미식가",
  "gaunt":"기분이 섬뜩한",
  "glint":"(작게) 반짝거리다",
  "glinting":"반짝이는",
  "glisten":"젖은 것이 반짝거리다",
  "glistening":"반짝이는",
  "glittering":"번쩍이는",
  "glow":"특히 뜨거운 것이 계속 은은히 빛나다",
  "glum":"무뚝뚝한",
  "goof":"바보",
  "gook":"황색인종 (모욕적인 말)",
  "goon":"바보, 멍청이",
  "gormand":"미식가, 대식가",
  "gourmand":"미식가, 대식가",
  "graceless":"품위 없는",
  "grate":"가루(dust)로 만들다",
  "grim":"소름끼치는",
  "gruel":"호되게 벌주다",
  "gruff":"(소리·목소리가) 굵고 탁한",
  "guardianship":"후견인의 보호",
  "gush":"(액체가) 솟구치다",
  "harsh":"귀에 거슬리는",
  "haughty":"오만한, 거만한",
  "hebetudinous":"우둔한; 무기력한",
  "hideous":"섬뜩한",
  "hinder":"훼방하다",
  "horrendous":"무서운",
  "humor":"(사람·기질·취미 등을) 만족시키다",
  "hydrate":"물(water)로 만들다",
  "idiot":"천치, 바보",
  "idiotic":"바보 같은",
  "imbecilic":"어리석은",
  "immoderate":"무절제한",
  "imperious":"오만한",
  "impertinent":"버릇없는",
  "impolite":"무례한, 버릇없는",
  "improper":"부도덕한",
  "impropriety":"부도덕",
  "incandesce":"백열광을 내다",
  "incandescent":"백열의, 백열광을 내는",
  "incinerate":"소각하다",
  "incontinent":"절제 없는",
  "indecent":"버릇없는",
  "indecorous":"버릇없는",
  "indecorum":"버릇없음",
  "indulging":"탐닉하는",
  "infidelity":"(배우자나 애인에 대한) 부정",
  "inflame":"소각하다",
  "initiate":"착수시키다",
  "insane":"정신 이상의",
  "insolent":"무례한, 뻐기는",
  "insurgence":"반란 행위",
  "insurgency":"반란 행위",
  "insurrectionist":"폭동 선동자",
  "insurrectionize":"폭동을 일으키다",
  "intervene":"(사이에 들어) 방해하다",
  "inundate":"-가 쇄도하다",
  "irate":"성난",
  "iridescent":"여러 가지 빛을 내는, 무지갯빛의",
  "jade":"녹초가 되게 하다",
  "keen":"(활동·사상 등에) 열정적인",
  "labile":"불안정한",
  "lash":"몹시 꾸짖다",
  "loutish":"버릇없는; 촌뜨기 같은",
  "luminesce":"냉광을 발하다",
  "maggot":"변덕; 구더기",
  "mediocre":"보통의",
  "migratory":"이주하는",
  "mobile":"유동하는",
  "mood":"(일시적인) 기분",
  "moronic":"저능아의",
  "muggins":"얼간이",
  "mushroom":"우후죽순처럼 늘어나다",
  "mutable":"변하기 쉬운",
  "mutate":"돌연변이가 되다",
  "mutiny":"(특히 군인선원들의) 반란",
  "nip":"저지하다",
  "obedient":"순종하는",
  "object":"반대하다",
  "opalesce":"단백광을 내다",
  "opalescent":"우유 빛을 내는",
  "oppose":"(계획·정책 등에) 반대하다",
  "ordinary":"평범한",
  "patch":"바보, 얼간이",
  "pedestrian":"단조로운; 보행자",
  "pelagian":"심해의",
  "pervert":"배교자",
  "pigeonhole":"정리함에 두고 뒤로 미루다",
  "point-blank":"퉁명스럽고 직설적인",
  "presumption":"주제넘음, 체면 없음, 철면피",
  "presumptuous":"주제넘은",
  "presumptuousness":"주제넘음, 건방짐",
  "procreate":"자손을 낳다",
  "prop":"받침대",
  "prosaic":"단조로운",
  "prosper":"번영하다",
  "protection":"보호",
  "protest":"항의하다",
  "pulverize":"가루(dust)로 만들다",
  "radiant":"빛나는, 밝은",
  "radiate":"(사람이 어떤 검정 특질 등을) 내뿜다",
  "rage":"격노(하다)",
  "rampage":"(성나서) 날뛰기",
  "rebel":"반란을 일으키다",
  "rebellion":"반란",
  "recompense":"보상하다",
  "recoup":"-에게 보상하다",
  "recreancy":"불성실, 변절",
  "refulgent":"환히 빛나는",
  "reimburse":"(빚 따위를) 갚다",
  "remunerate":"보상하다; 보수를 주다",
  "reprobate":"비난하다; 타락한; 방탕아",
  "repugn":"-에 반대하다",
  "requital":"보복",
  "requite":"갚다, 보상하다",
  "resplend":"빛나다, 반짝이다",
  "resplendent":"반짝 반짝 빛나는, 눈부신",
  "retaliate":"보복하다",
  "retorsion":"(높은 관세에 의한) 보복",
  "retortion":"(높은 관세에 의한) 보복",
  "revanche":"복수",
  "revenge":"복수, 앙갚음",
  "revolt":"불쾌함을 갖게 하다",
  "rigmarole":"횡설수설; (불필요하게 길고) 복잡한 절차",
  "riot":"폭동",
  "roving":"방랑하는",
  "sated":"-에 물린",
  "satiated":"충분히 만족한",
  "saturnine":"냉소적인",
  "scintillate":"불꽃을 내다",
  "seamy":"보기 흉한, 지저분한",
  "shining":"반짝이는",
  "shunt":"(기차의) 선로를 바꾸다; 이동시키다",
  "simpleton":"얼간이, 숙맥",
  "slacker":"책임 회피자; 게으름뱅이",
  "slimy":"(더럽고) 끈적끈적한",
  "spangle":"금속 조각으로 장식하다",
  "sparkling":"번쩍이는",
  "spate":"홍수; 대량; (감정 따위의) 폭발",
  "spew":"뿜어져 나오다",
  "stall":"꼼짝 못하게 하다; 마구간; 매점",
  "stem":"(반대 따위를) 저지하다",
  "stoke":"실컷 먹다",
  "strut":"지주, 버팀목",
  "stunt":"성장을 방해하다",
  "submissive":"복종하는",
  "subvert":"(체제를) 전복시키다",
  "sulky":"토라진, 골이 나서 말을 않는",
  "sullen":"토라진, 골이 나서 말을 않는",
  "surfeited":"과식한, 물린",
  "surly":"무뚝뚝한",
  "table":"(의안을) 무기 연기하다; 묵살하다",
  "temper":"기질, 성질",
  "tergiversation":"속임, 변절",
  "tractable":"다루기 쉬운",
  "treason":"반역, 배신",
  "tutelage":"보호",
  "twinkling":"반짝반짝하는",
  "unaffable":"퉁명스러운",
  "unbecomingly":"어울리지 않게; 온당치 못하게",
  "unguarded":"언행을 조심하지 않는, 경솔한",
  "unrestrained":"(언행 등이) 억제되지 않은",
  "unseemly":"꼴사나운; 꼴사납게",
  "unspoken":"입 밖에 내지 않는",
  "vagarious":"변덕스러운",
  "vaporize":"수증기로 만들다",
  "vitrify":"유리(glass)로 만들다",
  "vomit":"토하다",
  "wandering":"(정처 없이) 돌아다니는",
  "weary":"싫증나는, 진저리나는",
  "whip":"채찍질하다",
});

// Extracted meanings batch (4 words)
Object.assign(window.__V502_EXT__.wordMeanings,{
  "brusk":"무뚝뚝한, 퉁명스러운",
  "charge":"돌격하다",
  "indemnify":"-에게 배상하다",
  "redress":"(부정·불균형 따위를) 고치다",
});
