// LOGIC TREE V502 — Categories 051-060
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"051",words:["abate", "bate", "attemper", "temper", "allay", "alleviate", "assuage", "extenuate", "palliate", "mitigate", "moderate", "mollify", "qualify", "relent", "remit", "reprieve"]},
  {id:"052",words:["blind alley", "cul-de-sac", "deadlock", "dilemma", "imbroglio", "impasse", "lurch", "morass", "nonplus", "perplexity", "plight", "predicament", "quagmire", "quandary", "stalemate", "stymie"]},
  {id:"053",words:["tangle", "entangle", "embroil", "enmesh", "ensnare", "entrap", "implicate", "involve", "mire", "ravel", "snarl"]},
  {id:"054",words:["proclaim", "promulgate", "propagate", "trumpet"]},
  {id:"055",words:["collusion", "conspiracy", "intrigue", "plot", "scheme"]},
  {id:"056",words:["collude", "conspire", "intrigue", "plot", "scheme"]},
  {id:"057",words:["disinterested", "dispassionate", "unimpassioned", "equitable", "evenhanded"]},
  {id:"058",words:["amplify", "magnify", "overblow", "overemphasize", "overestimate", "overrate", "overstate", "bombast", "fustian", "grandiloquence", "hyperbole", "overstatement", "pomposity"]},
  {id:"059",words:["belittle", "decry", "depreciate", "discredit", "disparage", "minimize", "underestimate", "underrate", "understate"]},
  {id:"060",words:["glut", "over-abundance", "plethora", "superabundance", "surfeit"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abate":"(기세·격렬함이) 약해지다",
  "allay":"(고통·슬픔 등을) 누그러뜨리다",
  "alleviate":"경감하다",
  "amplify":"과장해서 말하다",
  "assuage":"진정시키다",
  "attemper":"누그러뜨리다, 완화시키다",
  "bate":"(기세·격렬함이) 약해지다",
  "belittle":"얕잡다",
  "blind alley":"막다른 골목",
  "bombast":"과장하는 말",
  "collude":"은밀히 결탁하다",
  "collusion":"공모",
  "conspiracy":"작당",
  "conspire":"공모하다",
  "cul-de-sac":"막힌 길",
  "deadlock":"교착상태",
  "decry":"(통화 등의) 가치를 떨어뜨리다, 공공연히 비난하다",
  "depreciate":"경시하다, 얕보다",
  "dilemma":"진퇴양난",
  "discredit":"-의 평판을 나쁘게 하다",
  "disinterested":"사욕이 없는, 청렴한",
  "disparage":"폄하하다",
  "dispassionate":"공평무사한",
  "embroil":"(사건 따위에) 휩쓸어 넣다",
  "enmesh":"(곤란 따위에) 빠뜨리다",
  "ensnare":"함정에 빠뜨리다",
  "entangle":"(함정·곤경 등에) 빠지게 하다",
  "entrap":"속여서 빠져들게 하다",
  "equitable":"공정한",
  "evenhanded":"공평한",
  "extenuate":"완화하다",
  "fustian":"(문장·말의) 과장",
  "glut":"차고 넘침",
  "grandiloquence":"과장하는 말",
  "hyperbole":"과장하는 말",
  "imbroglio":"(일의) 뒤얽힘",
  "impasse":"곤경",
  "implicate":"연좌시키다",
  "intrigue":"계략을 꾸미다",
  "involve":"분쟁에 말려들다",
  "lurch":"(갑자기) 휘청하다",
  "magnify":"과장하다",
  "minimize":"경시하다",
  "mire":"진구렁에 빠뜨리다",
  "mitigate":"가라앉히다; (형벌 따위를) 가볍게 하다",
  "moderate":"삼가는",
  "mollify":"누그러지게 하다, 완화하다",
  "morass":"곤경",
  "nonplus":"당혹, 곤경",
  "over-abundance":"과잉의",
  "overblow":"부풀리다",
  "overemphasize":"지나치게 강조하다",
  "overestimate":"과대평가하다",
  "overrate":"과대평가하다",
  "overstate":"허풍을 떨다, 과장하다",
  "overstatement":"과장한 말",
  "palliate":"고통을 완화시키다",
  "perplexity":"난국",
  "plethora":"과다",
  "plight":"궁지",
  "plot":"음모",
  "pomposity":"과장하는 말",
  "predicament":"곤경",
  "proclaim":"포고하다",
  "promulgate":"(법령 따위를) 반포하다",
  "propagate":"선전하다",
  "quagmire":"꼼짝할 수 없는 곤경",
  "qualify":"누그러뜨리다, 진정하다",
  "quandary":"곤혹, 진퇴유곡",
  "ravel":"(문제를) 혼란하게 하다",
  "relent":"상냥스러워지다",
  "remit":"(노여움·고통 따위를) 누그러뜨리다",
  "reprieve":"(특히 사형수의）형 집행을 연기하다",
  "scheme":"책략",
  "snarl":"(교통·통신 등을) 혼란시키다",
  "stalemate":"막다름",
  "stymie":"난처한 상태",
  "surfeit":"과다",
  "tangle":"(함정·곤경 등에) 빠지게 하다",
  "temper":"기질, 성질",
  "trumpet":"널리 알리다",
  "underestimate":"과소평가하다",
  "underrate":"경시하다",
  "understate":"삼가서 말하다",
  "unimpassioned":"냉정한"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "051":"(고통, 슬픔, 분노 따위를) 완화하다, 경감하다",
  "052":"곤경, 난처한 상황",
  "053":"곤경에 빠뜨리다",
  "054":"공고하다, 공포하다, 공언하다",
  "055":"공모(共謀), 음모",
  "056":"공모(共謀), 음모를 꾸미다",
  "057":"공평한, 불편부당한",
  "058":"과대평가하다, 과장하다",
  "059":"과소평가하다, 경시하다",
  "060":"과잉, 초과"
});
