// LOGIC TREE V502 — Categories 081-090
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};
window.__V502_EXT__.categories.push(
{id:"081",words:["annoy","bother","fret","gall","grate","irk","irritate","molest","nag","nettle","pester","plague","rankle","rasp","roil","ruffle","vex"]},
{id:"082",words:["abstemious","abstinent","ascetic","self-denying","sober","stoic","moderate","temperate"]},
{id:"083",words:["arrant","atrocious","diabolical","egregious","enormous","fell","ferocious","fiendish","fierce","flagitious","heinous","inexorable","infernal","knavish","miscreant","nefarious","notorious","rascally","relentless","ruffian","villainous"]},
{id:"084",words:["blackguard","hoodlum","hooligan","knave","malefactor","miscreant","rapscallion","rascal","reprobate","rogue","rowdy","ruffian","scoundrel","strum","villain"]},
{id:"085",words:["busy","industrious","diligent","assiduous","sedulous"]},
{id:"086",words:["agony","angst","anguish","anxiety","apprehension","misgiving","qualm"]},
{id:"087",words:["crabbed","illegible","scribble"]},
{id:"088",words:["financial","fiscal","monetary","pecuniary"]},
{id:"089",words:["debar","enjoin","inhibit","interdict","prohibit","proscribe"]},
{id:"090",words:["assail","assault","foray","incursion","invasion","onslaught","sally","dash","charge"]}
);
Object.assign(window.__V502_EXT__.wordMeanings,{
annoy:"괴롭히다",bother:"-을 괴롭히다",fret:"괴롭히다",gall:"성나게 하다",grate:"(신경·귀에) 거슬리다",irk:"지치게 하다",irritate:"짜증나게 하다",molest:"(짓궂게) 괴롭히다",nag:"(긴 잔소리로 귀찮게 하다)",nettle:"화나게 하다",pester:"고통을 주다",plague:"귀찮은 일",rankle:"-을 짜증나게 하다",rasp:"신경을 거스르다",roil:"노하게 하다",ruffle:"성나게 하다",vex:"귀찮게 굴다",
abstemious:"절제하는",abstinent:"금욕적인",ascetic:"금욕주의자","self-denying":"극기의",sober:"절주하고 있는",stoic:"금욕주의자",moderate:"삼가는",temperate:"중용의",
arrant:"악명 높은",atrocious:"흉악한",diabolical:"악마의",egregious:"지독한",enormous:"극악한",fell:"잔인한",ferocious:"사나운",fiendish:"극악한",fierce:"흉포한",flagitious:"극악무도한",heinous:"악질의",inexorable:"냉혹한; 변경할 수 없는",infernal:"악마 같은",knavish:"악한의",miscreant:"사악한",nefarious:"못된",notorious:"(보통 나쁜 의미로) 소문난",rascally:"무뢰한의",relentless:"끈질긴; 가차 없는",ruffian:"악한",villainous:"악한 같은",
blackguard:"깡패",hoodlum:"건달",hooligan:"무뢰한",knave:"악한",malefactor:"죄인",miscreant:"악한",rapscallion:"악한",rascal:"악당",reprobate:"비난하다; 타락한; 방탕아",rogue:"악한; 광대; 개구쟁이",rowdy:"난폭한 사람",ruffian:"불량배",scoundrel:"악당",strum:"깡패",villain:"(극·소설 따위의) 악역",
busy:"(사람·두뇌가) 부지런히 일하는",industrious:"근면한",diligent:"부지런한",assiduous:"근면한",sedulous:"공들인",
agony:"고민, 걱정",angst:"불안한 마음",anguish:"(심신의) 고통",anxiety:"걱정, 불안",apprehension:"염려, 우려",misgiving:"걱정",qualm:"불안한 마음",
crabbed:"(필적 등이) 알아보기 힘든",illegible:"읽기(판독하기) 어려운",scribble:"휘갈겨 쓰다; 악필",
financial:"재정상의",fiscal:"국고의",monetary:"금융의",pecuniary:"재정상의",
debar:"-하는 것을 금하다",enjoin:"금지하다",inhibit:"억제하다; 못하게 하다",interdict:"금하다; 금지 명령",prohibit:"금지하다",proscribe:"금지하다",
assail:"(사람·진지 등을 무력으로) 급습하다",assault:"강습, 습격",foray:"약탈하다; 급습, 습격",incursion:"(돌연한) 침입",invasion:"침입",onslaught:"돌격, 맹공격",sally:"돌격하다",dash:"돌격하다",charge:"돌격하다"
});
Object.assign(window.__V502_EXT__.categorySummaries,{
"081":"annoy / vex","082":"abstemious / ascetic","083":"atrocious / heinous","084":"scoundrel / villain","085":"industrious / diligent","086":"anxiety / anguish","087":"illegible / crabbed","088":"financial / pecuniary","089":"prohibit / proscribe","090":"assault / onslaught"
});

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abstemious":"절제하는, 금욕적인",
  "abstinent":"절제하는, 금욕적인",
  "agony":"고민, 고통",
  "angst":"불안한 마음",
  "anguish":"(심신의) 고통",
  "annoy":"괴롭히다, 귀찮게 하다",
  "anxiety":"걱정, 불안",
  "apprehension":"염려, 우려",
  "arrant":"악명 높은",
  "ascetic":"금욕주의자",
  "assail":"(사람·진지 등을 무력으로) 급습하다",
  "assault":"강습, 습격",
  "assiduous":"근면한; 주도면밀한",
  "atrocious":"흉악한",
  "blackguard":"깡패",
  "bother":"-을 괴롭히다",
  "busy":"(사람·두뇌가) 부지런히 일하는",
  "charge":"돌격하다",
  "crabbed":"(필적 등이) 알아보기 힘든, 심술궂은",
  "dash":"돌진하다",
  "debar":"(- 하는 것을) 방해하다",
  "diabolical":"극악무도한",
  "diligent":"부지런한",
  "egregious":"형편없는, 지독한",
  "enjoin":"금지하다",
  "enormous":"거대한, 막대한, 극악한",
  "fell":"잔인한",
  "ferocious":"사나운",
  "fiendish":"귀신같은; 잔인한",
  "fierce":"흉포한",
  "financial":"재정상의",
  "fiscal":"국고의",
  "flagitious":"극악무도한",
  "foray":"약탈하다; 급습, 습격",
  "fret":"괴롭히다",
  "gall":"(피부의) 찰과상",
  "grate":"가루(dust)로 만들다",
  "heinous":"악질의",
  "hoodlum":"건달",
  "hooligan":"무뢰한",
  "illegible":"읽기(판독하기) 어려운",
  "incursion":"(돌연한) 침입",
  "industrious":"근면한",
  "inexorable":"냉혹한; 변경할 수 없는",
  "infernal":"악마 같은",
  "inhibit":"억제하다; 못하게 하다",
  "interdict":"금하다; 금지 명령",
  "invasion":"침입",
  "irk":"지치게 하다",
  "irritate":"짜증나게 하다",
  "knave":"악한",
  "knavish":"악한의",
  "malefactor":"죄인",
  "miscreant":"사악한",
  "misgiving":"걱정",
  "moderate":"삼가는, 절제하는; 중재역을 맡다",
  "molest":"(짓궂게) 괴롭히다",
  "monetary":"금융의",
  "nag":"긴 잔소리로 귀찮게 하다, 잔소리(꾼)",
  "nefarious":"못된",
  "nettle":"초조하게 하다, 화나게 하다",
  "notorious":"(보통 나쁜 의미로）소문난",
  "onslaught":"돌격, 맹공격",
  "pecuniary":"재정상의",
  "pester":"고통을 주다",
  "plague":"귀찮은 일, 말썽꾸러기",
  "prohibit":"금지하다",
  "proscribe":"선거권을 박탈하다; 금지하다",
  "qualm":"(행동에 대한) 불안한 마음",
  "rankle":"(불쾌한 감정·경험 따위가) 끊임없이 괴롭히다",
  "rapscallion":"악한",
  "rascal":"악당",
  "rascally":"무뢰한의",
  "rasp":"신경을 거스르다",
  "relentless":"끈질긴; 가차 없는",
  "reprobate":"비난하다; 타락한; 방탕아",
  "rogue":"악한; 광대; 개구쟁이",
  "roil":"노하게 하다",
  "rowdy":"떠들썩한",
  "ruffian":"불량배, 악한",
  "ruffle":"(마음을) 뒤흔들다, 성나게 하다, 장식주름",
  "sally":"돌격하다",
  "scoundrel":"악당",
  "scribble":"휘갈겨 쓰다; 악필",
  "sedulous":"정성을 다하는, 공들인",
  "sober":"냉정한; 술 취하지 않은",
  "stoic":"금욕주의자",
  "strum":"깡패",
  "temperate":"절제하는, 금주의",
  "vex":"짜증나게 하다",
  "villain":"(극·소설 따위의) 악역",
  "villainous":"악한 같은",
});
