// LOGIC TREE V502 — Categories 111-120
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.categories.push(
{id:"111",words:["crestfallen","dejected","depressed","despondent","disheartened","dispirited","downcast","damped","dampened"]},
{id:"112",words:["impregnable","invincible","inviolable","invulnerable","tenable","unassailable"]},
{id:"113",words:["caterwaul","scream","screech","shriek","wail"]},
{id:"114",words:["exorbitance","extravagance","improvidence","lavishness","prodigality","profligacy","profuseness"]},
{id:"115",words:["exorbitant","extravagant","improvident","lavish","prodigal","profligate","profuse","reprobate","spendthrift"]},
{id:"116",words:["prodigal","profligate","spendthrift","wastrel"]},
{id:"117",words:["dissipate","lavish","splurge","squander","waste","drivel","piddle","dally"]},
{id:"118",words:["grudging","begrudging","hesitant","loath","reluctant"]},
{id:"119",words:["aplomb","composure","equanimity","impassiveness","imperturbation","imperturbability","poise","sangfroid","sedateness","self-possession","serenity","staidness"]},
{id:"120",words:["calm","composed","equable","impassive","imperturbable","placid","poised","reposeful","sedate","serene","staid","tranquil","undisturbed","unflappable","unimpassioned","unmoved"]}
);
Object.assign(window.__V502_EXT__.wordMeanings,{
crestfallen:"풀이 죽은",dejected:"기운 없는, 낙담한",depressed:"우울한, 낙담한",despondent:"낙담한",disheartened:"낙담시키다",dispirited:"의기소침한",downcast:"기가 꺾인",damped:"풀이 죽은",dampened:"풀이 죽은",
impregnable:"난공불락의",invincible:"정복할 수 없는",inviolable:"불가침의; 신성한",invulnerable:"(논의 따위가) 공격에 견디는",tenable:"(요새·진지 등이) 공격을 견딜 수 있는",unassailable:"난공불락의",
caterwaul:"(고양이처럼) 서로 으르렁대다",scream:"(공포·고통 따위로) 소리치다",screech:"날카로운 소리",shriek:"날카로운 소리; 비명",wail:"소리 내어 울다, 울부짖다",
exorbitance:"엄청남, 과대, 과도",extravagance:"(돈의) 낭비",improvidence:"선견지명이 없음; 낭비",lavishness:"낭비, 헤픔; 풍부함",prodigality:"방탕; 낭비; 난봉",profligacy:"방탕; 과소비",profuseness:"낭비",
exorbitant:"(욕망·요구·가격 따위가) 터무니없는",extravagant:"낭비벽이 있는",improvident:"장래를 대비치 않는; 헤픈",lavish:"(소비 따위가) 분별없는",prodigal:"낭비하는; 방탕한",profligate:"낭비가",profuse:"돈의 씀씀이가 헤픈",reprobate:"비난하다; 타락한; 방탕아",spendthrift:"돈 씀씀이 헤픈 사람",
prodigal:"낭비하는; 방탕한",profligate:"낭비가 심한, 낭비가",spendthrift:"돈 씀씀이 헤픈 사람",wastrel:"낭비자",
dissipate:"(재산 따위를) 다 써버리다",splurge:"(돈을) 물 쓰듯 하다",squander:"(시간·돈 따위를) 낭비하다",waste:"헛되이 하다, 낭비하다",drivel:"(시간 등을) 헛되게 쓰다",piddle:"시간을 낭비하다",dally:"(시간 등을) 허비하다",
grudging:"마지못해 하는; 싫어하는",begrudging:"마지못해 하는; 싫어하는",hesitant:"주저하는",loath:"(-하는 것이) 내키지 않는",reluctant:"마음 내키지 않는",
aplomb:"(마음의) 평정",composure:"침착, 냉정",equanimity:"(마음의) 평정",impassiveness:"감정이 없는",imperturbation:"침착",imperturbability:"침착",poise:"숙고하다",sangfroid:"냉정, 침착",sedateness:"침착함","self-possession":"침착",serenity:"(자연·바다·하늘 등의) 고요함",staidness:"조용, 침착",
calm:"침착한, 냉정한",composed:"(마음이) 가라앉은",equable:"(마음이) 고요한; 균등한",impassive:"감정이 없는",imperturbable:"침착한, 동요하지 않는",placid:"평온한",poised:"침착한",reposeful:"평온한, 침착한",sedate:"침착한, 조용한",serene:"(사람·표정·기질 따위가) 침착한",staid:"차분한; 고정된",tranquil:"조용한, 평온한",undisturbed:"평정을 잃지 않는; 방해받지 않은",unflappable:"침착한",unimpassioned:"냉정한, 침착한",unmoved:"확고한; 냉정한"
});
Object.assign(window.__V502_EXT__.categorySummaries,{
"111":"despondent / dejected","112":"impregnable / unassailable","113":"screech / shriek",
"114":"prodigality / extravagance","115":"prodigal / extravagant","116":"spendthrift / wastrel",
"117":"squander / dissipate","118":"reluctant / loath","119":"composure / equanimity","120":"imperturbable / serene"
});

Object.assign(window.__V502_EXT__.wordMeanings,{
  "aplomb":"(마음의) 평정",
  "begrudging":"마지못해 하는; 싫어하는",
  "calm":"침착한, 냉정한",
  "caterwaul":"(고양이처럼) 서로 으르렁대다",
  "composed":"(마음이) 가라앉은",
  "composure":"침착, 냉정",
  "crestfallen":"풀이 죽은               희롱하다",
  "dally":"미적거리다, (시간 등을) 허비하다",
  "damped":"풀이 죽은",
  "dampened":"풀이 죽은",
  "dejected":"기운 없는, 낙담한",
  "depressed":"우울한, 낙담한",
  "despondent":"낙담한, 의기소침한",
  "disheartened":"낙담시키다",
  "dispirited":"의기소침한                 116. 낭비하는 사람, 방탕한 사람",
  "dissipate":"(재산 따위를) 다 써버리다",
  "downcast":"기가 꺾인",
  "drivel":"(시간 등을) 헛되게 쓰다, 쓸데없는 말을 하다",
  "equable":"(마음이) 고요한; 균등한, 한결같은",
  "equanimity":"(마음의) 평정",
  "exorbitance":"엄청남, 과대, 과도",
  "exorbitant":"(욕망·요구·가격 따위가) 터무니없는",
  "extravagance":"(돈의) 낭비",
  "extravagant":"과도한, 낭비하는",
  "grudging":"마지못해 하는; 싫어하는",
  "hesitant":"주저하는",
  "impassive":"감정이 없는, 냉정한",
  "impassiveness":"감정이 없는",
  "imperturbability":"침착",
  "imperturbable":"침착한, 동요하지 않는",
  "impregnable":"난공불락의                117. 낭비하다, 다 써버리다",
  "improvidence":"선견지명이 없음; 낭비",
  "improvident":"장래를 대비치 않는; 헤픈",
  "invincible":"정복할 수 없는",
  "inviolable":"불가침의; 신성한",
  "invulnerable":"(논의 따위가) 공격에 견디는",
  "lavish":"(소비 따위가) 분별없는, 아낌없는",
  "lavishness":"낭비, 헤픔; 풍부함",
  "loath":"(-하는 것이) 내키지 않는",
  "piddle":"시간을 낭비하다, 한가하게 지내다",
  "placid":"평온한",
  "poise":"숙고하다",
  "poised":"침착한",
  "prodigal":"낭비하는; 방탕한                120. 냉정한, 침착한",
  "prodigality":"방탕; 낭비; 난봉",
  "profligacy":"방탕; 과소비",
  "profligate":"낭비가 심한, 낭비가",
  "profuse":"돈의 씀씀이가 헤픈, 많은, 풍부한",
  "profuseness":"낭비                    119. 냉정, 침착",
  "reluctant":"마음 내키지 않는",
  "reposeful":"평온한, 침착한",
  "reprobate":"비난하다; 타락한; 방탕아       232. 버팀목",
  "sangfroid":"냉정, 침착",
  "scream":"(공포·고통 따위로) 소리치다",
  "screech":"날카로운 소리",
  "sedate":"침착한, 조용한",
  "sedateness":"침착함",
  "serene":"(사람·표정·기질 따위가) 침착한",
  "serenity":"(자연·바다·하늘 등의) 고요함",
  "shriek":"날카로운 소리; 비명",
  "spendthrift":"돈 씀씀이 헤픈 사람",
  "splurge":"(돈을) 물 쓰듯 하다",
  "squander":"(시간·돈 따위를) 낭비하다",
  "staid":"근엄한; 침착한; 고정된",
  "staidness":"조용, 침착",
  "tenable":"(요새·진지 등이) 공격을 견딜 수 있는",
  "tranquil":"조용한, 평온한",
  "unassailable":"난공불락의",
  "undisturbed":"평정을 잃지 않는; 방해받지 않은",
  "unflappable":"침착한",
  "unimpassioned":"냉정한            60. 과잉, 초과",
  "unmoved":"확고한; 냉정한",
  "wail":"소리 내어 울다, 울부짖다",
  "waste":"헛되이 하다, 낭비하다, 황폐케 하다",
  "wastrel":"낭비자",
});
