// LOGIC TREE V502 — Categories 121-130
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"121",words:["capacious", "commodious", "spacious", "roomy"]},
  {id:"122",words:["decrepit", "doddering", "doddered", "doting", "effete", "impotent", "senile"]},
  {id:"123",words:["dissertation", "monograph", "thesis", "tract", "treatise"]},
  {id:"124",words:["confute", "contest", "controvert", "disprove", "dispute", "rebut", "refute", "consultation", "debate", "deliberation", "discussion", "disputation"]},
  {id:"125",words:["argumentative", "contentious", "controversial", "disputatious", "polemic", "polemical", "pugnacious", "quarrelsome", "scrappy"]},
  {id:"126",words:["maudlin", "mawkish", "lachrymal"]},
  {id:"127",words:["dazzling", "effulgent", "flamboyant", "incandescent", "iridescent", "opalescent", "radiant", "refulgent", "resplendent", "shining", "splendid"]},
  {id:"128",words:["clip", "trim", "prune", "hedge", "shear"]},
  {id:"129",words:["diverse", "multifaceted", "multifarious", "protean", "versatile"]},
  {id:"130",words:["bale", "host", "legion", "myriad", "passel", "raft", "scad", "skit", "slew", "spate", "throng", "wad"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "argumentative":"논쟁적인",
  "bale":"(운반용) 꾸러미, 더미",
  "capacious":"넓은; 포용력이 있는",
  "clip":"자르다, 베다",
  "commodious":"넓은",
  "confute":"틀렸음을 입증하다",
  "consultation":"상담, 의논",
  "contentious":"다투기 좋아하는",
  "contest":"반론을 펴다",
  "controversial":"논쟁의, 논쟁의 대상인",
  "controvert":"반박하다",
  "dazzling":"눈부신, 현혹적인",
  "debate":"토론",
  "decrepit":"노쇠한",
  "deliberation":"숙고, 협의",
  "discussion":"토론",
  "disprove":"틀렸음을 입증하다",
  "disputation":"논쟁",
  "disputatious":"논쟁적인",
  "dispute":"이의를 제기하다; 논쟁",
  "dissertation":"논설; 학위 논문",
  "diverse":"다양한",
  "doddered":"(중풍이나 노령으로) 떠는",
  "doddering":"(중풍이나 노령으로) 떠는",
  "doting":"망령든; 지나치게 사랑하는",
  "effete":"쇠약해진",
  "effulgent":"빛나는",
  "flamboyant":"현란한",
  "hedge":"위험에 미리 대비하다",
  "host":"많은 사람; 주최자",
  "impotent":"무기력한",
  "incandescent":"백열광을 내는",
  "iridescent":"무지갯빛의",
  "lachrymal":"눈물의",
  "legion":"다수, 많은",
  "maudlin":"눈물 잘 흘리는, 감상적인",
  "mawkish":"몹시 감상적인",
  "monograph":"(특정 테마에 관한) 전공 논문",
  "multifaceted":"(문제·보석 등이) 많은 측면을 가진",
  "multifarious":"다방면의",
  "myriad":"무수한",
  "opalescent":"우윳빛을 내는",
  "passel":"꽤 큰 수, 집단(group)",
  "polemic":"논쟁을 좋아하는",
  "polemical":"논쟁을 좋아하는",
  "protean":"변화무쌍한; 다방면의",
  "prune":"(가지를)잘라 내다, 축소하다",
  "pugnacious":"싸움하기 좋아하는",
  "quarrelsome":"싸우기를 좋아하는",
  "radiant":"빛나는",
  "raft":"많은 수; 뗏목",
  "rebut":"논박하다",
  "refulgent":"환히 빛나는",
  "refute":"반박하다",
  "resplendent":"빛나는",
  "roomy":"널찍한",
  "scad":"많음, 다수, 다량",
  "scrappy":"툭하면 싸우는",
  "senile":"나이 많은",
  "shear":"(양의) 털을 깎다, (머리를) 깎다; 순전한",
  "shining":"반짝이는",
  "skit":"무리, 군중; 짧은 풍자",
  "slew":"다수, 대량",
  "spacious":"넓은",
  "spate":"대량, 다수; 홍수",
  "splendid":"빛나는",
  "thesis":"논문",
  "throng":"군중, 다수",
  "tract":"논문; (특히 종교·정치계의) 소책자",
  "treatise":"(학술) 논문",
  "trim":"-을 정돈하다, 손질하다",
  "versatile":"재주가 많은; (감정·기질 등이) 변하기 쉬운",
  "wad":"뭉치, 다발"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "121":"넓은",
  "122":"노쇠한, 노후한",
  "123":"논문",
  "124":"논박하다, 거짓임을 입증하다",
  "125":"논쟁을 좋아하는",
  "126":"눈물을 잘 흘리는, 지나치게 감상적인",
  "127":"눈부신, 번쩍번쩍 빛나는",
  "128":"다듬다, 깎다",
  "129":"다방면의, 다양한",
  "130":"다수, 다량, 많은 사람, 무리"
});
