// LOGIC TREE V502 — Categories 251-300 (manually verified)
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.categories.push(
  {id:"251",words:["ashamed", "bashful", "shamefaced", "shy"]},
  {id:"252",words:["bending", "flexible", "limber", "lissom", "lissome", "lithe", "pliable", "pliant", "supple"]},
  {id:"253",words:["pariah", "outcast", "outlaw", "ragamuffin", "waif"]},
  {id:"254",words:["addendum", "adjunct", "appendix", "appurtenance", "appendage", "concomitant", "codicil"]},
  {id:"255",words:["abnegate", "deprecate", "disapprobate", "disapprove", "disaffirm", "disown", "gainsay", "recant", "repeal", "reprobate", "rescind", "retract", "revoke"]},
  {id:"256",words:["affected", "contrived", "far-fetched", "labored", "mannered", "procrustean", "stereotyped", "strained", "unnatural"]},
  {id:"257",words:["amulet", "charm", "talisman"]},
  {id:"258",words:["sparse", "scanty", "scant", "meager", "scarce"]},
  {id:"259",words:["careless", "crude", "cursory", "delinquent", "derelict", "heedless", "inadvertent", "inattentive", "lax", "negligent", "perfunctory", "remiss", "slipshod", "supine"]},
  {id:"260",words:["unknowing", "unwitting", "unwittingly"]},
  {id:"261",words:["balloon", "bloat", "distend", "expand", "extend", "heave", "swell"]},
  {id:"262",words:["arrears", "liability", "obligation", "default", "insolvent"]},
  {id:"263",words:["regenerate", "rehabilitate", "resurrect", "resurge", "resuscitate", "retrieve"]},
  {id:"264",words:["cloister", "insulate", "isolate", "seclude", "segregate", "separate", "sequester", "wean", "disengage"]},
  {id:"265",words:["apportion", "allot", "allocate", "assign", "impart", "mete"]},
  {id:"266",words:["breach", "cavity", "chasm", "cleft", "cove", "crack", "crevice", "fission", "fissure", "hiatus", "interstice", "pit", "rift", "schism"]},
  {id:"267",words:["blasphemous", "irreverent", "impious", "profane", "sacrilegious"]},
  {id:"268",words:["biased", "colored", "discriminatory", "inequitable", "jaundiced", "partisan", "prejudiced", "unfair", "warped"]},
  {id:"269",words:["amputate", "cripple", "disable", "dismember", "hamstring", "incapacitate", "lame", "maim", "mutilate", "paralyze"]},
  {id:"270",words:["admonish", "counsel", "direct", "guide", "instruct", "prescribe", "recommend"]},
  {id:"271",words:["accident", "adversity", "calamity", "catastrophe", "disaster", "mischance", "misery", "misfortune", "mishap", "tragedy", "tribulation"]},
  {id:"272",words:["abhorrence", "abomination", "antipathy", "aversion", "disgust", "loathing", "malaise", "nausea", "odium", "repugnance", "repulsion", "revulsion"]},
  {id:"273",words:["aggravate", "annoy", "displease", "exasperate", "incense", "infuriate", "irk", "irritate", "needle", "nettle", "offend", "outrage", "peeve", "provoke", "rankle", "rile", "vex"]},
  {id:"274",words:["abominable", "awful", "detestable", "disgusting", "execrable", "foul", "hideous", "horrid", "loathsome", "nasty", "noxious", "objectionable", "obnoxious", "odious", "offensive", "repellent", "repugnant", "repulsive", "revolting", "sickening", "vile"]},
  {id:"275",words:["disaffect", "discontent", "disgruntle", "displease", "disquiet", "dissatisfy"]},
  {id:"276",words:["beef", "bellyache", "complain", "gripe", "grouch", "groan", "grumble", "kvetch", "murmur", "mutter", "repine", "whine"]},
  {id:"277",words:["demur", "demurral", "exception", "grouse", "objection", "protest", "remonstrance", "scruple", "squawk"]},
  {id:"278",words:["loner", "lone wolf", "maverick", "nonconformist", "recusant"]},
  {id:"279",words:["atrocity", "enormity", "evil", "heinousness", "knavery", "misdeed", "outrage", "rascality", "sin", "villainy", "wickedness", "wrongdoing"]},
  {id:"280",words:["base", "evil", "foul", "heinous", "knavish", "nefarious", "rascally", "reprobate", "sinful", "vicious", "villainous", "wicked", "wrong"]},
  {id:"281",words:["fecund", "fertile", "fructuous", "fruitful", "productive", "prolific"]},
  {id:"282",words:["abject", "base", "beggarly", "contemptible", "despicable", "ignoble", "lowly", "mean", "menial", "servile", "squalid", "vile"]},
  {id:"283",words:["dormant", "idle", "inactive", "inert", "passive", "sluggish", "stagnant", "static", "torpid"]},
  {id:"284",words:["absorb", "consume", "devour", "engulf", "imbibe", "ingest", "suck", "swallow", "take in"]},
  {id:"285",words:["arrant", "barefaced", "blatant", "bold", "brash", "brazen", "impudent", "insolent", "pert", "presumptuous", "saucy", "shameless", "unabashed"]},
  {id:"286",words:["brazenness", "chutzpah", "contumely", "effrontery", "gall", "hubris", "impudence", "insolence", "presumption", "rudeness", "smartness"]},
  {id:"287",words:["inflexible", "rigid", "stark", "stern", "stiff", "taut", "tense", "unyielding"]},
  {id:"288",words:["charlatan", "fake", "fraud", "imposter", "mountebank", "quack", "sham"]},
  {id:"289",words:["affirm", "allege", "assert", "asseverate", "aver", "avouch", "avow", "claim", "contend", "declare", "maintain", "predicate", "profess", "protest", "state", "swear", "vow"]},
  {id:"290",words:["disabuse", "disillusion", "enlighten", "set straight", "undeceive"]},
);
Object.assign(window.__V502_EXT__.categorySummaries,{
  "251":"\ubd80\ub044\ub7fc \ud0c0\ub294",
  "252":"\ubd80\ub4dc\ub7ec\uc6b4, \uc720\uc5f0\ud55c, \uad6c\ubd80\ub9ac\uae30 \uc26c\uc6b4",
  "253":"\ubd80\ub791\uc544, \ucd94\ubc29\uc790",
  "254":"\ubd80\uc18d\ubb3c, \uc885\uc18d\ubb3c, \ubd80\ub85d",
  "255":"\ubd80\uc778\ud558\ub2e4, \ubd80\uc815\ud558\ub2e4",
  "256":"\ubd80\uc790\uc5f0\uc2a4\ub7ec\uc6b4, \uc5b5\uc9c0\ub85c \uc9dc \ub9de\ucd98",
  "257":"\ubd80\uc801(\u7b26\u7c4d)",
  "258":"\ubd80\uc871\ud55c, \ube48\uc57d\ud55c",
  "259":"\ubd80\uc8fc\uc758\ud55c, \ud574\uc774\ud55c",
  "260":"\ubd80\uc9c0\ubd88\uc2dd\uac04\uc758(\uc5d0), \uc6b0\uc5f0\ud55c",
  "261":"\ubd80\ud480\ub9ac\ub2e4",
  "262":"\ubd80\ucc44",
  "263":"\ubd80\ud65c\uc2dc\ud0a4\ub2e4, \uc7ac\uc0dd\uc2dc\ud0a4\ub2e4",
  "264":"\ubd84\ub9ac\ud558\ub2e4, \ub5bc\uc5b4\ub193\ub2e4, \uaca9\ub9ac\uc2dc\ud0a4\ub2e4",
  "265":"\ubd84\ubc30\ud558\ub2e4",
  "266":"\ubd84\uc5f4, \ud2c8",
  "267":"\ubd88\uacbd\uc2a4\ub7ec\uc6b4, \uc2e0\uc131\ubaa8\ub3c5\uc758",
  "268":"\ubd88\uacf5\uc815\ud55c, \ud3b8\ud30c\uc801\uc778, \ud3b8\uacac\uc774 \uc788\ub294",
  "269":"\ubd88\uad6c\ub85c \ub9cc\ub4e4\ub2e4",
  "270":"\ubd88\ubaa8\uc758, \ud669\ud3d0\ud55c, \uc4f8\ubaa8\uc5c6\ub294, \uc644\uc804\ud788 \uacb0\ud54d\ub41c",
  "271":"\ubd88\uc6b4",
  "272":"\ubd88\ucf8c\uac10",
  "273":"\ubd88\ucf8c\ud558\uac8c \ud558\ub2e4",
  "274":"\ubd88\ucf8c\ud55c, \uc2eb\uc740",
  "275":"\ubd88\ud3c9\ud558\uac8c \ud558\ub2e4, \ubd88\ub9cc\uc744 \ud488\uac8c \ud558\ub2e4",
  "276":"\ubd88\ud3c9\ud558\ub2e4",
  "277":"\ubd88\ud22c\uba85\ud55c, \ud750\ub9b0, \ubd88\uba85\ub8cc\ud55c, \ubaa8\ud638\ud55c",
  "278":"\ube44 \uc21c\uc751\uc8fc\uc758\uc790, \ub3c5\ubd88\uc7a5\uad70",
  "279":"\ube44\uc5f4(\ud55c \ud589\ub3d9), \uc0ac\uc545(\ud55c \ud589\ub3d9)",
  "280":"\ube44\uc5f4\ud55c, \uc0ac\uc545\ud55c",
  "281":"\ube44\uc625\ud55c",
  "282":"\ube44\ucc9c\ud55c, \ube44\uc5f4\ud55c",
  "283":"\ube44\ud65c\ub3d9\uc801\uc778, \ud798\uc5c6\ub294, \ub3d9\uc791(\ubc18\uc751)\uc774 \ub290\ub9b0",
  "284":"\ube68\uc544\ub4e4\uc774\ub2e4",
  "285":"\ubed4\ubed4\uc2a4\ub7ec\uc6b4, \ucca0\uba74\ud53c\uc758, \ud6c4\uc548\ubb34\uce58\uc758",
  "286":"\ubed4\ubed4\uc2a4\ub7ec\uc6c0, \ucca0\uba74\ud53c, \ud6c4\uc548\ubb34\uce58",
  "287":"\ubee3\ubee3\ud55c, \uacbd\uc9c1\ub41c",
  "288":"\uc0ac\uae30\uafbc, \uac00\uc9dc \uc804\ubb38\uac00",
  "289":"\uc0ac\uc2e4\uc774\ub77c\uace0 \uc8fc\uc7a5\ud558\ub2e4, \ub2e8\uc5b8\ud558\ub2e4, \uacf5\ud45c\ud558\ub2e4",
  "290":"",
});

Object.assign(window.__V502_EXT__.confusionNotes,{
  "abhorrence":"ab(떨어져)+horr(떨다)+ence. 몸서리칠 정도의 혐오.",
  "abject":"ab(떨어져)+ject(던지다). 던져져 버려진; 비참하고 비열한.",
  "abnegate":"ab(떨어져)+neg(부정)+ate. 버리다; 자제하다; 부인하다.",
  "abomination":"abomin(혐오)+ation. 극도의 혐오감. 가증스러운 것.",
  "addendum":"add(더하다)+endum. 추록, 부록. 책 뒤에 추가되는 내용.",
  "adjunct":"ad(옆에)+junct(잇다). 부속물, 부가물. 조교(adjunct professor).",
  "allocate":"al+loc(장소)+ate. (자원을 특정 용도에) 배정하다.",
  "allot":"al(쪽으로)+lot(몫). (몫을) 할당하다, 배분하다.",
  "amputate":"am(주위)+put(자르다)+ate. (사지·신체 일부를) 절단하다.",
  "amulet":"부적. 액막이용 장신구.",
  "antipathy":"anti(반대)+pathy(감정). 반감, 적대적 혐오.",
  "appendix":"append(붙이다)+ix. 부록; 맹장. 책 끝에 붙는 추가 정보.",
  "apportion":"ap(쪽으로)+portion(몫). 할당하다, 분배하다. 비율에 따라.",
  "arrears":"ar(뒤로)+rear(뒤). 체납금, 밀린 빚. 'in arrears(체납 중)'.",
  "asseverate":"as(강화)+sever(진지한)+ate. 엄숙히 단언하다.",
  "atrocity":"atroc(잔혹한)+ity. 극악무도한 행위, 잔학 행위.",
  "aver":"ad(쪽으로)+verum(진실). 진실이라고 단언하다. 법률 용어.",
  "aversion":"a(떨어져)+version(돌리다). 돌아서게 하는 혐오, 반감.",
  "avouch":"a(쪽으로)+vouch(증언). 단언하다, 보증하다.",
  "avow":"a(쪽으로)+vow(맹세). 공개적으로 선언하다, 인정하다.",
  "balloon":"풍선처럼 부풀다. 급격히 증가하다. 'ballooning deficit'.",
  "bashful":"bash(부끄러워하다)+ful. 수줍음을 잘 타는. 'bashful smile'.",
  "blasphemous":"blasphemy(신성모독)+ous. 신을 모독하는, 불경한.",
  "blatant":"blat(울부짖다)+ant. 노골적이고 뻔뻔한. 'blatant lie(뻔한 거짓말)'.",
  "bloat":"부풀게 하다, 팽창시키다. bloated(부풀어 오른).",
  "brazen":"brazen(놋쇠의). 놋쇠처럼 뻔뻔한. 'brazen lie(뻔뻔한 거짓말)'.",
  "breach":"깨뜨림, 위반, 파열. 'breach of contract(계약 위반)'.",
  "calamity":"재난, 재앙. 대규모 피해를 동반한 비극.",
  "charlatan":"이탈리아어 ciarlare(수다 떨다). 돌팔이, 사기꾼 전문가.",
  "chasm":"깊게 갈라진 틈, 균열. 비유적 '커다란 간극'.",
  "cleft":"갈라진 틈. cleave(쪼개다)의 과거분사.",
  "cloister":"회랑, 수도원; 은둔시키다. 세상과 격리된.",
  "codicil":"codex(책)+il. 유언 보충서. 유언장에 추가되는 문서.",
  "contrived":"contrive(고안하다)+ed. 인위적인, 부자연스러운.",
  "crevice":"바위 틈, 갈라진 금. 좁고 깊은 틈새.",
  "delinquent":"de(완전히)+linqu(떠나다)+ent. 의무를 저버린. 비행 청소년.",
  "derelict":"de(완전히)+relict(남겨진). 버려진; 의무 태만의. 'derelict building'.",
  "disabuse":"dis(제거)+abuse(남용). 잘못된 믿음에서 깨우치다, 교정하다.",
  "discriminatory":"discriminate(차별하다)+ory. 차별적인.",
  "disengage":"dis(반대)+engage(관여하다). 연결을 풀다, 분리하다.",
  "disgruntle":"dis(강화)+gruntle(투덜거리다). 불평하게 하다, 심기를 상하게 하다.",
  "distend":"dis(떨어져)+tend(늘이다). (내부 압력으로) 팽창하다.",
  "dormant":"dorm(잠자다)+ant. 잠자고 있는, 휴면 상태의. 'dormant volcano'.",
  "engulf":"en+gulf(큰 구멍, 만). 삼키다, 휩싸다. 'engulfed in flames'.",
  "exasperate":"ex(완전히)+asper(거친)+ate. 몹시 화나게 하다.",
  "execrable":"execrate(저주하다)+able. 저주할 만한, 극도로 싫은.",
  "far-fetched":"멀리서 가져온. 억지로 꾸며낸, 부자연스러운.",
  "fecund":"비옥한, 다산의. fecundity(번식력). 땅·사람 모두에 씀.",
  "fissure":"갈라진 틈, 균열. 지질·의학 용어.",
  "flexible":"flex(구부리다)+ible. 유연한, 신축성 있는. 융통성 있는.",
  "foul":"더럽고 악취 나는; 반칙의(foul play). 날씨가 나쁜.",
  "fructuous":"fruct(열매)+uous. 열매 맺는; 생산적인.",
  "gripe":"쥐어짜다; 불평하다. 위경련(gripe)에서 유래.",
  "grouse":"불평하다, 투덜거리다. 뇌조(grouse) 뜻도.",
  "hamstring":"ham(오금)+string(줄). 오금을 끊다; 무력화하다.",
  "heave":"(가슴·파도 등이) 크게 부풀다, 밀려 올라오다.",
  "heinousness":"heinous(극악한)+ness. 증오스러울 정도로 사악함.",
  "hiatus":"틈, 중단, 휴지기. 'go on hiatus(휴지기에 들어가다)'.",
  "horrid":"horr(떨다)+id. 몹시 불쾌한, 끔찍한.",
  "imbibe":"im(안으로)+bibe(마시다). 마시다, 빨아들이다. 지식·사상을 흡수.",
  "inadvertent":"in(아닌)+advert(주의하다)+ent. 부주의한, 고의 아닌.",
  "incense":"in(위에)+cense(불타다). 불타오르게 하다, 격분시키다.",
  "infuriate":"in(안으로)+furi(분노)+ate. 격노하게 하다.",
  "insolvent":"in(아닌)+solvent(지급 능력 있는). 파산한, 지급 불능의.",
  "insulate":"insula(섬)+ate. 섬처럼 떼어놓다. 절연·단열·방음.",
  "irk":"짜증나게 하다, 귀찮게 하다. 가벼운 불쾌감.",
  "knavery":"knave(악한)+ry. 악당 짓, 사기.",
  "lax":"느슨한, 해이한. 규율이 엄격하지 않은.",
  "liability":"liable(책임 있는)+ity. 법적 부채, 채무. 책임(liability insurance).",
  "limber":"유연한, 부드러운. 운동 전 몸풀기(limber up).",
  "lissom":"lithesome의 변형. 유연하고 우아한. 춤추는 사람의 몸매.",
  "lithe":"유연하고 부드러운. 우아하게 구부러지는.",
  "loathing":"loath(혐오하다)+ing. 극심한 혐오, 구역질나는.",
  "loathsome":"loath(혐오)+some. 혐오스러운, 구역질나는.",
  "maim":"불구로 만들다. 심하게 다치게 하다. 주로 영구적 부상.",
  "maverick":"Samuel Maverick(소 목장 주인)에서. 낙인 없는 송아지; 독불장군.",
  "meager":"빈약한, 부족한. 살이 없는(meager body).",
  "mete":"(형벌·보상 따위를) 할당하다, 나누어 주다. 'mete out justice(정의를 집행하다)'.",
  "mischance":"mis(잘못된)+chance(기회). 불운, 재수 없는 사건.",
  "mountebank":"이탈리아어 monta in banco(벤치에 올라타다). 약장수, 사기꾼.",
  "mutilate":"(신체·문서를) 심하게 훼손하다, 절단하다.",
  "negligent":"neg(부정)+lig(선택하다)+ent. 태만한, 소홀한. 법적 과실.",
  "nettle":"쐐기풀(nettle)로 찌르다; 약오르게 하다.",
  "nonconformist":"non+conform(따르다)+ist. 관습에 따르지 않는 사람.",
  "obnoxious":"ob(쪽으로)+nox(해)+ious. 몹시 불쾌한, 눈에 거슬리는.",
  "odious":"odi(증오)+ous. 증오스러운, 혐오스러운.",
  "odium":"odi(증오)+um. 대중의 증오, 비난. 'odium of corruption(부패에 대한 공분)'.",
  "outlaw":"법의 보호 밖으로 내쫓긴 자. 무법자.",
  "pariah":"인도 타밀어 'paraiyar(북 치는 사람)'. 사회적 추방자.",
  "partisan":"part(편)+isan. 당파적인. 특정 편을 드는. 빨치산(partisan) 뜻도.",
  "perfunctory":"per(통해)+funct(수행하다)+ory. 형식적인, 마지못해 하는.",
  "pliable":"pli(접다)+able. 잘 구부러지는; 남의 말을 잘 듣는.",
  "pliant":"나긋나긋한, 유순한. pliable과 거의 동의어.",
  "predicate":"pre(앞서)+dicate(선언하다). 주장하다, 단언하다. 술부(문법).",
  "procrustean":"Procrustes(그리스 신화 강도). 지나치게 획일적인. 침대에 맞춰 다리를 자른.",
  "profane":"pro(앞)+fane(신전). 신성을 더럽히다; 세속적인.",
  "prolific":"proli(자손)+fic(만드는). 다작의, 다산의. 'prolific writer'.",
  "rankle":"고름이 생기듯 계속 마음을 괴롭히다. 'the insult rankled for years'.",
  "recant":"re(뒤로)+cant(노래하다). (주장·신앙을) 공개 철회하다. 갈릴레오.",
  "recusant":"re(반대)+cuse(이유)+ant. (종교적) 거부자, 비순응자.",
  "regenerate":"re(다시)+generate(생성하다). 재건하다, 회생시키다.",
  "remiss":"re(뒤로)+miss(보내다). 태만한, 소홀한.",
  "repellent":"repel(물리치다)+ent. 물리치는; 불쾌한, 혐오감을 주는.",
  "repine":"re(강화)+pine(시름). 불평하며 슬퍼하다.",
  "repugnance":"re(뒤로)+pugn(싸우다)+ance. 강한 반감, 위화감.",
  "repugnant":"re(반대)+pugn(싸우다)+ant. 위화감이 드는, 불쾌한.",
  "rescind":"re(뒤로)+scind(자르다). (법률·계약을) 폐지하다, 철회하다.",
  "resurrect":"re(다시)+surrection(일어나다). 부활시키다. 죽음에서 되살리다.",
  "resuscitate":"re+suscit(일으키다)+ate. 소생시키다. CPR로 심장을 되살리다.",
  "retract":"re(뒤로)+tract(끌다). (말·약속을) 철회하다. 오므리다.",
  "revoke":"re(뒤로)+voke(부르다). (명령·면허를) 취소하다.",
  "revolting":"revolt(반란)+ing. 반란을 일으키고 싶을 정도로 혐오스러운.",
  "revulsion":"re(뒤로)+vulsion(잡아당기다)+ion. 구역질 날 듯한 혐오.",
  "rile":"roil(휘저어 흐리게 하다)의 변형. 약올리다, 화나게 하다.",
  "sacrilegious":"sacrilege(신성모독)+ous. 신성한 것을 더럽히는.",
  "scarce":"희소한, 부족한. 공급이 수요를 못 따라가는.",
  "schism":"(종교·정당·단체의) 분열. 'Great Schism(교회 대분열)'.",
  "segregate":"se(떨어져)+greg(무리)+ate. 무리에서 분리하다. 인종 차별.",
  "sequester":"격리하다; (배심원을) 격리 수용하다. 재산 가압류.",
  "servile":"serv(노예)+ile. 노예 근성의, 굽실거리는.",
  "shamefaced":"shame+face. 숫기 없는, 부끄러워하는. shy의 격식어.",
  "shameless":"shame(부끄러움)+less. 부끄러움을 모르는, 파렴치한.",
  "stereotyped":"stereotype(정형). 판에 박힌, 정형화된.",
  "supine":"supine(반듯이 누운). 게으르게 누운; 무관심한.",
  "supple":"유연한; 순응성 있는. 'supple leather(부드러운 가죽)'.",
  "talisman":"신비한 힘이 깃든 부적. 행운을 가져다주는.",
  "torpid":"torp(마비)+id. 무감각하고 느린, 동면하는.",
  "tribulation":"tribul(찧다)+ation. 고난, 시련. 성경에서 자주 쓰임.",
  "unabashed":"un+abashed(부끄러워하지 않는). 당당하고 뻔뻔한.",
  "villainy":"villain(악당)+y. 악행, 범죄 행위.",
  "waif":"버려진 아이; 방랑자. 'waifs and strays(부랑아들)'.",
});
