// LOGIC TREE V502 — Categories 081-090
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"081",words:["annoy", "bother", "fret", "gall", "grate", "irk", "irritate", "molest", "nag", "nettle", "pester", "plague", "rankle", "rasp", "roil", "ruffle", "vex"]},
  {id:"082",words:["abstemious", "abstinent", "ascetic", "self-denying", "sober", "stoic", "moderate", "temperate"]},
  {id:"083",words:["arrant", "atrocious", "diabolical", "egregious", "enormous", "fell", "ferocious"]},
  {id:"084",words:["blackguard", "hoodlum", "hooligan", "knave", "malefactor", "miscreant", "rapscallion", "rascal", "reprobate", "rogue", "rowdy", "ruffian", "scoundrel", "strum", "villain"]},
  {id:"085",words:["busy", "industrious", "diligent", "assiduous", "sedulous"]},
  {id:"086",words:["agony", "angst", "anguish", "anxiety", "apprehension", "misgiving", "qualm"]},
  {id:"087",words:["crabbed", "illegible", "scribble"]},
  {id:"088",words:["financial", "fiscal", "monetary", "pecuniary"]},
  {id:"089",words:["debar", "enjoin", "inhibit", "interdict", "prohibit", "proscribe"]},
  {id:"090",words:["assail", "assault", "foray", "incursion", "invasion", "onslaught", "sally", "dash", "charge"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abstemious":"절제하는",
  "abstinent":"금욕적인",
  "agony":"고민, 고통",
  "angst":"불안한 마음",
  "anguish":"(심신의) 고통",
  "annoy":"괴롭히다",
  "anxiety":"걱정, 불안",
  "apprehension":"염려, 우려",
  "arrant":"악명 높은",
  "ascetic":"금욕주의자",
  "assail":"(사람·진지 등을 무력으로) 급습하다",
  "assault":"강습, 습격",
  "assiduous":"근면한; 주도면밀한",
  "atrocious":"흉악한",
  "blackguard":"깡패",
  "bother":"-을 괴롭히다",
  "busy":"(사람·두뇌가) 부지런히 일하는",
  "charge":"돌격하다",
  "crabbed":"심술궂은",
  "dash":"돌진하다",
  "debar":"(- 하는 것을) 방해하다",
  "diabolical":"악마의",
  "diligent":"부지런한",
  "egregious":"지독한",
  "enjoin":"금지하다",
  "enormous":"극악한",
  "fell":"잔인한",
  "ferocious":"사나운",
  "financial":"재정상의",
  "fiscal":"국고의",
  "foray":"약탈[침략]하다",
  "fret":"괴롭히다",
  "gall":"성나게 하다",
  "grate":"(신경·귀에) 거슬리다",
  "hoodlum":"건달",
  "hooligan":"무뢰한",
  "illegible":"읽기(판독하기) 어려운",
  "incursion":"(돌연한) 침입",
  "industrious":"근면한",
  "inhibit":"억제하다; 못하게 하다",
  "interdict":"금하다; 금지 명령",
  "invasion":"침입",
  "irk":"지치게 하다",
  "irritate":"짜증나게 하다",
  "knave":"악한",
  "malefactor":"죄인",
  "miscreant":"사악한",
  "misgiving":"걱정",
  "moderate":"삼가는",
  "molest":"(짓궂게) 괴롭히다",
  "monetary":"금융의",
  "nag":"(긴 잔소리로 귀찮게 하다)",
  "nettle":"화나게 하다",
  "onslaught":"돌격, 맹공격",
  "pecuniary":"재정상의",
  "pester":"고통을 주다",
  "plague":"귀찮은 일",
  "prohibit":"금지하다",
  "proscribe":"선거권을 박탈하다",
  "qualm":"(행동에 대한) 불안한 마음",
  "rankle":"-을 짜증나게 하다",
  "rapscallion":"악한",
  "rascal":"악당",
  "rasp":"신경을 거스르다",
  "reprobate":"비난하다; 타락한; 방탕아",
  "rogue":"악한; 광대; 개구쟁이",
  "roil":"(마음을) 어지럽히다",
  "rowdy":"난폭한 사람",
  "ruffian":"불량배, 악한",
  "ruffle":"뒤흔들다",
  "sally":"돌격하다",
  "scoundrel":"악당",
  "scribble":"휘갈겨 쓰다; 악필",
  "sedulous":"근면한, 공들인",
  "self-denying":"극기의",
  "sober":"절주하고 있는",
  "stoic":"금욕주의자",
  "strum":"깡패",
  "temperate":"중용의",
  "vex":"귀찮게 굴다",
  "villain":"(극·소설 따위의) 악역"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "081":"귀찮게 하다, 귀찮게 하여 화나게 하다, 괴롭히다",
  "082":"극기하는, 금욕하는",
  "083":"극악무도한, 잔인한, 악명 높은",
  "084":"극악무도한 사람, 악당, 깡패",
  "085":"근면한, 부지런한",
  "086":"근심, 걱정, 불안",
  "087":"글씨가 알아보기 힘든",
  "088":"금전상의, 재정상의",
  "089":"금지하다",
  "090":"급습, 습격(하다)"
});
