// LOGIC TREE V502 — Categories 131-140
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"131",words:["abdicate", "abjure", "abnegate", "abolish", "abrogate", "desist", "disclaim", "relinquish", "renounce", "repudiate", "waive"]},
  {id:"132",words:["disheveled", "dowdy", "sloppy", "slouchy", "slovenly", "unkempt", "untidy", "slouch", "sloven"]},
  {id:"133",words:["dapper", "groomed", "natty", "neat", "posh", "prim", "spruce", "trim", "preen", "primp", "prink"]},
  {id:"134",words:["drab", "harping", "humdrum", "monotonous", "tedious"]},
  {id:"135",words:["allay", "appease", "assuage", "comfort", "conciliate", "mollify", "pacify", "placate", "propitiate", "soothe"]},
  {id:"136",words:["disconsolate", "implacable", "inexorable", "merciless", "relentless", "ruthless", "unrelenting"]},
  {id:"137",words:["bale", "fare", "interest", "ransom", "toll", "tuition", "wage"]},
  {id:"138",words:["carnage", "decimation", "demolition", "holocaust", "massacre", "pogrom", "slaughter"]},
  {id:"139",words:["bonanza", "coup", "eclat"]},
  {id:"140",words:["glutton", "gormand", "gormandizer", "gourmand", "trencherman"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abdicate":"(권리 등을) 버리다, 포기하다",
  "abjure":"맹세하고 버리다",
  "abnegate":"버리다; 자제하다",
  "abolish":"(관례·제도 등을) 폐지하다",
  "abrogate":"(법률·습관 따위를) 폐지하다",
  "allay":"(고통·슬픔 등을) 누그러뜨리다",
  "appease":"달래다",
  "assuage":"진정시키다",
  "bale":"(운반용) 꾸러미, 더미",
  "bonanza":"노다지, 대성공",
  "carnage":"대량 학살",
  "comfort":"위로, 위안",
  "conciliate":"회유하다",
  "coup":"대성공; 쿠데타",
  "dapper":"말쑥한; 날렵한",
  "decimation":"다수의 인명을 앗음",
  "demolition":"해체; (특권 따위의) 타파",
  "desist":"그만두다, 중지하다",
  "disclaim":"(권리 등을) 포기하다",
  "disconsolate":"쓸쓸한",
  "disheveled":"단정치 못한",
  "dowdy":"(복장이) 초라한",
  "drab":"재미없는",
  "eclat":"대성공; 평판; 대단한 갈채",
  "fare":"transportation의 대가(교통요금)",
  "glutton":"대식가; 끈덕진 사나이",
  "gormand":"대식가",
  "gormandizer":"대식가, 식도락가",
  "gourmand":"대식가",
  "groomed":"-하게 차려 입은",
  "harping":"중언부언",
  "holocaust":"대학살",
  "humdrum":"평범한, 단조로운",
  "implacable":"확고한",
  "inexorable":"냉혹한; 변경할 수 없는",
  "interest":"이자(loan의 대가)",
  "massacre":"대량 학살",
  "merciless":"냉혹한",
  "mollify":"누그러지게 하다, 완화하다",
  "monotonous":"(소리·목소리가) 단조로운",
  "natty":"(복장·풍채가) 산뜻한",
  "neat":"(용모·모습 따위가) 균형 잡힌",
  "pacify":"달래다",
  "placate":"위로하다",
  "pogrom":"(소수 민족)학살; 유대인 학살",
  "posh":"(복장 등이) 우아한",
  "preen":"모양내다, 치장하다",
  "prim":"(복장 등을) 깔끔히 차려 입다",
  "primp":"(머리·복장 등을) 잘 다듬다",
  "prink":"화려하게 꾸미다",
  "propitiate":"비위를 맞추다; 회유하다",
  "ransom":"몸값(인질의 release의 대가)",
  "relentless":"끈질긴; 가차 없는",
  "relinquish":"(소유물 따위를) 포기하다",
  "renounce":"거부하다; 단념하다; 버리다",
  "repudiate":"거부하다",
  "ruthless":"무자비한",
  "slaughter":"대량 학살",
  "sloppy":"(언행·태도 등이) 깔끔치 못한",
  "slouch":"게으른 사람; 구부정한 걸음걸이",
  "slouchy":"단정치 못한; 게으른",
  "sloven":"꾀죄죄한 사람",
  "slovenly":"(옷차림이) 단정치 못한",
  "soothe":"(사람·감정을) 달래다",
  "spruce":"말쑥한, 멋진",
  "tedious":"지루한, 싫증나는; 장황한",
  "toll":"통행료(passage의 대가)",
  "trencherman":"대식가, 식객",
  "trim":"-을 정돈하다, 손질하다",
  "tuition":"수업료(instruction의 대가)",
  "unkempt":"단정하지 못한; 난잡한",
  "unrelenting":"끊임없는",
  "untidy":"말끔하지 않은; 흐트러진",
  "wage":"급료(work/labor의 대가)",
  "waive":"(권리·요구 등을) 포기하다, 철회하다"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "131":"(습관, 권리 등을) 단념하다, 그만두다",
  "132":"단정하지 못한, 꾀죄죄한",
  "133":"단정한, 깔끔한, 말쑥한",
  "134":"단조로운",
  "135":"달래다, 위로하다, 회유하다",
  "136":"달랠 수 없는, 무자비한",
  "137":"대가(代價)",
  "138":"대량학살",
  "139":"대성공",
  "140":"대식가"
});
