// LOGIC TREE V502 — Categories 141-200
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"141",words:["feculent", "filthy", "mangy", "mucky", "nasty", "sordid", "squalid", "humble", "ignoble", "ignominious", "vile"]},
  {id:"142",words:["immaculate", "innocent", "sterilized", "sterile", "unblemished", "unspotted", "unsullied", "untarnished"]},
  {id:"143",words:["adulterated", "contaminated", "defiled", "polluted", "tainted"]},
  {id:"144",words:["smirch", "besmirch", "bedraggle", "daub", "defile", "denigrate", "distain", "imbrue", "muck", "smear", "sully", "vitiate", "asperse", "calumniate", "carp", "cavil", "defame", "dent", "derogate", "inveigh", "libel", "malign", "rail", "reprobate", "revile", "slander", "traduce", "vilify"]},
  {id:"145",words:["ephemeral", "evanescent", "fleeting", "frail", "fugacious", "fugitive", "momentary", "transient", "transitory", "vanishing"]},
  {id:"146",words:["boulder", "cobble", "gravel", "pebble", "lapidary", "lapidify", "petrify", "petroglyph", "petrography", "petrology"]},
  {id:"147",words:["commensurate", "equivalent", "tantamount"]},
  {id:"148",words:["accede", "assent", "concede", "concord", "concur", "consent"]},
  {id:"149",words:["awesome", "conspicuous", "enormous", "notable", "noticeable", "pronounced", "redoubtable", "remarkable", "salient", "stupendous"]},
  {id:"150",words:["convolute", "hem", "wind"]},
  {id:"151",words:["bare", "bespeak", "betray", "blunder", "blab", "bolt", "blurt", "bruit", "debunk", "disclose", "divulge", "reveal", "snitch", "squeal", "tattle", "dig (up)", "disinter", "exhume", "unbury", "unearth", "adduce", "evince", "exemplify"]},
  {id:"152",words:["fretful", "nervous", "restive", "restless", "skittish"]},
  {id:"153",words:["club", "flail", "flog", "lash", "trounce", "welt", "whip"]},
  {id:"154",words:["shove", "jostle", "elbow", "push"]},
  {id:"155",words:["windfall", "serendipity", "fluke", "jackpot"]},
  {id:"156",words:["desiccated", "dehydrated", "parched", "scorched", "sear(ed)", "sere"]},
  {id:"157",words:["wizardry", "legerdemain", "prestidigitation", "jugglery", "thaumaturgy"]},
  {id:"158",words:["juggler", "prestidigitator", "thaumaturgist", "thaumaturge", "wizard"]},
  {id:"159",words:["bravado", "overboldness", "presumption", "rashness", "recklessness", "temerity"]},
  {id:"160",words:["glut", "gorge", "gratify", "humor", "satisfy", "slake"]},
  {id:"161",words:["impalpable", "intangible", "untouchable", "imperceptible", "unappreciable"]},
  {id:"162",words:["palpable", "tangible", "touchable", "perceptible", "appreciable"]},
  {id:"163",words:["acronym", "pleonasm", "oxymoron", "gaffe", "malapropism", "neologism", "archaism", "solecism", "periphrasis", "circumlocution", "euphemism", "hypocorism", "roundabout expression", "bouquet", "flattery", "blandishment", "hyperbole", "bombast", "grandiloquence", "pomposity", "fustian", "harangue", "tirade", "screed", "vituperation", "traducement", "billingsgate", "parlance", "phraseology", "equivoke", "equivoque", "pun", "technicality", "terminology"]},
  {id:"164",words:["desiccate", "dehydrate", "parch", "sear", "scorch"]},
  {id:"165",words:["annihilate", "carnage", "decimate", "demolish", "eradicate", "exterminate", "extirpate", "holocaust", "massacre", "sterilize"]},
  {id:"166",words:["hobble", "stutter", "stammer", "stumble"]},
  {id:"167",words:["babble", "gabble", "gibber", "jabber", "patter", "rattle"]},
  {id:"168",words:["equivocate", "prevaricate", "hedge", "palter", "quibble", "shuffle", "tergiversate", "waffle"]},
  {id:"169",words:["babble", "falter", "mumble", "murmur", "mutter", "drone", "chant", "prattle", "stammer", "stumble", "stutter"]},
  {id:"170",words:["amphigory", "babble", "balderdash", "blather", "drivel", "folderole", "fudge", "piffle", "prate", "prattle", "rig(a)marole", "trumpery", "twaddle"]},
  {id:"171",words:["babble", "blabber", "blather", "chatter", "drivel", "piffle", "prate", "prattle", "rattle", "twaddle"]},
  {id:"172",words:["chatty", "diffuse", "garrulous", "long-winded", "loquacious", "prolix", "redundant", "talkative", "verbose", "voluble", "wordy"]},
  {id:"173",words:["guarded", "reserved", "restrained", "smoldered", "standoffish", "stifled", "uncommunicative"]},
  {id:"174",words:["calm", "mum", "mute", "reserved", "reticent", "taciturn", "uncommunicative"]},
  {id:"175",words:["flavor", "gusto", "relish", "savor", "smack", "taste", "zest"]},
  {id:"176",words:["affable", "genial", "congenial", "bland", "gentle", "lenient", "mild", "suave"]},
  {id:"177",words:["insipid", "tasteless", "unpalatable", "unsavory", "vapid"]},
  {id:"178",words:["ambrosial", "delectable", "delicious", "mellifluous", "mellow", "palatable", "sapid", "tasteful"]},
  {id:"179",words:["acerb", "acerbic", "acid", "acidulent", "acidulous", "acrimonious", "caustic", "cutting", "edgy", "incisive", "mordant", "piquant", "pungent", "racy", "tangy", "trenchant", "truculent", "vitriolic"]},
  {id:"180",words:["blunder", "falter", "flicker", "hover", "linger", "oscillate", "palter", "resile", "scruple", "stagger", "vacillate", "waver", "irresolute", "indecisive"]},
  {id:"181",words:["abase", "abash", "humble", "humiliate", "mortify"]},
  {id:"182",words:["bribe", "corrupt", "lubricate", "suborn", "tamper", "corruptible", "mercenary", "venal"]},
  {id:"183",words:["absorb", "allure", "attract", "captivate", "douse", "enchant", "engage", "engross", "enrapture", "enthrall", "entrance", "fetch", "immerse", "inebriate", "infatuate", "intoxicate", "mesmerize", "preoccupy", "prepossess", "ravish", "rivet", "smite", "steep", "strike", "transfix", "transport"]},
  {id:"184",words:["abdicate", "abjure", "abnegate", "abolish", "abrogate", "desist", "disclaim", "relinquish"]},
  {id:"185",words:["bite", "chew", "chomp", "crunch", "munch", "gnaw", "gobble", "gorge", "gulp", "guzzle", "swill", "nibble", "quaff", "raven", "sip", "slurp", "swallow"]},
  {id:"186",words:["defunct", "extinct", "extant"]},
  {id:"187",words:["inventory", "manifest", "necrology", "roll", "roster", "rota", "slate"]},
  {id:"188",words:["behest", "decree", "edict", "fiat", "injunction", "mandate", "ordain"]},
  {id:"189",words:["acute", "agile", "argute", "astute", "brilliant", "canny", "keen", "longheaded", "perspicacious", "sagacious", "sapient", "shrewd", "smart"]},
  {id:"190",words:["cogitate", "contemplate", "meditate", "muse", "opine", "ponder", "pore", "ruminate", "speculate"]},
  {id:"191",words:["demonstrative", "explicit", "express", "overt"]},
  {id:"192",words:["affront", "disgrace", "dishonor", "indignity"]},
  {id:"193",words:["derogative", "derogatory", "pejorative"]},
  {id:"194",words:["defame", "defile", "denigrate", "derogate", "smear", "smirch", "besmirch", "muck", "vilify", "vitiate", "sully", "compromise", "becloud", "grime", "begrime", "asperse", "calumniate"]},
  {id:"195",words:["agnomen", "alias", "appellation", "cognomen", "denomination", "diminutive", "hypocorism", "epithet", "incognito", "misnomer", "moniker", "nomenclature", "pseudonym", "sobriquet", "vernacular"]},
  {id:"196",words:["accumulate", "amass", "garner", "hoard"]},
  {id:"197",words:["ambiguous", "equivocal", "hazy", "murky", "nebulous", "obscure", "opaque", "turbid", "vague"]},
  {id:"198",words:["raucous", "hoarse", "gruff"]},
  {id:"199",words:["confiscate", "sequester", "sequestrate", "mulct", "forfeit", "levy", "impound"]},
  {id:"200",words:["apathetic", "callous", "impassive", "indifferent", "lethargic"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abase":"깎아내리다",
  "abash":"-을 부끄럽게 하다",
  "abdicate":"(권리 등을) 버리다, 포기하다",
  "abjure":"맹세하고 버리다",
  "abnegate":"버리다; 자제하다",
  "abolish":"(관례·제도 등을) 폐지하다",
  "abrogate":"(법률·습관 따위를) 폐지하다",
  "absorb":"흡수하다",
  "accede":"(요구 등에) 동의하다",
  "accumulate":"(재산 따위를) 축적하다",
  "acerb":"(기질·태도 등이) 거친",
  "acerbic":"(기질·태도 등이) 거친",
  "acid":"신랄한",
  "acidulent":"신랄한; 다소 신맛이 도는",
  "acidulous":"신랄한",
  "acrimonious":"매서운, 신랄한",
  "acronym":"두문자어",
  "acute":"혜안의, 명민한",
  "adduce":"(이유·증거 따위를) 제시하다",
  "adulterated":"(-을 타서) 품질을 떨어뜨린",
  "affable":"상냥한",
  "affront":"과감히 맞서다; 모욕하다; 모욕",
  "agile":"기민한; 날렵한",
  "agnomen":"별명",
  "alias":"가명",
  "allure":"마음을 끌다",
  "amass":"(긁어) 모으다",
  "ambiguous":"애매한",
  "ambrosial":"아주 맛 좋은",
  "amphigory":"무의미하고 우스운 글",
  "annihilate":"전멸시키다",
  "apathetic":"냉담한",
  "appellation":"명칭",
  "appreciable":"감지할 수 있을 정도의",
  "archaism":"고어",
  "argute":"빈틈없는",
  "asperse":"험담하다",
  "assent":"찬성하다; 찬성",
  "astute":"기민한",
  "attract":"-의 마음을 끌다",
  "awesome":"경탄할 만한",
  "babble":"쓸데없는 말을 하다",
  "balderdash":"같잖은 소리",
  "bare":"(비밀·마음 등을) 털어놓다, 폭로하다",
  "becloud":"흐리게 하다",
  "bedraggle":"더럽히다",
  "begrime":"(연기·때로) 더럽히다",
  "behest":"명령",
  "besmirch":"더럽히다; (명예)를 손상하다",
  "bespeak":"-을 나타내다, 보이다",
  "betray":"(감정·무지·약점·특징 따위를)",
  "billingsgate":"런던의 어시장; 악담",
  "bite":"베어 물다",
  "blab":"무심코 비밀 따위를 폭로하다",
  "blabber":"헛소리를 지껄이다",
  "bland":"(말·태도가) 온화한, 부드러운",
  "blandishment":"아첨하는 말",
  "blather":"재잘거리다",
  "blunder":"(비밀 등을) 무심코 입 밖에 내다",
  "blurt":"무심코 비밀 따위를 폭로하다",
  "bolt":"무심코 비밀 따위를 폭로하다",
  "bombast":"과장하는 말",
  "boulder":"커다란 반석",
  "bouquet":"아첨하는 말",
  "bravado":"허세",
  "bribe":"매수하다",
  "brilliant":"두뇌가 날카로운",
  "bruit":"소문을 널리 퍼뜨리다",
  "callous":"무감각한, 냉담한",
  "calm":"조용한",
  "calumniate":"중상하다",
  "canny":"현명한",
  "captivate":"(마음 따위)를 붙잡다",
  "carnage":"대량 학살",
  "carp":"투덜거리다; 잉어",
  "caustic":"신랄한",
  "cavil":"트집을 잡다",
  "chant":"(단순하고 반복적인 곡조를) 부르다",
  "chatter":"재잘거리다",
  "chatty":"수다스러운",
  "chew":"어금니로 씹다",
  "chomp":"우적우적 깨물다",
  "circumlocution":"완곡어법",
  "club":"곤봉으로 치다",
  "cobble":"자갈, 조약돌",
  "cogitate":"숙고하다",
  "cognomen":"이름, 별명",
  "commensurate":"같은 양의",
  "compromise":"(명성·신용 등을) 더럽히다",
  "concede":"인정하다; 양보하다",
  "concord":"(의견·이해의) 일치",
  "concur":"의견 일치를 보다",
  "confiscate":"몰수하다",
  "congenial":"(사람이) 마음이 맞는",
  "consent":"동의하다; 동의",
  "conspicuous":"눈에 띄는",
  "contaminated":"(접촉하여) 더럽혀진",
  "contemplate":"심사숙고하다",
  "convolute":"둘둘 감다",
  "corrupt":"부정한",
  "corruptible":"부패하기 쉬운",
  "crunch":"아삭아삭 깨물다",
  "cutting":"예리한, 통렬한",
  "daub":"더럽히다",
  "debunk":"(정체를) 폭로하다",
  "decimate":"많은 사람을 죽이다",
  "decree":"법령",
  "defame":"비방하다, 중상하다",
  "defile":"(신성을) 모독하다",
  "defunct":"죽은",
  "dehydrate":"수분을 제거하다",
  "dehydrated":"탈수증세를 보이는",
  "delectable":"즐거운, 기쁜",
  "delicious":"아주 맛있는",
  "demolish":"(건물 따위를) 부수다",
  "demonstrative":"심정을 토로하는",
  "denigrate":"(인격·명예 등을) 훼손하다",
  "denomination":"명명, 화폐의 명칭",
  "dent":"(명성 따위에) 흠을 안기다",
  "derogate":"(가치·명예 따위를) 훼손하다",
  "derogative":"명예를 손상하는",
  "derogatory":"(명예·인격 따위를) 손상시키는",
  "desiccate":"건조시키다",
  "desiccated":"(풍토 등이) 건조한",
  "desist":"그만두다, 중지하다",
  "diffuse":"말(수가) 많은",
  "dig (up)":"진실을 탐구하다, 찾아내다",
  "diminutive":"소형의, 작은",
  "disclaim":"(권리 등을) 포기하다",
  "disclose":"(비밀을) 들추어내다, 폭로하다",
  "disgrace":"불명예",
  "dishonor":"불명예",
  "disinter":"(숨겨진 곳에서) 드러내다",
  "distain":"명예를 손상시키다; 변색시키다",
  "divulge":"(비밀을) 누설하다, 밝히다",
  "douse":"-에 물을 끼얹다",
  "drivel":"쓸데없는 말",
  "drone":"단조로운(monotonous) 어조로 말하다",
  "edgy":"가시 돋친, 신랄한",
  "edict":"(옛날의) 칙령",
  "elbow":"팔꿈치로 밀다",
  "enchant":"매혹하다",
  "engage":"-의 마음을 끌다",
  "engross":"(마음을) 빼앗다",
  "enormous":"극악한",
  "enrapture":"황홀케 하다",
  "enthrall":"마음을 사로잡다",
  "entrance":"황홀하게 하다",
  "ephemeral":"덧없는",
  "epithet":"별명, 통칭",
  "equivalent":"동등한, 같은",
  "equivocal":"(뜻이) 모호한; 다의적인",
  "equivocate":"속이기 위해 모호하게 말하다",
  "equivoke":"재담",
  "equivoque":"재담",
  "eradicate":"박멸하다",
  "euphemism":"완곡어법",
  "evanescent":"(김처럼) 사라지는, 순간의",
  "evince":"(감정 따위를) 분명히 나타내다; 명시하다",
  "exemplify":"예증하다",
  "exhume":"(숨은 인재·명작 등을) 찾아내다,",
  "explicit":"소설 등의 대미",
  "exterminate":"몰살시키다",
  "extinct":"(인종, 동식물 따위가) 멸종한",
  "extirpate":"근절시키다",
  "falter":"멈칫하다",
  "feculent":"탁한, 더러운",
  "fetch":"추론하다",
  "fiat":"(권위에 의한) 명령",
  "filthy":"불결한",
  "flail":"도리깨질하다; 연속으로 때리다",
  "flattery":"아첨하는 말",
  "flavor":"맛",
  "fleeting":"쏜살같은, 덧없는",
  "flicker":"흔들리다",
  "flog":"매질하다",
  "fluke":"요행",
  "folderole":"헛소리",
  "forfeit":"(죄·과실 등에 의해 재산·권리를) 상실하다",
  "frail":"무른, (체질 등이) 약한",
  "fretful":"초조한",
  "fudge":"허튼소리를 하다",
  "fugacious":"덧없는; 변하기 쉬운",
  "fugitive":"일시적인; 탈주하는",
  "fustian":"(문장·말의) 과장",
  "gabble":"빨리 지껄이다",
  "gaffe":"실언, 실수",
  "garner":"곡창, (지혜·사상 따위의) 축적",
  "garrulous":"수다스러운",
  "genial":"(사람이) 마음이 맞는",
  "gentle":"가벼운, 순한",
  "gibber":"(흔히 공포에 질려) 횡설수설하다",
  "glut":"차고 넘침",
  "gnaw":"앞니로 갉다",
  "gobble":"게걸스럽게 먹다, 꿀꺽 삼키다",
  "gorge":"포식하다; 가득 채우다",
  "grandiloquence":"과장하는 말",
  "gratify":"기쁘게 하다; 만족시키다",
  "gravel":"자갈더미",
  "grime":"(연기·때로) 더럽히다",
  "gruff":"(소리·목소리가) 굵고 탁한",
  "guarded":"조심성 있는",
  "gulp":"벌컥벌컥 마시다, 꿀꺽꿀꺽 마시다",
  "gusto":"맛, 풍미",
  "guzzle":"벌컥벌컥 마시다, 폭음하다",
  "harangue":"꾸짖는 말",
  "hazy":"모호한",
  "hedge":"위험에 미리 대비하다",
  "hem":"(사람·물건·장소를) 에워싸다",
  "hoard":"축적",
  "hoarse":"쉰 목소리의",
  "hobble":"다리를 절다",
  "holocaust":"대학살",
  "hover":"주저하다",
  "humble":"(신분 등이) 천한; 겸손한",
  "humiliate":"창피를 주다",
  "humor":"-의 비위를 맞추다",
  "hyperbole":"과장하는 말",
  "hypocorism":"완곡어법",
  "ignoble":"비열한",
  "ignominious":"수치스러운",
  "imbrue":"(손·칼을) 더럽히다; 물들이다",
  "immaculate":"순결한",
  "immerse":"빠져들게 하다",
  "impalpable":"이해하기 어려운; 미세한",
  "impassive":"냉정한",
  "imperceptible":"감지할 수 없는",
  "impound":"(사람을) 가두다",
  "incisive":"날카로운, 통렬한",
  "incognito":"익명(의), 익명자",
  "indecisive":"결단성이 없는",
  "indifferent":"무관심한",
  "indignity":"수모",
  "inebriate":"취하게 하다",
  "infatuate":"얼빠지게 만들다; 매혹하다",
  "injunction":"명령",
  "innocent":"청정한, 순결한",
  "insipid":"싱거운, 맛없는",
  "intangible":"만져서 알 수 없는",
  "intoxicate":"취하게 하다",
  "inveigh":"통렬히 비난하다",
  "inventory":"상품(stock, merchandise)의 목록",
  "irresolute":"우유부단한",
  "jabber":"(흥분해서 알아듣기 힘들게) 지껄이다",
  "jackpot":"(뜻밖의) 대성공",
  "jostle":"(난폭하게) 떠밀다",
  "juggler":"요술쟁이",
  "jugglery":"요술, 마술",
  "keen":"날카로운, 예리한",
  "lapidary":"보석공, 돌의, 보석의",
  "lapidify":"돌이 되게 하다",
  "lash":"몹시 꾸짖다",
  "legerdemain":"(마술에 의한) 속임수",
  "lenient":"관대한",
  "lethargic":"노곤한, 무기력한",
  "levy":"(세금 따위를) 징수하다",
  "libel":"(문서로) 명예를 훼손하다; (문서에 의한)",
  "linger":"(꾸물거려) 시간이 걸리다",
  "long-winded":"장광설의, 이야기가 긴",
  "longheaded":"머리가 좋은; 선견지명이 있는",
  "loquacious":"말 많은",
  "lubricate":"뇌물을 주다",
  "malapropism":"어법상의 실수",
  "malign":"비방하다",
  "mandate":"(공식의) 명령",
  "mangy":"불결한, 옴이 오른",
  "manifest":"적하목록",
  "massacre":"대량 학살",
  "meditate":"숙려하다",
  "mellifluous":"감미로운",
  "mellow":"부드럽고 풍부한",
  "mercenary":"보수를 목적으로 하는",
  "mesmerize":"홀리게 하다",
  "mild":"(음식·음료가) 부드러운, 자극성이 없는",
  "misnomer":"이름 잘못 부르기(쓰기)",
  "momentary":"순간의, 잠깐의",
  "moniker":"별명",
  "mordant":"신랄한, 독설적인",
  "mortify":"굴욕감을 느끼게 하다",
  "muck":"더럽히다; 망쳐놓다",
  "mucky":"(수단이) 비열한",
  "mulct":"빼앗다, 사취하다",
  "mum":"잠자코 있는, 무언의",
  "mumble":"중얼거리다",
  "munch":"아삭아삭 깨물다",
  "murky":"(표현 따위가) 애매한",
  "murmur":"나직하게 속삭이다",
  "muse":"숙고하다",
  "mute":"무언의",
  "mutter":"중얼거리다, 투덜거리다",
  "nasty":"불쾌한",
  "nebulous":"애매한",
  "necrology":"사망자 명부, 사망기사",
  "neologism":"신조어",
  "nervous":"신경질적인; 흥분하기 쉬운",
  "nibble":"조금씩 야금야금 먹다",
  "nomenclature":"학명",
  "notable":"저명한, 유명한",
  "noticeable":"이목을 끄는; 현저한",
  "obscure":"모호한; 감추다",
  "opaque":"불투명한",
  "opine":"-라고 생각하다",
  "ordain":"(법률 등이) 규정하다",
  "oscillate":"(마음·의견 따위가) 동요하다",
  "overboldness":"지나친 대담함",
  "oxymoron":"모순어법",
  "palatable":"(음식 등이) 입에 맞는",
  "palpable":"손으로 만질 수 있는",
  "palter":"말끝을 흐리다",
  "parch":"바싹 말리다",
  "parched":"(특히 날씨가 더워서) 몹시 건조한",
  "parlance":"어투, 어조",
  "patter":"속사포처럼 내뱉는 말",
  "pebble":"둥근 자갈",
  "pejorative":"가치를 떨어뜨리는",
  "perceptible":"인지할 수 있는",
  "periphrasis":"완곡어법",
  "perspicacious":"총명한, 통찰력 있는",
  "petrify":"돌로 만들다, 경화시키다",
  "petroglyph":"암석화",
  "petrography":"암석 분류학",
  "petrology":"암석학",
  "phraseology":"어투, 어조; 전문용어",
  "piffle":"실없는 말을 지껄이다",
  "piquant":"(맛이 상큼하게) 톡 쏘는 듯한",
  "pleonasm":"장황한 표현",
  "pomposity":"과장하는 말",
  "ponder":"깊이 생각하다",
  "pore":"곰곰이 생각하다",
  "prate":"쓸데없는 소리하다",
  "prattle":"쓸데없는 말을 하다",
  "preoccupy":"마음을 빼앗다",
  "prepossess":"(인물·태도 따위가) 호의를 품게 하다",
  "prestidigitation":"마술, 눈속임 기술",
  "prestidigitator":"마법사",
  "presumption":"주제넘음",
  "prevaricate":"속이기 위해 모호하게 말하다",
  "prolix":"장황한; 지루한",
  "pronounced":"뚜렷한, 현저한",
  "pseudonym":"가명",
  "pun":"재담",
  "pungent":"(맛 따위가) 자극성의; 신랄한",
  "push":"밀다",
  "quaff":"단숨에 마시다, 들이키다",
  "quibble":"옥신각신하다, 억지스런 변명을 하다",
  "racy":"외설한, 음탕한",
  "rail":"욕을 퍼붓다, 악담하다",
  "rashness":"성급함, 무분별함",
  "rattle":"-에 대해 계속 떠벌리다",
  "raucous":"목이 쉰",
  "raven":"폭식하다",
  "ravish":"황홀하게 하다",
  "recklessness":"무모함",
  "redoubtable":"경외할 만한",
  "redundant":"(표현이) 불필요한",
  "relinquish":"(소유물 따위를) 포기하다",
  "relish":"맛, 풍미, 향기",
  "remarkable":"주목할 만한; 현저한",
  "reprobate":"비난하다; 타락한; 방탕아",
  "reserved":"말없는, 내성적인",
  "resile":"주저하다, 회피하다 (from)",
  "restive":"고집 센",
  "restless":"침착하지 못한",
  "restrained":"삼가는, 자제하는",
  "reticent":"과묵한",
  "reveal":"(알려지지 않은 것을) 드러내다",
  "revile":"매도하다",
  "rig(a)marole":"횡설수설; (불필요하게 길고) 복잡한 절차",
  "rivet":"고정시키다; 매혹시키다",
  "roll":"명부",
  "roster":"근무(당번)표",
  "rota":"당번 명부",
  "roundabout expression":"완곡어법",
  "ruminate":"반추하다",
  "sagacious":"총명한",
  "salient":"현저한, 두드러진",
  "sapid":"강한 풍미가 있는",
  "sapient":"약은, 영리한",
  "satisfy":"만족시키다",
  "savor":"맛, 풍미; 흥미",
  "scorch":"살짝 태우다, 시들게 하다, 말라죽게 하다",
  "scorched":"탄, 그을은",
  "screed":"꾸짖는 말",
  "scruple":"(-하기를) 망설이다",
  "sear":"까맣게 그을리다, 태우다, 말리다, 시들게 하다",
  "sear(ed)":"(강한 불에 겉 부분을) 그슬다",
  "sequester":"격리시키다",
  "sequestrate":"몰수하다",
  "sere":"시든, 마른",
  "serendipity":"운 좋게 발견한 것",
  "shove":"밀치다",
  "shrewd":"영리한",
  "shuffle":"모호한 태도(말)로 난처함을 피하다",
  "sip":"조금씩 홀짝홀짝 마시다",
  "skittish":"겁이 많은",
  "slake":"(굶주림·욕망 따위를) 채우다",
  "slander":"중상모략하다; 중상",
  "slate":"(책 따위를) 혹평하다",
  "slurp":"소리 내어 먹다 (마시다)",
  "smack":"맛, 풍미",
  "smart":"잘난 체하는, 건방진; 분개(憤慨)하다",
  "smear":"더럽히다; (기름 따위를) 바르다",
  "smirch":"더럽히다; (명예)를 손상하다",
  "smite":"매혹시키다; 세게 때리다",
  "smoldered":"(감정이) 사무치는",
  "snitch":"밀고하다",
  "sobriquet":"별명, 가명",
  "solecism":"어법상의 오류",
  "sordid":"지저분한; 심보가 더러운",
  "speculate":"-에 관해 사색하다",
  "squalid":"더러운",
  "squeal":"밀고하다",
  "stagger":"망설이다, 주저하다",
  "stammer":"말을 더듬다",
  "standoffish":"(남에게) 쌀쌀한, 냉담한",
  "steep":"(액체에) 적시다, 담그다",
  "sterile":"흉작의; 자식을 못 낳는, 불임의",
  "sterilize":"(토질을) 불모(不毛)로 만들다",
  "sterilized":"살균한",
  "stifled":"(감정 등이) 억눌러진",
  "strike":"-에 몰두하다, 반하다",
  "stumble":"(말·글 읽기·연주를 하다가) 더듬거리다",
  "stupendous":"엄청나게 큰",
  "stutter":"말을 더듬다",
  "suave":"입에 순한, 자극성이 없는",
  "suborn":"매수하다",
  "sully":"(명예 따위를) 훼손하다",
  "swallow":"마시다, 들이키다, 삼키다",
  "swill":"벌컥벌컥 마시다, 폭음하다",
  "taciturn":"말없는",
  "talkative":"이야기하기 좋아하는",
  "tamper":"뇌물을 주다",
  "tangible":"만져서 알 수 있는; 실체적인",
  "tangy":"(맛이) 짜릿한, (냄새가) 톡 쏘는",
  "tantamount":"동등한, 상당하는(equal)",
  "taste":"미각",
  "tasteful":"감식력이 있는",
  "tasteless":"맛없는",
  "tattle":"고자질하다",
  "technicality":"전문용어",
  "temerity":"만용",
  "tergiversate":"속이기 위해 얼버무리다",
  "terminology":"전문용어",
  "thaumaturge":"요술사",
  "thaumaturgist":"요술사",
  "thaumaturgy":"요술, 마술",
  "tirade":"꾸짖는 말",
  "touchable":"만져 알 수 있는",
  "traduce":"비방하다",
  "traducement":"악담",
  "transfix":"선 채로 그 자리에 꼼짝 못하게 하다",
  "transient":"일시적인; 변하기 쉬운",
  "transitory":"일시적인, 무상한",
  "transport":"황홀하게 만들다; 수송하다",
  "trenchant":"(말 따위가) 통렬한",
  "trounce":"호되게 패주다; 혼내주다",
  "truculent":"공격적인",
  "trumpery":"허튼 소리",
  "turbid":"흐린",
  "twaddle":"실없는 소리하다",
  "unappreciable":"너무 작아서 인지할 수 없는",
  "unblemished":"흠이 없는",
  "unbury":"무덤에서 파내다; 발굴하다",
  "uncommunicative":"말을 잘 안하는",
  "unearth":"발견하다; (음모 따위를) 밝혀내다",
  "unpalatable":"입에 맞지 않는; 맛없는",
  "unsavory":"맛이 좋지 않은",
  "unspotted":"오점이 없는",
  "unsullied":"더럽혀지지 않은",
  "untarnished":"변색하지 않은",
  "untouchable":"실체가 없는",
  "vacillate":"망설이다",
  "vague":"막연한, 애매한",
  "vanishing":"사라지는",
  "vapid":"맛이 없는",
  "venal":"매수할 수 있는",
  "verbose":"말이 많은",
  "vernacular":"학명이 아닌 통칭, 속명; 모국어(사투리)로 쓴",
  "vile":"비열한",
  "vilify":"비난하다",
  "vitiate":"-의 가치를 떨어뜨리다",
  "vitriolic":"(언어·논평이) 독설에 찬",
  "vituperation":"호통",
  "voluble":"말 잘하는, 수다스러운",
  "waffle":"이해하기 어렵게 쓰거나 말하다",
  "waver":"결정을 못 하다",
  "welt":"때리다",
  "whip":"채찍질하다",
  "wind":"나선상을 이루다, 휘감기다",
  "windfall":"(유산 등의) 예기치 못한 횡재",
  "wizard":"마법사",
  "wizardry":"신기, 묘기",
  "wordy":"말 많은, 장황한",
  "zest":"풍미, 맛; 향미"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "141":"더러운, 비천한",
  "142":"더럽혀지지 않은",
  "143":"더럽혀진",
  "144":"더럽히다, 명예를 손상시키다",
  "145":"덧없는, 일시적인",
  "147":"동연의, 같은 크기(무게, 부피, 가치)의",
  "148":"동의하다",
  "149":"두드러진, 눈에 띄는",
  "150":"둘둘 말다",
  "151":"드러내다, 밝혀내다, 폭로하다",
  "152":"들뜬, 차분하지 못한",
  "153":"때리다",
  "154":"떠밀다",
  "155":"뜻밖의 행운",
  "156":"마른, 물기가 없는",
  "157":"마법, 마술",
  "158":"마법사, 마술사",
  "160":"만족시키다",
  "161":"(손으로) 만질 수 없는, 실체가 없는",
  "162":"(손으로) 마질 수 있는, 인지할 수 있는",
  "163":"말, 어법",
  "164":"말리다, 바싹 마르게 하다",
  "165":"말살하다, 박멸하다",
  "166":"말을 더듬다",
  "167":"말을 알아듣지 못하도록 빠르게 재잘대다",
  "168":"말을 얼버무리다, 모호하게 말하다, 핑계를 대다",
  "169":"말을 불분명하게 중얼거리다",
  "170":"(쓸데없는/의미 없는) 말",
  "171":"(쓸데없는/의미 없는) 말을 늘어놓다",
  "172":"말이 많은, 장황한",
  "173":"말(행동)이 신중한, 감정을 드러내지 않는",
  "174":"말이 없는, 과묵한",
  "175":"맛, 풍미, 재미",
  "176":"맛이 순한",
  "177":"맛이 없는",
  "178":"맛이 있는",
  "179":"(맛, 태도, 언행이) 신랄한, 통렬한, 자극적인",
  "180":"망설이다, 주저하다",
  "181":"망신을 주다",
  "182":"매수하다, 타락시키다",
  "183":"매혹시키다, 넋을 빼앗다, 몰두하게 하다",
  "184":"(습관/종교/신념 따위를) 맹세코 끊다",
  "185":"먹고 마시는 모양",
  "186":"멸종한, 생존해 있는 (extant)",
  "187":"명단, 명부",
  "188":"명령, 엄명",
  "189":"명민한, 총명한",
  "190":"명상하다, 숙고하다",
  "191":"명시적인, 터놓고 말하는",
  "192":"명예손상, 불명예",
  "193":"명예를 손상시키는, 불명예스러운",
  "194":"명예를 손상시키다, 가치를 떨어뜨리다",
  "195":"명칭, 별명, 가명",
  "196":"모아두다, 쌓아두다",
  "197":"모호한",
  "198":"목이 쉰",
  "199":"몰수(압수)하다, 징수(징병, 징발, 부과)하다",
  "200":"무관심한, 냉담한, 무감동한, 무감각한"
});
