// LOGIC TREE V502 — Categories 021-030
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"021",words:["rebuff", "snort", "snub", "spurn", "repel", "repulse"]},
  {id:"022",words:["healthful", "salubrious", "salutary", "salutiferous", "wholesome", "advantageous", "auspicious", "beneficial", "benign", "favorable", "lucrative", "profitable", "propitious", "toward"]},
  {id:"023",words:["bustle", "gallop", "rustle", "scurry", "scuttle", "trot", "scamp", "amble", "canter", "lope", "slither", "lumber", "waddle", "flit", "plod", "trudge", "flop", "scuff", "shuffle", "gambol", "dally", "dawdle"]},
  {id:"024",words:["cowardice", "cravenness", "funk", "timidity", "timorousness", "trepidation"]},
  {id:"025",words:["caitiff", "cowardly", "craven", "poltroon", "pusillanimous", "recreant", "sissy", "skittish", "timid", "timorous", "trepid"]},
  {id:"026",words:["balk", "boggle", "cower", "cringe"]},
  {id:"027",words:["audacious", "bold", "dauntless", "fearless", "intrepid", "brash", "rash", "foolhardy", "headlong", "impetuous", "imprudent", "impulsive", "overbold", "reckless", "bravado", "overboldness", "temerity", "gallantry", "grit", "guts", "mettle"]},
  {id:"028",words:["caitiff", "coward", "craven", "dastard", "funk", "poltroon", "recreant", "sissy"]},
  {id:"029",words:["bluster", "browbeat", "bully", "daunt", "dismay", "hector", "intimidate", "menace", "threaten"]},
  {id:"030",words:["garish", "gaudy", "gewgaw", "loud"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "advantageous":"이로운",
  "amble":"(말이) 천천히 걷다",
  "audacious":"대담한",
  "auspicious":"길조의",
  "balk":"멈칫거리다",
  "beneficial":"유익한",
  "benign":"양성의",
  "bluster":"엄포를 놓다",
  "boggle":"주춤하다",
  "bold":"용감한",
  "brash":"경솔한",
  "bravado":"허세",
  "browbeat":"협박[겁박]하다",
  "bully":"괴롭히다",
  "bustle":"(말이) 빠르게 걷다",
  "caitiff":"겁쟁이",
  "canter":"(말이) 천천히 뛰다",
  "coward":"비겁자",
  "cowardice":"겁",
  "cowardly":"겁이 많은",
  "cower":"(겁먹고) 몸을 숙이다",
  "craven":"용기 없는",
  "cravenness":"소심함",
  "cringe":"움츠리다",
  "dally":"미적거리다",
  "dastard":"비겁자",
  "daunt":"겁먹게 하다",
  "dauntless":"불굴의, 겁 없는",
  "dawdle":"꾸물거리다",
  "dismay":"실망시키다; 실망",
  "favorable":"호의적인",
  "fearless":"대담무쌍한",
  "flit":"(새가) 훨훨 날다; 가볍고 빠르게 지나가다",
  "flop":"발걸음이 무겁게 터덕터덕 걷다",
  "foolhardy":"무모한",
  "funk":"공포; 겁쟁이",
  "gallantry":"용맹",
  "gallop":"(말이) 빠르게 뛰다",
  "gambol":"껑충껑충 (천천히) 뛰다",
  "garish":"야한",
  "gaudy":"천박한",
  "gewgaw":"겉만 번지르르한",
  "grit":"투지, 기개",
  "guts":"배짱",
  "headlong":"성급한, 저돌적인",
  "healthful":"건강에 좋은",
  "hector":"위협하다",
  "impetuous":"성급한",
  "imprudent":"경솔한",
  "impulsive":"충동적인",
  "intimidate":"겁을 주다",
  "intrepid":"두려움을 모르는",
  "lope":"(말이) 천천히 뛰다",
  "loud":"야한",
  "lucrative":"금전적으로 유리한, 수지가 맞는",
  "lumber":"(곰이) 쿵쿵거리며 걷다; 무겁게 움직이다",
  "menace":"위협하다",
  "mettle":"패기",
  "overbold":"지나치게 대담한",
  "overboldness":"지나친 대담함",
  "plod":"발을 질질 끌며 터벅터벅 걷다",
  "poltroon":"겁쟁이",
  "profitable":"수익성이 있는",
  "propitious":"길조의",
  "pusillanimous":"겁 많은",
  "rash":"성급한",
  "rebuff":"퇴짜(하다)",
  "reckless":"무모한",
  "recreant":"용기 없는",
  "repel":"격퇴하다",
  "repulse":"물리치다",
  "rustle":"가죽을 훔치다",
  "salubrious":"살기 좋은",
  "salutary":"유익한",
  "salutiferous":"건강에 유익한",
  "scamp":"(말이) 빠르게 걷다",
  "scuff":"발을 질질 끌다",
  "scurry":"빠르게 달리다",
  "scuttle":"(말이) 빠르게 걷다",
  "shuffle":"모호한 태도(말)로 난처함을 피하다",
  "sissy":"유약한",
  "skittish":"겁이 많은",
  "slither":"(뱀이) 미끄러지듯 기어가다",
  "snort":"콧방귀를 뀌다",
  "snub":"무시하다",
  "spurn":"퇴짜 놓다",
  "temerity":"만용",
  "threaten":"협박[겁박]하다",
  "timid":"소심한",
  "timidity":"겁 많음",
  "timorous":"겁이 많은",
  "timorousness":"무서워함",
  "toward":"우호적인",
  "trepid":"소심한",
  "trepidation":"두려움",
  "trot":"(말이) 빠르게 걷다",
  "trudge":"무거운 걸음으로 터벅터벅 걷다",
  "waddle":"(오리나 거위가) 뒤뚱뒤뚱 걸어가다",
  "wholesome":"건강에 좋은"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "021":"(무례하게) 거절하다, 퇴짜를 놓다",
  "022":"건강에 좋은, 유익한",
  "023":"걷는 모양",
  "024":"겁, 소심",
  "025":"겁 많은, 비겁한",
  "026":"겁먹다, 움츠리다, 움찔하다, 주눅 들다",
  "027":"겁이 없는",
  "028":"겁쟁이, 비겁한 사람",
  "029":"겁주다, 협박하다",
  "030":"겉만 번지르르한 싸구려의, 값싸고 야한"
});
