// LOGIC TREE V502 — Categories 041-050
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"041",words:["awesome", "prodigious", "redoubtable"]},
  {id:"042",words:["baffle", "balk", "blight", "damp", "dampen", "discomfit", "disconcert", "discourage", "foil", "founder", "mar", "muddle"]},
  {id:"043",words:["aristocratic", "eminent", "exalted", "grandiose", "lofty", "virtuous"]},
  {id:"044",words:["lull", "pacify", "paregorize", "placate", "sedate"]},
  {id:"045",words:["halcyon", "hushed", "calm", "equable", "placid", "sedate", "serene", "tranquil"]},
  {id:"046",words:["agitate", "discombobulate", "discompose", "disconcert", "disquiet", "disturb", "faze", "perturb", "roil", "ruffle"]},
  {id:"047",words:["chronic", "indelible", "ineradicable", "inexterminable", "ingrain(ed)", "inveterate"]},
  {id:"048",words:["contumacious", "crotchety", "disobedient", "dogged", "froward", "insubordinate", "intractable", "intransigent", "mulish", "obdurate", "obstinate", "obstreperous", "opinionated", "pertinacious", "perverse", "recalcitrant", "refractory", "restive"]},
  {id:"049",words:["affliction", "agony", "anguish", "distress", "ordeal", "throes", "torment", "torture", "travail", "tribulation", "woe"]},
  {id:"050",words:["aggravate", "embitter", "exacerbate", "aggrieve"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "affliction":"고통",
  "aggravate":"악화시키다",
  "aggrieve":"(사람을) 학대하다",
  "agitate":"심하게 움직이다",
  "agony":"고민, 고통",
  "anguish":"(심신의) 고통",
  "aristocratic":"귀족 정치의",
  "awesome":"경탄할 만한",
  "baffle":"좌절시키다",
  "balk":"멈칫거리다",
  "blight":"손상시키다",
  "calm":"조용한",
  "chronic":"만성의",
  "contumacious":"고집 센, 완고한",
  "crotchety":"변덕스러운",
  "damp":"풀이 죽게 하다",
  "dampen":"풀이 죽게 하다",
  "discombobulate":"혼란시키다",
  "discomfit":"(계획·목적을) 깨뜨리다, 좌절시키다",
  "discompose":"불안하게 하다",
  "disconcert":"당황하게 하다",
  "discourage":"용기를 잃게 하다",
  "disobedient":"순종치 않는",
  "disquiet":"불안하게 하다",
  "distress":"비탄, 고통",
  "disturb":"마음을 어지럽게 하다",
  "dogged":"완강한",
  "embitter":"한층 더 비참하게 하다",
  "eminent":"저명한",
  "equable":"한결같은",
  "exacerbate":"(고통·노여움 따위를) 악화시키다",
  "exalted":"우쭐한",
  "faze":"마음을 혼란시키다",
  "foil":"(특히 불법적인 것을) 좌절시키다",
  "founder":"(계획·사업 등이) 틀어지다",
  "froward":"완고한",
  "grandiose":"(과장된) 거창한",
  "halcyon":"고요한; 번영의",
  "hushed":"조용해진",
  "indelible":"지울 수 없는",
  "ineradicable":"근절할 수 없는, 뿌리 깊은",
  "inexterminable":"근절할 수 없는",
  "ingrain(ed)":"뿌리 깊은, 타고난",
  "insubordinate":"고분고분하지 않는",
  "intractable":"말을 듣지 않는",
  "intransigent":"타협하지 않는",
  "inveterate":"(감정·병이) 뿌리 깊은",
  "lofty":"고상한",
  "lull":"(비·바람·폭풍우 등의) 진정",
  "mar":"손상시키다",
  "muddle":"혼란시키다",
  "mulish":"고집 센",
  "obdurate":"억지 센",
  "obstinate":"완고한",
  "obstreperous":"제어할 수 없는",
  "opinionated":"자기주장을 고집하는",
  "ordeal":"호된 시련",
  "pacify":"달래다",
  "paregorize":"진정시키다",
  "pertinacious":"집요한",
  "perturb":"교란하다",
  "perverse":"외고집의",
  "placate":"위로하다",
  "placid":"평온한",
  "prodigious":"엄청난; 굉장한",
  "recalcitrant":"반항하는",
  "redoubtable":"경외할 만한",
  "refractory":"말을 안 듣는",
  "restive":"고집 센",
  "roil":"(마음을) 어지럽히다",
  "ruffle":"뒤흔들다",
  "sedate":"침착한",
  "serene":"잔잔한",
  "throes":"격통, 고민",
  "torment":"고통",
  "torture":"고문",
  "tranquil":"평온한",
  "travail":"고생, 노고",
  "tribulation":"고난, 고생",
  "virtuous":"덕이 높은",
  "woe":"비애, 비통"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "041":"경외감(존경심)을 불러일으키는",
  "042":"계획을 망쳐놓다, 좌절 시키다, 혼란하게하다",
  "043":"고귀한, 웅대한",
  "044":"고요하게 만들다, 진정시키다",
  "045":"고요한, 평온한",
  "046":"고요함(평온함, 냉정함)을 깨뜨리다, 동요시키다",
  "047":"고질적인, 뿌리 깊은",
  "048":"고집 센, 다루기 힘든",
  "049":"고통, 고난",
  "050":"(고통, 슬픔, 분노를) 더욱 크게 하다"
});
