// LOGIC TREE V502 — Categories 071-080
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};
window.__V502_EXT__.categories.push(
{id:"071",words:["bondage","coercion","cuff","custody","duress","incarceration","shackle","yoke"]},
{id:"072",words:["bridle","constrain","cramp","curb","detain","fetter","enfetter","enthrall","fasten","immure","impound","incarcerate","leash","manacle","rein","restrain","restrict","secure","shackle","tether"]},
{id:"073",words:["archaic","musty","obsolescent","obsolete","outmoded","passe"]},
{id:"074",words:["disentangle","extricate","unravel","untangle"]},
{id:"075",words:["capitulate","subside","succumb","yield"]},
{id:"076",words:["dearth","deficiency","destitution","exiguity","famine","impecuniosity","impecuniousness","impoverishment","indigence","paucity","penury","privation","scarcity"]},
{id:"077",words:["destitute","exiguous","impecunious","impoverished","indigent","needy","penurious"]},
{id:"078",words:["boredom","ennui","languor","lassitude","tedium","weariness"]},
{id:"079",words:["cacophonous","discordant","harsh","obtrusive","protrusive","raucous","shrill","strident","grating","raspy"]},
{id:"080",words:["annoying","fretful","irksome","pesky","plaguy","plaguey","plaguesome","troublesome","trying","gadfly","plague","pest","wasp","vermin"]}
);
Object.assign(window.__V502_EXT__.wordMeanings,{
bondage:"속박",coercion:"강제, 위압",cuff:"수갑",custody:"구금",duress:"구속",incarceration:"투옥하다",shackle:"-에 쇠고랑을 채우다",yoke:"속박, 지배",
bridle:"-에 굴레를 씌우다",constrain:"구속하다",cramp:"제한하다, 가두다",curb:"억제하다, 구속하다",detain:"붙들어 두다, 구금하다",fetter:"속박하다, 노예로 만들다",enfetter:"속박하다, 노예로 만들다",enthrall:"마음을 사로잡다",fasten:"(사람·동물 따위를) 가두어 놓다",immure:"감금하다",impound:"(사람을) 가두다",incarcerate:"투옥하다",leash:"가죽 끈으로 매다, 억제하다",manacle:"수갑을 채우다",rein:"고삐를 채우다",restrain:"제지하다",restrict:"제한하다",secure:"안전하게 보관된; 도망칠 우려 없는",tether:"(밧줄·사슬로) 매다",
archaic:"고풍의, 낡은",musty:"케케묵은",obsolescent:"쇠퇴해 가고 있는",obsolete:"시대에 뒤진",outmoded:"유행에 뒤떨어진",passe:"한창때가 지난",
disentangle:"-의 엉킨 것을 풀다; 해결하다",extricate:"(위험·곤경에서) 구출하다",unravel:"(엉클어진 것들을) 풀다; 해명하다",untangle:"(분규·불화 등을) 해결하다",
capitulate:"조건부로 항복하다",subside:"무릎 꿇다, 굴복하다",succumb:"굴복하다",yield:"굴복하다",
dearth:"부족",deficiency:"결핍",destitution:"빈곤",exiguity:"근소",famine:"기근",impecuniosity:"(언제나) 가난함",impecuniousness:"(언제나) 가난함",impoverishment:"빈곤화, 궁핍화",indigence:"가난",paucity:"소수; 결핍",penury:"빈곤",privation:"(생활필수품 등의) 결여",scarcity:"부족, 결핍",
destitute:"빈곤한",exiguous:"근소한",impecunious:"무일푼의",impoverished:"가난해진",indigent:"곤궁한",needy:"가난한",penurious:"몹시 아끼는, 인색한",
boredom:"권태",ennui:"권태, 지루함",languor:"피로, 무기력",lassitude:"(정신·육체적) 나른함",tedium:"싫증",weariness:"피로함",
cacophonous:"불협화음의",discordant:"조화를 이루지 못하는",harsh:"귀에 거슬리는",obtrusive:"주제넘게 참견하는; 눈에 거슬리는",protrusive:"돌출한; 주제넘게 나서는; 뻔뻔스러운",raucous:"무질서하고 소란한",shrill:"(소리가) 날카로운",strident:"(소리가) 귀에 거슬리는",grating:"삐걱 소리의; 거슬리는",raspy:"삐걱거리는 소리의; 신경질적인",
annoying:"성가신",fretful:"초조한",irksome:"넌더리나는",pesky:"귀찮은",plaguy:"귀찮은 일",plaguey:"귀찮은 일",plaguesome:"귀찮은 일",troublesome:"골치 아픈",trying:"고된",gadfly:"귀찮은 사람",plague:"말썽꾸러기",pest:"골칫거리",wasp:"성나게 하는 것",vermin:"해로운 작은 동물"
});
Object.assign(window.__V502_EXT__.categorySummaries,{
"071":"restraint / bondage","072":"restrain / fetter","073":"obsolete / archaic","074":"extricate / disentangle","075":"capitulate / yield","076":"poverty / scarcity","077":"destitute / indigent","078":"boredom / ennui","079":"cacophonous / strident","080":"annoying / troublesome"
});

Object.assign(window.__V502_EXT__.wordMeanings,{
  "annoying":"성가신",
  "archaic":"고풍의, 낡은",
  "bondage":"속박",
  "boredom":"권태",
  "bridle":"-에 굴레를 씌우다",
  "cacophonous":"불협화음의",
  "capitulate":"조건부로 항복하다",
  "coercion":"강제, 위압",
  "constrain":"구속하다, 제한하다",
  "cramp":"제한하다, 가두다",
  "cuff":"수갑",
  "curb":"억제하다, 구속하다",
  "custody":"보호, 감독; 구금",
  "dearth":"부족",
  "deficiency":"결핍",
  "destitute":"빈곤한",
  "destitution":"빈곤",
  "detain":"붙들어 두다, 구금하다",
  "discordant":"조화하지 않는",
  "disentangle":"-의 엉킨 것을 풀다; 해결하다",
  "duress":"구속",
  "enfetter":"속박하다, 노예로 만들다",
  "ennui":"권태, 지루함",
  "enthrall":"마음을 사로잡다",
  "exiguity":"근소",
  "exiguous":"근소한                   귀찮고 성가신 것",
  "extricate":"(위험·곤경에서) 구출하다, 해방하다",
  "famine":"기근",
  "fasten":"(사람·동물 따위를) 가두어 놓다",
  "fetter":"속박하다, 노예로 만들다",
  "fretful":"불평이 많은, 초조한",
  "gadfly":"귀찮은 사람",
  "grating":"삐걱 소리의; 거슬리는",
  "harsh":"귀에 거슬리는",
  "immure":"감금하다",
  "impecuniosity":"(언제나) 가난함",
  "impecunious":"무일푼의",
  "impecuniousness":"(언제나) 가난함",
  "impound":"(사람을) 가두다, (증거물 따위를) 압수하다",
  "impoverished":"가난해진; 힘을 잃은",
  "impoverishment":"빈곤화, 궁핍화",
  "incarcerate":"투옥하다",
  "incarceration":"투옥하다",
  "indigence":"가난",
  "indigent":"곤궁한",
  "irksome":"넌더리나는              전쟁을 좋아하는",
  "languor":"피로, 무기력",
  "lassitude":"(정신·육체적) 나른함",
  "leash":"가죽 끈으로 매다, 억제하다",
  "manacle":"수갑을 채우다",
  "musty":"진부한, 케케묵은",
  "needy":"가난한",
  "obsolescent":"쇠퇴해 가고 있는",
  "obsolete":"시대에 뒤진",
  "obtrusive":"(보기 싫게) 눈에 띄는       유리한, 유익한",
  "outmoded":"유행에 뒤떨어진",
  "passe":"한창때가 지난",
  "paucity":"소수; 결핍",
  "penurious":"몹시 아끼는, 인색한; 빈곤한",
  "penury":"빈곤",
  "pesky":"귀찮은",
  "pest":"골칫거리",
  "plague":"귀찮은 일, 말썽꾸러기",
  "plaguesome":"성가신             소송을 좋아하는                           난투, 소란스러운 말다툼",
  "plaguey":"성가신, 귀찮은",
  "plaguy":"성가신, 귀찮은",
  "privation":"(생활필수품 등의) 결여",
  "protrusive":"돌출한; 주제넘게 나서는; 뻔뻔스러운",
  "raspy":"삐걱거리는 소리의; 신경질적인",
  "raucous":"무질서하고 소란한, 목이 쉰",
  "rein":"고삐를 채우다",
  "restrain":"제지하다, 억누르다",
  "restrict":"제한하다",
  "scarcity":"부족, 결핍",
  "secure":"(죄인 따위를) 붙잡다; 안전하게 보관된",
  "shackle":"-를 쇠고랑에 채우다",
  "shrill":"(소리가) 날카로운",
  "strident":"(소리가) 귀에 거슬리는",
  "subside":"무릎 꿇다, 굴복하다",
  "succumb":"굴복하다",
  "tedium":"싫증",
  "tether":"(밧줄·사슬로) 매다",
  "troublesome":"골치 아픈",
  "trying":"견디기 어려운, 고된",
  "unravel":"(엉클어진 것들을) 풀다; 해명하다",
  "untangle":"(불화 등을) 해결하다; -의 엉킨 것을 풀다",
  "vermin":"해로운 작은 동물",
  "wasp":"성나게 하는 것",
  "weariness":"피로함",
  "yield":"굴복하다",
  "yoke":"속박, 지배",
});
