// LOGIC TREE V502 — Categories 031-040
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"031",words:["idle", "indolent", "slothful", "slovenly", "sluggard", "sluggish", "slouch", "sloven"]},
  {id:"032",words:["revulsion", "upheaval", "vicissitude"]},
  {id:"033",words:["adage", "aphorism", "apothegm", "apophthegm"]},
  {id:"034",words:["coda", "denouement", "envoy", "epilogue", "explicit", "finale", "peroration", "outrance"]},
  {id:"035",words:["conjugal", "connubial", "marital", "matrimonial", "nuptial"]},
  {id:"036",words:["humility", "modesty", "humbleness"]},
  {id:"037",words:["border", "bound", "boundary", "brim", "brink", "edge"]},
  {id:"038",words:["alert", "vigilant", "wary", "watchful", "wide-awake"]},
  {id:"039",words:["abase", "belittle", "contemn", "debase", "degrade", "deprecate", "despise", "disdain", "disparage", "scorn", "underestimate", "underrate", "understate", "contemptuous", "disdainful", "scornful", "contemptible", "despicable", "ignominious", "ignoble", "humble", "scurvy"]},
  {id:"040",words:["brash", "rash", "headlong", "heady", "impetuous", "imprudent", "impulsive", "precipitant", "precipitate", "precipitous", "flippant", "frivolous", "giddy", "nervous", "restive", "skittish", "levity"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "abase":"깎아내리다",
  "adage":"격언",
  "alert":"방심 않는",
  "aphorism":"금언, 격언",
  "apophthegm":"격언",
  "apothegm":"격언",
  "belittle":"얕잡다",
  "border":"테두리",
  "bound":"(안쪽에서 본) 경계(선)",
  "boundary":"경계(선)",
  "brash":"경솔한",
  "brim":"(컵 등의) 가장자리",
  "brink":"(벼랑 따위의) 가장자리",
  "coda":"악곡의 종결부",
  "conjugal":"결혼의, 배우자의",
  "connubial":"결혼의, 부부의",
  "contemn":"모욕하다",
  "contemptible":"비열한",
  "contemptuous":"경멸적인",
  "debase":"(인품·품위·가치 따위를) 떨어뜨리다",
  "degrade":"지위를 낮추다",
  "denouement":"연극의 대단원",
  "deprecate":"업신여기다; 반대하다",
  "despicable":"경멸할 만한",
  "despise":"경멸하다",
  "disdain":"업신여기다; 업신여김",
  "disdainful":"업신여기는",
  "disparage":"폄하하다",
  "edge":"끝머리",
  "envoy":"시, 산문, 연극의 종결부",
  "epilogue":"발문, 산문의 종결부",
  "explicit":"소설 등의 대미",
  "finale":"악곡의 마지막 악장, 연극의 마지막 장",
  "flippant":"경솔한",
  "frivolous":"보잘것없는; 경솔한",
  "giddy":"경솔한, 들뜬",
  "headlong":"성급한, 저돌적인",
  "heady":"무모한",
  "humble":"(신분 등이) 천한; 겸손한",
  "humbleness":"겸손함; 하찮음",
  "humility":"겸손",
  "idle":"빈둥거리다",
  "ignoble":"비열한",
  "ignominious":"수치스러운",
  "impetuous":"성급한",
  "imprudent":"경솔한",
  "impulsive":"충동적인",
  "indolent":"나태한",
  "levity":"경박함, 촐싹거림",
  "marital":"남편의, 혼인의",
  "matrimonial":"결혼의",
  "modesty":"겸손",
  "nervous":"신경질적인; 흥분하기 쉬운",
  "nuptial":"결혼(식)의",
  "outrance":"싸움의 끝",
  "peroration":"연설의 종결부",
  "precipitant":"경솔한, 덤벙이는",
  "precipitate":"경솔한; 재촉하다",
  "precipitous":"경솔한, 무모한",
  "rash":"성급한",
  "restive":"고집 센",
  "revulsion":"(감정의 격변) 혐오; 불쾌",
  "scorn":"경멸하다",
  "scornful":"경멸하는",
  "scurvy":"상스러운; 괴혈병",
  "skittish":"겁이 많은",
  "slothful":"굼뜬",
  "slouch":"게으른 사람; 구부정한 걸음걸이",
  "sloven":"꾀죄죄한 사람",
  "slovenly":"(옷차림이) 단정치 못한",
  "sluggard":"게으름쟁이",
  "sluggish":"게으른",
  "underestimate":"과소평가하다",
  "underrate":"경시하다",
  "understate":"삼가서 말하다",
  "upheaval":"(사회 등의) 대격변",
  "vicissitude":"변화",
  "vigilant":"자지 않고 지키는",
  "wary":"경계하는",
  "watchful":"주의하는",
  "wide-awake":"완전히 잠이 깬; 정신을 바짝 차린"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "031":"게으른, 나태한",
  "033":"격변, 경구(警句), 속담",
  "034":"결말, 대단원, 종결부",
  "035":"결혼의",
  "037":"경계, 가장자리",
  "038":"경계하는, 방심하지 않는",
  "039":"경멸하다, 경시하다",
  "040":"경솔한, 성급한, 무모한"
});
