// LOGIC TREE V502 — Categories 091-100
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};
window.__V502_EXT__.categories.push(
{id:"091",words:["crabbed","dour","glum","morose","saturnine","sulky","sullen","surly"]},
{id:"092",words:["blissful","blithe","buoyant","cheerful","delectable","ecstatic","elated","exalted","exhilarated","exultant","gayful","gleeful","jocund","jolly","jovial","joyful","jubilant","mirthful"]},
{id:"093",words:["celebrate","delight","exult","glory","jubilate","rejoice","revel","triumph"]},
{id:"094",words:["elate","exalt","exhilarate","puff"]},
{id:"095",words:["accuse","incriminate","inculpate","indict","prosecute"]},
{id:"096",words:["antic","bizarre","crotchety","eccentric","erratic","extraordinary","freakish","idiosyncratic","offbeat","outlandish","outrageous","outre","phenomenal","quaint","queer","quirky","uncanny","unconventional","weird"]},
{id:"097",words:["exigent","imminent","impending","imperious","pressing"]},
{id:"098",words:["accustom","domesticate","habituate","inure","tame"]},
{id:"099",words:["amaze","appall","astonish","astound","consternate","dumbfound","flabbergast","jar","jolt","startle","stun","stupefy"]},
{id:"100",words:["caress","cuddle","embrace","fondle","hug"]}
);
Object.assign(window.__V502_EXT__.wordMeanings,{
crabbed:"심술궂은",dour:"뚱한; 음침한",glum:"뚱한, 음울한",morose:"기분이 언짢은; 침울한",saturnine:"무뚝뚝한; 음침한",sulky:"뾰루퉁한",sullen:"언짢은",surly:"퉁명스러운",
blissful:"더없이 행복한",blithe:"즐거운, 쾌활한",buoyant:"기운찬, 명랑한",cheerful:"기분 좋은, 기운찬",delectable:"즐거운, 기쁜",ecstatic:"황홀한",elated:"의기양양한, 우쭐대는",exalted:"우쭐한",exhilarated:"들뜬",exultant:"몹시 기뻐하는",gayful:"명랑한, 즐거운",gleeful:"매우 기뻐하는",jocund:"명랑한",jolly:"명랑한",jovial:"쾌활한",joyful:"즐거운, 기쁜",jubilant:"환호하는",mirthful:"유쾌한",
celebrate:"(식을 올려) 경축하다",delight:"매우 기뻐하다",exult:"크게 기뻐하다",glory:"기뻐하다; 자랑으로 여기다",jubilate:"환희하다",rejoice:"기뻐하다",revel:"매우 기뻐하다; 한껏 즐기다",triumph:"의기양양해 하다",
elate:"기운을 돋우다; 의기양양하게 하다",exalt:"몹시 기쁘게 하다, 의기양양하게 하다",exhilarate:"원기를 돋우다",puff:"우쭐대게 하다",
accuse:"고발하다",incriminate:"-에게 죄를 씌우다, 고소하다",inculpate:"연좌시키다, 고발하다",indict:"기소하다",prosecute:"기소하다",
antic:"기묘한, 기이한",bizarre:"기상천외의",crotchety:"별난 생각을 갖고 있는",eccentric:"괴짜인, 별난",erratic:"불규칙한, 변덕스러운",extraordinary:"기이한, 놀라운",freakish:"별난, 기이한",idiosyncratic:"특이한",offbeat:"상식을 벗어난; 엉뚱한",outlandish:"이국풍의; 이상스러운",outrageous:"별난, 이상한",outre:"기괴한; 색다른",phenomenal:"자연현상의; 놀랄만한; 천재적인",quaint:"기묘한, 기이한",queer:"이상한, 기묘한",quirky:"별난",uncanny:"괴기한",unconventional:"독특한",weird:"수상한",
exigent:"절박한, 긴급한",imminent:"절박한, 급박한",impending:"절박한; 임박한",imperious:"절박한, 긴급한",pressing:"절박한",
accustom:"습관이 들게 하다",domesticate:"(동물 따위를) 길들이다",habituate:"습관 들이다",inure:"익숙하게 하다",tame:"길들이다",
amaze:"깜짝 놀라게 하다",appall:"오싹 소름끼치게 하다",astonish:"놀라게 하다",astound:"아연실색케 하다",consternate:"깜짝 놀라게 하다",dumbfound:"-에 어이없어 말도 못 하게 하다",flabbergast:"소스라쳐 놀라게 하다",jar:"(정신적인) 충격",jolt:"-에 충격을 주다",startle:"깜짝 놀라다",stun:"깜짝 놀라게 하다",stupefy:"망연케 하다",
caress:"어루만지다, 애무하다",cuddle:"부둥켜 안다",embrace:"포옹하다",fondle:"귀여워하다",hug:"꼭 껴안다"
});
Object.assign(window.__V502_EXT__.categorySummaries,{
"091":"sullen / morose","092":"blithe / ecstatic","093":"rejoice / exult","094":"elate / exhilarate","095":"accuse / indict","096":"bizarre / eccentric","097":"imminent / pressing","098":"accustom / domesticate","099":"astonish / flabbergast","100":"embrace / caress"
});

Object.assign(window.__V502_EXT__.wordMeanings,{
  "accuse":"고발하다",
  "accustom":"습관이 들게 하다",
  "amaze":"깜짝 놀라게 하다",
  "antic":"기묘한, 기이한",
  "appall":"오싹 소름끼치게 하다",
  "astonish":"놀라게 하다",
  "astound":"아연실색케 하다",
  "bizarre":"기상천외의",
  "blissful":"더없이 행복한",
  "blithe":"즐거운, 쾌활한",
  "buoyant":"기운찬, 명랑한",
  "caress":"어루만지다, 애무하다",
  "celebrate":"(식을 올려) 경축하다",
  "cheerful":"기분 좋은, 기운찬",
  "consternate":"깜짝 놀라게 하다",
  "crabbed":"(필적 등이) 알아보기 힘든, 심술궂은",
  "crotchety":"별난 생각을 갖고 있는",
  "cuddle":"부둥켜 안다",
  "delectable":"아주 맛있는, 즐거운, 기쁜",
  "delight":"매우 기뻐하다",
  "domesticate":"(동물 따위를) 길들이다",
  "dour":"뚱한; 음침한",
  "dumbfound":"-에 어이없어 말도 못 하게 하다",
  "eccentric":"괴짜인, 별난",
  "ecstatic":"황홀한             96. 기이한, 이상한, 희귀한",
  "elate":"기운을 돋우다; 의기양양하게 하다",
  "elated":"의기양양한, 우쭐대는",
  "embrace":"포옹하다",
  "erratic":"일정하지 않은, 변하기 쉬운",
  "exalt":"몹시 기쁘게 하다, 의기양양하게 하다",
  "exalted":"고귀한, 우쭐한",
  "exhilarate":"원기를 돋우다",
  "exhilarated":"(기분이) 들뜬",
  "exigent":"절박한, 긴급한",
  "extraordinary":"기이한, 놀라운",
  "exult":"크게 기뻐하다",
  "exultant":"몹시 기뻐하는",
  "flabbergast":"소스라쳐 놀라게 하다",
  "fondle":"귀여워하다",
  "freakish":"별난, 기이한",
  "gayful":"명랑한, 즐거운",
  "gleeful":"매우 기뻐하는",
  "glory":"기뻐하다; 자랑으로 여기다",
  "glum":"뚱한, 음울한             94. (몹시) 기쁘게 하다",
  "habituate":"습관 들이다",
  "hug":"꼭 껴안다",
  "idiosyncratic":"특이한",
  "imminent":"절박한, 급박한",
  "impending":"절박한; 임박한",
  "imperious":"고압적인; 오만한; 절박한, 긴급한",
  "incriminate":"-에게 죄를 씌우다, 고소하다, 비난하다",
  "inculpate":"연좌시키다, 고발하다",
  "indict":"기소하다",
  "inure":"익숙하게 하다",
  "jar":"(정신적인) 충격",
  "jocund":"명랑한, 즐거운",
  "jolly":"명랑한",
  "jolt":"-에 충격을 주다",
  "jovial":"쾌활한, 명랑한",
  "joyful":"즐거운, 기쁜",
  "jubilant":"환호하는",
  "jubilate":"환희하다",
  "mirthful":"유쾌한",
  "morose":"기분이 언짢은; 침울한",
  "offbeat":"상식을 벗어난; 엉뚱한",
  "outlandish":"이국풍의; 이상스러운",
  "outrageous":"별난, 이상한",
  "outre":"기괴한; 색다른                 100. 껴안다",
  "phenomenal":"자연현상의; 놀랄만한; 천재적인",
  "pressing":"절박한",
  "prosecute":"기소하다                 99. 깜짝 놀라게 하다",
  "puff":"우쭐대게 하다                   98. 길들이다, 익숙하게 하다",
  "quaint":"기묘한, 기이한",
  "queer":"이상한, 기묘한",
  "quirky":"별난",
  "rejoice":"기뻐하다",
  "revel":"매우 기뻐하다; 한껏 즐기다          97. 긴급한, 절박한",
  "saturnine":"무뚝뚝한; 음침한",
  "startle":"깜짝 놀라다",
  "stun":"깜짝 놀라게 하다",
  "stupefy":"지각을 잃게 하다; 망연케 하다",
  "sulky":"(날씨 따위가) 음산한; 뾰루퉁한",
  "sullen":"토라진, 골이 나서 말을 않는",
  "surly":"무뚝뚝한, 화를 잘 내는",
  "tame":"길들이다",
  "triumph":"의기양양해 하다",
  "uncanny":"괴기한",
  "unconventional":"독특한",
  "weird":"수상한",
});
