// LOGIC TREE V502 — Categories 071-080
window.__V502_EXT__=window.__V502_EXT__||{};
window.__V502_EXT__.categories=window.__V502_EXT__.categories||[];
window.__V502_EXT__.wordMeanings=window.__V502_EXT__.wordMeanings||{};
window.__V502_EXT__.categorySummaries=window.__V502_EXT__.categorySummaries||{};
window.__V502_EXT__.confusionNotes=window.__V502_EXT__.confusionNotes||{};

window.__V502_EXT__.categories.push(
  {id:"071",words:["bondage", "coercion", "cuff", "custody", "duress", "incarceration", "shackle", "yoke"]},
  {id:"072",words:["bridle", "constrain", "cramp", "curb", "detain", "fetter", "enfetter", "enthrall", "fasten", "immure", "impound", "incarcerate", "leash", "manacle", "rein", "restrain", "restrict", "secure", "shackle", "tether"]},
  {id:"073",words:["archaic", "musty", "obsolescent", "obsolete", "outmoded"]},
  {id:"074",words:["disentangle", "extricate", "unravel", "untangle"]},
  {id:"075",words:["capitulate", "subside", "succumb", "yield"]},
  {id:"076",words:["dearth", "deficiency", "destitution", "exiguity", "famine", "impecuniosity", "impecuniousness", "impoverishment", "indigence", "paucity", "penury", "privation", "scarcity"]},
  {id:"077",words:["destitute", "exiguous", "impecunious", "impoverished", "indigent", "needy", "penurious"]},
  {id:"078",words:["boredom", "ennui", "languor", "lassitude", "tedium", "weariness"]},
  {id:"079",words:["cacophonous", "discordant", "harsh", "obtrusive", "protrusive", "raucous", "shrill", "strident", "grating", "raspy"]},
  {id:"080",words:["annoying", "fretful", "irksome", "pesky", "plaguy", "plaguey", "plaguesome", "troublesome", "trying", "gadfly", "plague", "pest", "wasp", "vermin"]}
);

Object.assign(window.__V502_EXT__.wordMeanings,{
  "annoying":"성가신",
  "archaic":"고풍의, 낡은",
  "bondage":"속박",
  "boredom":"권태",
  "bridle":"-에 굴레를 씌우다",
  "cacophonous":"불협화음의",
  "capitulate":"조건부로 항복하다",
  "coercion":"강제, 위압",
  "constrain":"구속하다",
  "cramp":"제한하다, 가두다",
  "cuff":"수갑",
  "curb":"억제하다, 구속하다",
  "custody":"구금",
  "dearth":"부족",
  "deficiency":"결핍",
  "destitute":"빈곤한",
  "destitution":"빈곤",
  "detain":"붙들어 두다, 구금하다",
  "discordant":"조화를 이루지 못하는",
  "disentangle":"-의 엉킨 것을 풀다; 해결하다",
  "duress":"구속",
  "enfetter":"속박하다, 노예로 만들다",
  "ennui":"권태, 지루함",
  "enthrall":"마음을 사로잡다",
  "exiguity":"근소",
  "exiguous":"근소한",
  "extricate":"(위험·곤경에서) 구출하다",
  "famine":"기근",
  "fasten":"(사람·동물 따위를) 가두어 놓다",
  "fetter":"속박하다, 노예로 만들다",
  "fretful":"초조한",
  "gadfly":"귀찮은 사람",
  "grating":"삐걱 소리의; 거슬리는",
  "harsh":"가혹한, 거친",
  "immure":"감금하다",
  "impecuniosity":"(언제나) 가난함",
  "impecunious":"무일푼의",
  "impecuniousness":"(언제나) 가난함",
  "impound":"(사람을) 가두다",
  "impoverished":"가난해진; 힘을 잃은",
  "impoverishment":"빈곤화, 궁핍화",
  "incarcerate":"투옥하다",
  "incarceration":"투옥하다",
  "indigence":"가난",
  "indigent":"곤궁한",
  "irksome":"넌더리나는",
  "languor":"피로, 무기력",
  "lassitude":"(정신·육체적) 나른함",
  "leash":"가죽 끈으로 매다, 억제하다",
  "manacle":"수갑을 채우다",
  "musty":"케케묵은",
  "needy":"가난한",
  "obsolescent":"쇠퇴해 가고 있는",
  "obsolete":"시대에 뒤진",
  "obtrusive":"(보기 싫게) 눈에 띄는",
  "outmoded":"유행에 뒤떨어진",
  "paucity":"소수; 결핍",
  "penurious":"몹시 아끼는; 빈곤한",
  "penury":"빈곤",
  "pesky":"귀찮은",
  "pest":"골칫거리",
  "plague":"귀찮은 일",
  "plaguesome":"성가신",
  "plaguey":"성가신",
  "plaguy":"성가신",
  "privation":"(생활필수품 등의) 결여",
  "protrusive":"주제넘게 나서는",
  "raspy":"삐걱거리는 소리의; 신경질적인",
  "raucous":"목이 쉰",
  "rein":"고삐를 채우다",
  "restrain":"제지하다",
  "restrict":"제한하다",
  "scarcity":"부족, 결핍",
  "secure":"안전하게 보관된; 도망칠 우려 없는",
  "shackle":"-에 쇠고랑을 채우다",
  "shrill":"(소리가) 날카로운",
  "strident":"귀에 거슬리는 (소리)",
  "subside":"무릎 꿇다, 굴복하다",
  "succumb":"굴복하다",
  "tedium":"싫증",
  "tether":"(밧줄·사슬로) 매다",
  "troublesome":"골치 아픈",
  "trying":"견디기 어려운",
  "unravel":"(엉클어진 것들을) 풀다; 해명하다",
  "untangle":"(분규·불화 등을) 해결하다",
  "vermin":"해로운 작은 동물",
  "wasp":"성나게 하는 것",
  "weariness":"피로함",
  "yield":"굴복하다",
  "yoke":"속박, 지배"
});

Object.assign(window.__V502_EXT__.categorySummaries,{
  "071":"구속, 구금, 속박",
  "072":"구속하다, 속박하다",
  "073":"구식의, 쓸모없는",
  "074":"(복잡한 문제, 난처한 일에서) 구출하다, 해결해주다",
  "075":"굴복하다, 항복하다",
  "076":"궁핍, 가난",
  "077":"궁핍한, 가난한",
  "078":"권태, 따분함",
  "079":"귀에 거슬리는",
  "080":"귀찮게 하는"
});
